### ISSUE TITLE
View by OSO team (contributors spanning more than one project)

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#101]
### Describe the feature you'd like to request

In the future, when we allow users to create their own projects and collections, it'd be nice to be able to see all of the projects and collections owned by an OSO team.

For now, we can just focus on our official organization, which shows canonical verified projects and collections as defined by [oss-directory](https://github.com/hypercerts-org/oss-directory)

### Describe the solution you'd like

TBD

### Describe alternatives you've considered

TBD

**Comment by ccerv1** [comment]
We will start with the degenerate case where the organization is the project (ie, `Uniswap` the organization is also `Uniswap` the project)

See also #102 

It should be at `/org/slug/` (to do: learn how to create dynamic pages in Plasmic)

**Comment by ryscheng** [comment]
@ccerv1 can you start with this?
https://github.com/hypercerts-org/oso/issues/100

This issue is a placeholder for when we get to allowing people define their own collections and projects, and we might want to have some team abstraction within OSO for owning these user-defined projects/collections.

In other words, just focus on
- `/projects/slug/` - https://github.com/hypercerts-org/oso/issues/100
- `/artifacts/id/` - https://github.com/hypercerts-org/oso/issues/99
- `/collections/id` - https://github.com/hypercerts-org/oso/issues/102

**Comment by ccerv1** [comment]
Yep, will re-jigger

**Comment by ryscheng** [comment]
Wow this issue is 1 year old.
Happy to share that we finally did this, effectively by creating /collections, /projects, and /artifacts.

Closing this for now, we can file new issues when we have specific changes we want to make around the current behavior
