### ISSUE TITLE
Docs: Contributing dbt models should assume you don't have write access

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1016]
### What is the improvement or update you wish to see?

Right now, I think users writing a new dbt model will fail, because they don't have write access to our GCP account.

I moved the `setting up your own copy of the oso_playground` from "getting started" to this section. We should explain how to setup your own little playground area to run dbt models

### Is there any context that might help us understand?

If we do this, then .dbt/profiles.yml needs to be updated to reflect this right?
Also, I think there's a bug in the existing profiles.yml as written, shouldn't the dataset under playground be the playground dataset?

### Does the docs page already exist? Please link to it.

http://localhost:3000/docs/contribute/impact-models

**Comment by ravenac95** [comment]
Closed with #1024
