### ISSUE TITLE
Discussion: Let's talk about impact vectors

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1017]
### What is it?

This is probably something we should just discuss in meeting tomorrow, but I'm kinda confused by the notion of an impact vector:

Vectors are typically just a quantity and a direction (https://www.merriam-webster.com/dictionary/vector). We seem to also add a bunch of constraints around time and normalization and stuff that don't seem vector-like, but I'm still brainstorming for a different name.

 I think you're trying to describe a way to compare impact metrics across a group of projects? Can't we just stick to "impact metric"? An impact metric can just be a normalized version of another impact metric. And impact metrics are already aggregated over a discrete period of time.

**Comment by ryscheng** [comment]
Here's my mental model, curious if it fits with what you guys think:

A metric is a single quantity (e.g. like commits) 
A vector (like in linear algebra) is a group of metrics + the project_id + the time. Basically a row of our KPI table or metrics table.

**Comment by ccerv1** [comment]
@ryscheng made some edits #1022 - let me know if you have further improvements. I looked into expressing it mathematically, but was dissuaded by needing to import [KaTeX](https://docusaurus.io/docs/markdown-features/math-equations)
