### ISSUE TITLE
Wire up the collection page

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#102]
### Describe the feature you'd like to request

Be able to view a collection of projects

This is a step on the way to getting to the full UI/UX of a stats table for the collection.

### Describe the solution you'd like

TBD

### Describe alternatives you've considered

TBD

**Comment by ccerv1** [comment]
For now, this will be handled as several variants on the current explore UI with the ability to access additional metrics, probably similar to how Messari handles this.



![Image](https://github.com/hypercerts-org/oso/assets/42869436/e0dffce7-1683-4438-82c7-11329e34ba68)

**Comment by ccerv1** [comment]
See inspo from [here](https://web3metrics.com/polkadot)



![Image](https://github.com/hypercerts-org/oso/assets/42869436/9d9a2d13-ea09-4fb4-9f9e-71623b20c4a1)

**Comment by ccerv1** [comment]
@ryscheng I've added the dateOptions component plus a settings/filters widget that when a user clicks will give them options for selecting additional metrics. For now, we can ignore implementing a filters feature (eg, "num contributors with more than X contributions").


![Image](https://github.com/hypercerts-org/oso/assets/42869436/731c6c7c-9982-4f0e-ab02-d07b65cbe112)

**Comment by ccerv1** [comment]
Next steps: implement a filter option to add / change metrics in the table

**Comment by ryscheng** [comment]
From discord

Regarding the demo for Oct 2, here's the minimum I think we should aim for in the explore view:

- I can filter projects by collection [there will be a variety of OP-related collections in oss-directory]
- I can see the following indicators in a sortable table, by project:
    - Number of repos it owns [from github event data]
    - Total forks for all of those repos [from github event data]
    - Total unique contributors for all of those repos [from github event data]
    - Total active developers for all of of those repos [from github event data]
    - Number of contracts deployed on Optimism [same as oss-directory]
    - Number of wallet addresses for receiving funds on Optimism [same as oss-directory]
    - Number of npm packages it owns [same as oss-directory]
- I can further filter by date range [this filters the github event data only]

Stretch goal:

- I can click on a project in the table and be brought to its project page
- The project page displays real data for Onchain Impact (Metrics related to a project's onchain contracts and the resulting sequencer fees, transaction volumes, and user activity.)
- The project page displays real GitHub event data (Metrics related to code and developer contributions for the project.)

**Comment by ryscheng** [comment]
Adding an API endpoint for getting data here
https://github.com/opensource-observer/oso/pull/466

**Comment by ryscheng** [comment]
Gonna close this out for now, filing subsequent issues on bugs and feature / refinements.
