### ISSUE TITLE
CI validate new blockchain artifacts and auto-create downstream artifacts (eg, from a deployer address)

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1034]
I've written some spaghetti scripts that does this manually (see also opensource-observer/oss-directory#29), but ideally we would have the following types of modules that can be triggered from changes to an OSS Directory project file:

## `add_eoa`

An address with an `eoa` tag that is added to OSS Directory (wallet, deployer, etc) should be validated to determine if it is an EOA account. Currently, I use the [Alchemy API](https://docs.alchemy.com/reference/eth-getcode) `eth-getcode`. If the API returns `0x` then it is an EOA.

When a new `eoa` is added, we should:
- **validate** that it is an EOA (not a smart contract)
- **validate** that it isn't owned anywhere else (even on other networks)
- **lookup** the ENS name on ETH mainnet

At some regular interval (eg, weekly), we should refresh the ENS names.

## `add_deployer`

An address with a `deployer` tag is an EOA  controlled by a project that is used for deploying smart contracts. For instance, [here](https://github.com/duneanalytics/spellbook/blob/main/models/_sector/contracts/contracts_contract_creator_address_list.sql) is a list of deployers that OP Labs use to trace deployments on Dune.

The same `deployer` is typically used across multiple chains, so this is a better way of tracking multi-chain apps.

When a `deployer` is linked to a project, we should trace all contracts that have been deployed by the address and, if they meet certain requirements, those contracts should become artifacts that are linked to the project. Currently, I use the [Etherscan API](https://docs.etherscan.io/api-endpoints/accounts#get-a-list-of-normal-transactions-by-address) `txlist` action and run the following validation logic on the result: `[tx['contractAddress'] for tx in result if not tx['to'] and tx['input'] and tx['isError'] == '0']`

When a new `deployer` is added, we should:
- **validate** that it is an EOA (see above)
- **validate** that it has deployed at least one contract on any chain
- **crawl** all relevant networks to identify contracts deployed by the address; they should be added as new artifacts provided they meet certain validation criteria (see below)

At some regular interval (eg, weekly), we should **crawl** for new deployments and add those contracts.

A user should also be able to trigger a **crawl** for a project or address manually.

## `add_safe`

A `safe` is a wallet controlled by a smart contract. An address with a `safe` tag should be validated to determine it was created through one of the factory addresses maintained by Safe Global. It should not have the `contract` tag associated with it. Currently, I do this in a lazy way looking up the contract name on Etherscan and validating it if it contains certain keywords (eg, "safe", "multisig", "proxy") 

When a new `safe` is added, we should:
- **validate** that it was generated from one of the known Safe factories 
- **crawl** all relevant networks to identify other instances of the same Safe address [nice to have]
- **lookup** the ENS name on ETH mainnet

At some regular interval (eg, weekly), we should refresh the ENS names.

## `add_contract`

In the future, the majority of contracts will be added via `add_deployer` but there will still be cases of contracts that may be manually added. For instance, some contracts (like [ethereum-attestation-service](https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000020)) are included in the GENESIS block. Others are deployed via a [deterministic deployer contract](https://github.com/Arachnid/deterministic-deployment-proxy). 

When a new `contract` is added, we should:
- **validate** that is not an EOA
- **validate** that it does not have an EOA deployer that belongs to another project
- **lookup** the contract name, if it has one

## `validate_factory`

A `factory` is a smart contract that deploys other contracts. All `contract` addresses should be reviewed to determine if they are a `factory` or not. If they are a `factory`, then the contracts deployed by them should be counted as part of their downstream impact (but should not be separate artifacts).

**Comment by ravenac95** [comment]
Decomposed!
