### ISSUE TITLE
Video tutorials of each docs guide

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1037]

**Comment by ccerv1** [comment]
@ravenac95 I would love to see some 2 minute Loom videos for Dagster jobs. The following are probably most relevant but I'm sure there are more:

- [ ] Syncing OSS Directory
- [ ] Triggering a full run
- [ ] Triggering a run for a specific source
- [ ] Triggering a backfill
- [ ] Re-materializing a metric model and everything downstream

**Comment by ravenac95** [comment]
* Syncing OSS Directory: https://www.loom.com/share/9342f91620e1416e83a9823a605d5bf4
* Trigging a full run (and also specific dbt environments including backfill): https://www.loom.com/share/55534d1aa6cd4187a2d52ec98709edf1
* Triggering a run for a specific source: https://www.loom.com/share/5a2818d05bed4fc8a4a153b72b07ee8d
* Rematerializing a metric model: https://www.loom.com/share/0b673d1c8e9a494ab30d84bbb9d9134a

**Comment by ccerv1** [comment]
Thanks @ravenac95 - these are great. I added all of them a Tutorials Space on Loom. You should be able to access it here: https://www.loom.com/spaces/All-Kariba-Labs-24123308/folders/Tutorials-7be451e369fb4fe788137545eb8d2469
