### ISSUE TITLE
oss-directory: Automated EOA and Deployer validation

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1047]
### Describe the feature you'd like to request

An address with an `eoa` or `deployer` tag that is added to OSS Directory (wallet, deployer, etc) should be validated to determine if it is an EOA account. Currently, I use the [Alchemy API](https://docs.alchemy.com/reference/eth-getcode) eth-getcode. If the API returns 0x then it is an EOA.

### Describe the solution you'd like

When a new eoa or deployer is added, we should:

* validate that it is an EOA (not a smart contract)
* validate that it isn't owned anywhere else (even on other networks)
* lookup the ENS name on ETH mainnet
* At some regular interval (eg, weekly), we should refresh the ENS names.

For deployers we add these additional validations:

* validate it has deployed at least one contract on any chain 

### Describe alternatives you've considered

N/A

**Comment by ravenac95** [comment]
Decomposition of #1034

**Comment by ravenac95** [comment]
@ccerv1 i just noticed one of the bullets here:

> * validate that it isn't owned anywhere else (even on other networks)

What do you mean exactly? If the address is on both networks we would just want to include both networks yes?

**Comment by ccerv1** [comment]
@ravenac95 I was referring to a conflict that could occur if project A claimed a deployer on network X and project B claimed a deployer on network Y.

**Comment by ravenac95** [comment]
Closed with https://github.com/opensource-observer/oss-directory/pull/232
