### ISSUE TITLE
Design user reputation data challenge

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1053]
### What is it?

Let's have a future data challenge around user reputations in Optimism. 

Related issues: it'd be nice to get these datasets before hand https://github.com/opensource-observer/oso/issues/1007 and https://github.com/opensource-observer/oso/issues/839

**Comment by ccerv1** [comment]
FYI, from Emily just now: https://www.notion.so/Round-5-Guest-Voter-Selection-OSO-Karma3-45d4e95f5f7346138c3c805d27c69648

**Comment by ryscheng** [comment]
@ccerv1 "Either this page doesn't exist or you don't have permission to access it."

**Comment by ryscheng** [comment]
Potentially collaborate with 
https://read.cryptodatabytes.com/p/cb7bb290-0295-4edf-8cd6-cae9b797681c

CC @ccerv1

**Comment by ccerv1** [comment]
https://app.hex.tech/00bffd76-9d33-4243-8e7e-9add359f25c7/app/1488806c-cc70-4245-b8f6-78ace4a5a0e7/latest
