### ISSUE TITLE
Farcaster as a public data set

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1055]
### What is it?

Easy enough to replicate a "hub", we should get all that data into a public dataset to populate OSO users as well

**Comment by davidgasquez** [comment]
I think you can also pay and get access to https://neynar.com/ database. Not sure if you can replicate all their data though!

**Comment by ryscheng** [comment]
Ya seems like there are 2 high level approaches we can take:

1. Use the Farcaster [replicator](https://github.com/farcasterxyz/hub-monorepo/tree/main/apps/replicator) to replicate the data to a Postgres database. ([Docs](https://docs.farcaster.xyz/developers/guides/apps/replicate)). This is a Node.js app that Farcaster maintains, and likely what all the services below depend on.
2. Use a Farcaster API. I'm aware of 2, [Neynar](https://neynar.com/) and [Pinata](https://www.pinata.cloud/farcaster). We'd probably need to write an airbyte connector to pull from these APIs.

Second option seems cleaner in terms of following the same architecture as our other connectors, but adds an unnecessary service dependency.
First option seems like the most direct approach, but requires us to run a Node.js app / docker container.

**Comment by ryscheng** [comment]
Current plan:

- Just use the replicator terraform scripts
- Setup Airbyte to do replication to BQ

**Comment by ryscheng** [comment]
Another option
https://blog.indexing.co/posts/IaPkkuevwwfgBWtZ3F7eg5oQUqyV_o6sLDo28oEV8Tg

**Comment by ryscheng** [comment]
This is done via BigQuery data transfer service.
It was manually setup for the time being, there’s a separate issue for putting this into Dagster
https://github.com/opensource-observer/oso/issues/1311

**Comment by ryscheng** [comment]
Staging models here
https://github.com/opensource-observer/oso/pull/1320
