### ISSUE TITLE
Use the Graph for indexing on-chain data

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#109]
### Describe the feature you'd like to request

It looks like substreams has progressed significantly, where it might make sense to revisit whether we use the Graph for these indexing jobs
https://thegraph.com/docs/en/substreams/README/

TLDR:
- A superset of what you can do with subgraphs, strictly more powerful, includes the ability to use other substreams in your substream. Also ability to mix substreams across chains
- Exposes same GraphQL interface we're used to
- about 100x faster, which makes it more possible to use it for analytics/exploration
- 2 catches: you have to write them in Rust and they only support Ethereum mainnet atm

### Describe the solution you'd like

Write some substreams that follow what we want.

Perhaps a workflow might look like:
1. Use Dune for exploration, figure out what we want to index
2. Use substreams when we have a clearer idea of what we want to index
3. Use GraphQL to query the substream for data

### Describe alternatives you've considered

Something else we can consider is to leverage existing subgraphs, if we can find one that fits our needs. 
Maybe look at the subgraphs maintained by
- [DappLooker](https://dapplooker.com/)
- [Messari](https://messari.io/protocol-explorer/all-protocols)
- [Playgrounds](https://playgrounds.network/)

**Comment by ryscheng** [comment]
If there are existing subgraphs to leverage, that might be cool
https://github.com/messari/subgraphs

**Comment by ryscheng** [comment]
Sounds like we're going to backlog this until after the MVP. Hopefully by then their substrream support for Optimism will be better.

**Comment by ravenac95** [comment]
I think we should close this as we're moving a different direction.
