### ISSUE TITLE
Metrics schema v1

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1096]
### What is it?

As we move towards a world where there are increasing impact metrics, we will probably want a separate schema rather than jamming everything into our two metrics tables.

A metric schema would likely need to include:
- An artifact / project / collection id
- A time bucket
- A namespace (eg, a blockchain network or 'all networks')
- The metric itself
- A value

Creating this issue mostly as a placeholder to have this discussion and consider implications on our events tables and marts.

**Comment by ccerv1** [comment]
I've created some drawings of our data model. Curious what you think? Would like to add to the docs if you likey!

https://excalidraw.com/#room=085dd83317dbd3b54022,eBDfByMzUw3G_f1VbjwxfQ


![Image](https://github.com/opensource-observer/oso/assets/42869436/d6f7d47f-178e-4571-9a66-b97e4a2d11cb)


![Image](https://github.com/opensource-observer/oso/assets/42869436/5b915eb7-d604-4349-afd4-b1f6c7bd7646)


![Image](https://github.com/opensource-observer/oso/assets/42869436/a80d61d7-c944-406f-889c-e64b38e98755)


![Image](https://github.com/opensource-observer/oso/assets/42869436/0d1d8f4b-1266-4274-8718-7e211d516261)

**Comment by ryscheng** [comment]
lgtm

Feedback from our call:
- It'd be nice to be able to capture the many-to-many relationships from collections to project, and separately the 1-to-many relationships from projects to artifacts.
- Also, users are going to be more abstract, which could include multiple artifacts as well.

But I say ship it, we should be iterating on these things regularly.

**Comment by ccerv1** [comment]
https://github.com/opensource-observer/oso/pull/1156
