### ISSUE TITLE
Create unit tests for API endpoints and database ops

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#11]
### What is it?

Placeholder until API spec is further built out

**Comment by ravenac95** [comment]
@ryscheng @ccerv1 While I'd like tests in general, what exactly would we want to be testing? It'd mostly be making sure that our dbt models are functioning as we say they will.

**Comment by ryscheng** [comment]
Hasura is pretty automagic. I think we should treat this as obsolete until we have explicit tests we want to see
