### ISSUE TITLE
Only deploy a PR dataset when something in the `warehouse/` directory changes

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1116]
### Describe the feature you'd like to request

We should only deploy when the `warehouse/` directory changes 

### Describe the solution you'd like

We should scan for changed files and only trigger a deploy if the changed files include one of the models or their dependencies. 

### Describe alternatives you've considered

N/A

**Comment by ryscheng** [comment]
@ravenac95 I vaguely recall we did something here a bit ago?

**Comment by ravenac95** [comment]
Ah yeah we did do this.
