### ISSUE TITLE
Capture events from all forked repositories

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1121]
### Describe the feature you'd like to request

In order to better collect all of the commit data we should get more events from forked repositories. For things like, squash commits it would be good to still get additional information about the what exactly was squashed (how many commits, how many authors). We lose all of that information right now and the only way to get it for PRs from forks is if we extend the reach of the our event capture to forks. 

### Describe the solution you'd like

There should be some separate query likely before we result the `stg_github__events` model that first checks for any recent forks of the projects we're monitoring. Then we will include those forks into a table that we join with our list of projects to filter githubarchive events. 

### Describe alternatives you've considered

N/A

**Comment by ravenac95** [comment]
Not sure yet if this is the _right_ thing to do but it could prove useful.

**Comment by ryscheng** [comment]
GH Archive gets this
