### ISSUE TITLE
Gitcoin Passport: setup database replication

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1136]
### What is it?

probably using Airbyte

**Comment by ccerv1** [comment]
@ravenac95 see this issue they've opened. Tagging you to provide two comments related to Airbyte: https://github.com/gitcoinco/passport/issues/2353

**Comment by ryscheng** [comment]
Sounds like Gitcoin doesn't want to do this. #1245 is what we'll do instead
