### ISSUE TITLE
Clickhouse sqlmesh pipeline

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1165]
### What is it?

dbt pipelines do not span warehouses.

Since we are already looking to do more stuff in Clickhouse, we can use this as a testing ground for sqlmesh. This is very P2 for the time being.

I filed a separate issue to move data in between the 2 pipelines: https://github.com/opensource-observer/oso/issues/1164

**Comment by ryscheng** [comment]
Deprioritizing this

**Comment by davidgasquez** [comment]
Probably doesn't cover 100% of the models as Clickhouse needs a somewhat different approach than BigQuery but [SQLGlot](https://github.com/tobymao/sqlglot) might be useful for the base models (can run at the Dagster level).

**Comment by ryscheng** [comment]
- column lineage - seeing schema changes
- test-deploy / playground in duckdb
- generated models per network

**Comment by ryscheng** [comment]
Going to backlog this for now, sqlmesh is working on Clickhouse integrations, but its not ready yet. There's only BigQuery, duckdb, and postgres

**Comment by ryscheng** [comment]
Updated scope:
@ravenac95 got this working off a sqlmesh branch.
Remaining work is to have it orchestrated by Dagster
