### ISSUE TITLE
dbt models should be using MetricFlow

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1179]
### What is it?

https://docs.getdbt.com/docs/build/build-metrics-intro

**Comment by ryscheng** [comment]
Fun facts:
<img width="1087" alt="Screen Shot 2024-04-22 at 13 25 07" src="https://github.com/opensource-observer/oso/assets/566890/4c1d98f0-ab30-4b4a-bda9-fc4d559f8865">

- dbt core MetricFlow is being deprecated. That explains why they're getting rid of all the documentation involving MetricFlow + dbt core
- Here's the migration guide to the new MetricFlow based on dbt cloud
https://docs.getdbt.com/guides/sl-migration?step=1
- You have to have a Team or Enterprise account to use this new version. There will be no free tier available.

I'm going to close this for now, we might still want to do this in the future, but not worth it for now.
