### ISSUE TITLE
Create a model to verify RF4 eligibility criteria

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1192]
### What is it?

Original [source](https://www.notion.so/Retro-Funding-4-Onchain-Builder-round-details-FORUM-POST-6fb3946fa5b6421bbf390b51fcb2bad9#c27d9780a5ca4383940fc77926cf076a)

Builders are eligible who have:

- Deployed their onchain contracts on one or multiple OP chains (OP Mainnet, Base, Zora, Mode, Frax and Metal) and meet the following criteria:
    - Onchain contracts have interactions from 420 unique addresses during Jan 1st - April 1st 2024
    - Onchain contracts had their first transaction before March 1st 2024
    - Onchain contract had more than 10 days of activity during Feb  1st - April 1st 2024
- Verified their onchain contracts in the Retro Funding sign up process
- Made their contract code available in a public Github repo, for which ownership has been verified in the Retro Funding sign up process

**Comment by ryscheng** [comment]
@ccerv1 see
https://github.com/opensource-observer/oso/issues/1175

**Comment by ccerv1** [comment]
This can be simulated here:

```
select
  project_id,
  project_name,
  COUNT(distinct from_artifact_name) as unique_addresses,
  MIN(bucket_day) as date_first_transaction,
  COUNT(distinct
    case
      when bucket_day between '2024-02-01' and '2024-04-01' then bucket_day
    end
  ) as days_with_onchain_activity_in_range
from `oso.rf4_events_daily_to_project`
where
  event_type = 'CONTRACT_INVOCATION_SUCCESS_DAILY_COUNT'
  and bucket_day >= '2024-01-01'
group by
  project_id,
  project_name
```

However, waiting for #1438 to merge before implementing this.
