### ISSUE TITLE
Create staging models for trace data by network

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1193]
### What is it?

The goal is to have a staging model for each blockchain source that feeds are event data models. This should probably be broken up into smaller issues based on where the data will be coming from (Goldsky vs BigQuery vs ???).

Anyway, here are the trace datasets we want to be able to query, roughly in order of priority:

Tier 1: most important for defining initial impact metrics
- [x] OP Mainnet
- [x] Base

Tier 2: large chains that we intend support
- [ ] Ethereum
- [ ] Arbitrum

Tier 3: smaller OP chains required for RF4 
- [x] Zora
- [x] Frax
- [x] Mode
- [ ] Metal (tbd - not currently on GoldSky)

**Comment by ryscheng** [comment]
We probably want to make one for each network, subfiltering on the traces that are "relevant"

This would include anything in oss-directory, maybe other data sources (e.g. like users)

**Comment by ryscheng** [comment]
We also need to hook up the traces staging model to `int_events`

**Comment by ravenac95** [comment]
I'm going to move Arbitrum and Metal to separate issues as we just got the metal data and we don't yet have traces for arbitrum.

**Comment by ccerv1** [comment]
Closing this out per discussion. Have opened separate issues for the remaining chains included in this issue.
