### ISSUE TITLE
Add Base contracts to OSS Directory

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1203]
[Here](https://github.com/ethzoomer/rpgf-data/blob/main/data/base20231203.json) is a great initial source of contracts that includes all RetroPGF3 projects on Base we can start with

**Comment by ryscheng** [comment]
I'd suggest down-scoping this to a 1, just testing with a couple of projects

**Comment by ccerv1** [comment]
Super easy to identify tagged deployers on other chains with a query like this:

```
WITH deployers AS (
  SELECT DISTINCT
    artifact_source_id,
    project_name 
  FROM `oso.artifacts_by_project_v1`
  WHERE artifact_type = 'DEPLOYER' 
)

SELECT
  deployers.project_name,
  b.deployer_address,
  COUNT(DISTINCT b.contract_address) AS count_contracts
FROM deployers
JOIN `oso.stg_base__deployers` b
  ON deployers.artifact_source_id = b.deployer_address
GROUP BY 1,2
ORDER BY 3 DESC

```

Will test a few projects now...

**Comment by ccerv1** [comment]
Currently blocked on #1428

**Comment by ccerv1** [comment]
https://github.com/opensource-observer/oss-directory/pull/286
