### ISSUE TITLE
oss-directory: Adding `.yml` files to the directory aren't captured or properly validated

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1224]
### To Reproduce

Add a file into a project that's a `.yml` file. It will be ignored by all validation methods and the project will not appear in the directory. 

### Describe the Bug

See above.

### Expected Behavior

We should fail validation if the file is named `.yml`. Currently the bug isn't really fatal but is an annoyance.

**Comment by ryscheng** [comment]
This was fixed here
https://github.com/opensource-observer/oss-directory/pull/273
