### ISSUE TITLE
Add `primary_github_owner` and `primary_github_owner_type` fields to the Projects mart

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1225]
### Describe the feature you'd like to request

API users would like to query a project and get the GitHub owner it is associated with

### Describe the solution you'd like

Additional fields in the Projects mart.
If there is more than one GitHub owner, choose the org or if there is more than one org then the one with the most recent activity as the primary. Owner type can be  `personal` or `organization`. May also want to consider a field to indicate projects with multiple owners.

### Describe alternatives you've considered

Users can grab this directly from BigQuery or by doing some filtering client side.

**Comment by ryscheng** [comment]
I'm not sure we want to do this, or at the very least we should understand the use case better.
If we expose this, and people start using it, it's going to be hard to tear out.

What semantic meaning does choosing "the one with the most recent activity as the primary" have? Why would I ever want that?

**Comment by ccerv1** [comment]
Update: I moved this to an int model, but we don't expose via the `project` mart.
