### ISSUE TITLE
Get Gitcoin Passport imported as static parquet dump

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1245]
### What is it?

Passport is doing some infra changes right now so this pushes back issue #1136 a few weeks. In the meantime we agreed to dump a parquet file in OSO so we can get users to start exploring the data.

**Comment by ryscheng** [comment]
@ravenac95 to send them auth today

**Comment by ccerv1** [comment]
@ravenac95 Nutrina is still awaiting auth per latest on their GitHub issue

**Comment by ravenac95** [comment]
@ccerv1 Oh. I just saw a message from this morning. A different auth method than originally discussed is being requested. I’ll create one

**Comment by ravenac95** [comment]
Oh actually upon closer read I think it’s just some confusion on how to use the creds I supplied. I responded over dm
