### ISSUE TITLE
Impact metrics extended descriptions with mock data

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1282]
See Agora's public roadmap:
https://argoagora.notion.site/Retro-Round-4-API-Roadmap-public-92adc5bdef8148cc98991e30b4066c8f

| Milestone | External Date | Status | Phase }
| -- | -- | -- | -- |
| Formal API schema & docs | April 22, 2024​ | Done | Pre-Alpha |
| RF API with mock data | April 22, 2024​ | Done | Alpha |
| RF Voting API beta | May 10, 2024​ |   | Beta |
| Projects & Metrics API beta with real data | June 7, 2024​ |   | Beta |
| Prod release | June 21, 2024​ |   | Post-Release |

**Comment by april** [comment]
if I might make a personal request, could you please not use @monthname for the dates please? 😅

**Comment by may** [comment]
+1 What April said.

**Comment by monthname** [comment]
+1!

**Comment by ryscheng** [comment]
The idea is to share the descriptions with Agora so that they can create impact "profile pages" for each

**Comment by ccerv1** [comment]
I've currently generated the first 8 that have already been reviewed and accepted by badgeholders [here](https://docs.google.com/document/d/1hZ35HC_FRwX5hhNmskRpA3AKSop0A9wDj6JEtz3K3zY/edit?usp=sharing). I'm going to add this as a blogpost that we can update as new metrics come in / get refined.

**Comment by ccerv1** [comment]
Sent as a CSV file powered by this query:

```
SELECT 
  project_name,
  * EXCEPT (project_id, project_name)
FROM `oso.rf4_impact_metrics_by_project`
WHERE
  trusted_transaction_share > 0.05
  and project_name != 'op'
ORDER by trusted_recurring_users DESC
LIMIT 50
```

with the copy for extended descriptions available [here](https://github.com/opensource-observer/oso/blob/main/apps/docs/blog/2024-05-16-impact-metrics-rf4/index.md#current-metrics)
