### ISSUE TITLE
Launch a read-only public instance of Dagster web server

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1322]
### What is it?

https://docs.dagster.io/_apidocs/cli

See —read-only

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oso/blob/main/ops/k8s-apps/base/dagster/dagster.yaml

**Comment by ravenac95** [comment]
attempting again here: #1607

**Comment by ravenac95** [comment]
Works!
