### ISSUE TITLE
Cleanup schemas across oss-directory to dbt models to API

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1335]
### What is it?

As of this PR https://github.com/opensource-observer/oso/pull/1334, we now have a style guide.
There are many instances where we violate this style guide. This is the meta-issue to just go through and clean it up

**Comment by ryscheng** [comment]
artifacts/projects/collections models
https://github.com/opensource-observer/oso/pull/1337

**Comment by ryscheng** [comment]
artifacts_by_project and projects_by_collection
here https://github.com/opensource-observer/oso/pull/1339

**Comment by ryscheng** [comment]
more here
https://github.com/opensource-observer/oso/pull/1340

**Comment by ryscheng** [comment]
A summary of the changes we want to make:

- Remove use of all positional arguments (e.g. `GROUP BY 1,2,3`)
- Replace all single-letter and acryonym names with a full name
- Move anything not labeled `_v1` in marts back to an intermediate model
- Make project/collection/artifact/user naming consistent. We decided to go with `_id`, `_source`, `_namespace`, `_name`.
- We'll move the historical list of artifact names to a new table `artifacts_history`. We should probably do the same with project/collection slugs (which will be renamed to `name`)
- Rename project_name to project_display_name
- Currently we have a separate artifact for each artifact type, even if its the same address. We should go back to collapsing this into a single artifact. We'll have a new 1-to-many table called `artifact_types` to reflect the many types an artifact could have.
-

**Comment by ccerv1** [comment]
Yes, I've reviewed and this covers everything. Let's do it.

**Comment by ryscheng** [comment]
update directory marts to alias here
https://github.com/opensource-observer/oso/pull/1352

**Comment by ccerv1** [comment]
first major round of model renames and moves
#1344

**Comment by ryscheng** [comment]
import oss-directory fixed here
https://github.com/opensource-observer/oso/pull/1356

**Comment by ryscheng** [comment]
renaming marts models columns here
https://github.com/opensource-observer/oso/pull/1355

**Comment by ryscheng** [comment]
publish oss-directory to npm here
https://github.com/opensource-observer/oss-directory/pull/278

**Comment by ryscheng** [comment]
oss-directory should import descriptions
https://github.com/opensource-observer/oso/pull/1360

**Comment by ryscheng** [comment]
Gonna close this for now, and track the followon work here:
https://github.com/opensource-observer/oso/issues/1365
