### ISSUE TITLE
Host a data challenge / hackathon IRL at Devcon 2024

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1368]
### What is it?

Collaborate with Metagov's "impact-a-thon" idea.
Plus FTC's hackathon
Plus our RF7 exploration with ByteExplorers.

**Comment by ryscheng** [comment]
David Casey offered to host it alongside the hackathon they're already doing as part of FTC.

**Comment by ryscheng** [comment]
FYI, here is the FTC page on Dorahacks
https://dorahacks.io/hackathon/ftc-2024/submission

They offered to cross post our Kaggle competition and give us space and a track for their IRL component on 11/6-11/7 in Bangkok

**Comment by ccerv1** [comment]
have a call booked with Beth tomorrow (Friday)

**Comment by ryscheng** [comment]
Current status.
Going to help with FTC hackathon around grant data with Daostar/metagov.

Gonna pursue the data challenge separately here
https://github.com/opensource-observer/oso/issues/1807
