### ISSUE TITLE
Enumerate `contract` artifacts from a `factory` address

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1374]
### What is it?

Currently we only enumerate contracts that are created by `deployer` address.
We do not detect whether they're a factory and whether that factory in turn creates new `contracts`.

These should all be artifacts in our data model

**Comment by ccerv1** [comment]
@ravenac95 update: this intersects with Agora's sign-up verification. Essentially, they'd like an API they can call:

Request:
- network
- address (contract or factory)

Response:
- deployer (EOA)

**Comment by ccerv1** [comment]
Update:

Would we be able to go two levels deep, eg:

- contracts_by_deployer_one_level
- contracts_by_factory_one_level
- contracts_by_deployer_two_levels (union of the above two tables)

Specific user story:

> i deploy a factory from my EOA and it deploys contract x, then i give contract x's address and you give me the EOA address

**Comment by ccerv1** [comment]
@ravenac95 I have moved our discussion about the contract verification that we were having with Jonas and Agora into its own issue now. Please add any comments or additional context that may be relevant to that issue. 

Separately, my understanding is that this feature _should_ be working now. We just want to test it, eg, by adding a deployer on Base that deployed a factory. If so, we can close this out once we get #1203 to work.
