### ISSUE TITLE
Dynamic pages for projects

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#138]
### Describe the feature you'd like to request

`/projects/slug_or_id`

See here for UI design
https://github.com/hypercerts-org/oso/issues/100

### Describe the solution you'd like

There's a Plasmic page already that needs to be wired up to real data

### Describe alternatives you've considered

N/A

**Comment by ryscheng** [comment]
Middleware proxying here
https://github.com/hypercerts-org/oso/pull/146

**Comment by ryscheng** [comment]
The routing is done, and the prototyping with dummy data is done. Now we need to go in and actually plumb up real data.

**Comment by ccerv1** [comment]
@ryscheng if you see this extending into next week, then I might suggest breaking it into one or more smaller issues

**Comment by ryscheng** [comment]
Update EventDataProvider to use graphQL here
https://github.com/opensource-observer/oso/pull/383

**Comment by ryscheng** [comment]
As of this PR, we are finally rendering something for each project and artifact page.
https://github.com/opensource-observer/oso/pull/395

Going to close this out and file smaller bugs from here
