### ISSUE TITLE
Use bigquery usage statistics to measure costs

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1383]
### What is it?

We can better measure our usage of bigquery by making queries like this:

```sql
SELECT *
FROM `region-us`.INFORMATION_SCHEMA.JOBS_BY_PROJECT 
--`region-us` gets results for all jobs in the US region
```

This query allows us to track usage data for each of our queries. The schema is defined [here](https://cloud.google.com/bigquery/docs/information-schema-jobs). We should be able to determine the total bytes processed as actually see the most costly queries here. Additionally, each of the jobs listed has the user that executed the job as well as a plethora of other potentially useful information to understand the operation of each query.

To determine costs, we would simply need to multiply "bytes processed" by bigquery's pricing model.

**Comment by ryscheng** [comment]
I also just created a Data Exchange on Analytics Hub here
https://console.cloud.google.com/bigquery/analytics-hub/exchanges?project=opensource-observer

This provides usage details for anyone that adds our dataset and uses it

**Comment by ryscheng** [comment]
@ravenac95 can we close this?
There's another issue with more details here
https://github.com/opensource-observer/oso/issues/990
