### ISSUE TITLE
Superchain traces quality assurance checks

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1385]
### What is it?

We should have some simple strategies to make sure that we're not missing data in our blocks/transactions/traces datasets.

FWIW, FYI
The Goldsky folks do some pretty compute heavy QA, including recomputing merkle trees and whatnot to make sure they don't miss anything. They said they have some lighter-weight scripts they could share regarding comparing block headers.

**Comment by ryscheng** [comment]
would you be doing this in bigquery/outside of the file layer? if so, the easiest one is to check distinct block number counts and min/max block numbers for blocks and any other dataset - the other thing you can do is look at - another thing to do is to check the transaction count in blocks and compare that to the number of transactions with that block hash

for traces, maybe compare distinct transaction hashes between traces and transactions

**Comment by ravenac95** [comment]
Technically closed with #1633. However, I'm opening up a new issue to explore issues with missing data in the optimism traces.
