### ISSUE TITLE
PostgREST client suitable for unit tests and caching

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#142]
### Describe the feature you'd like to request

We want to use client-side fetching for event data.
We should have something that satisfies the conditions below.

We should sanity check that we can't just use the default supabase client.
If not, maybe just do something simple with PostgREST directly.

### Describe the solution you'd like

The solution should:
- Make it easy to stub out functionality for unit tests
- Works well with caching libraries like [SWR](https://swr.vercel.app/)

### Describe alternatives you've considered

- Just use the supabase client

**Comment by ravenac95** [comment]
My hope is that supabase uses: https://github.com/supabase/postgrest-js.

**Comment by ryscheng** [comment]
Deprecating in favor of graphql
