### ISSUE TITLE
bug: OSSD PRs are failing against new schema

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1428]
### Which area(s) are affected? (leave empty if unsure)

Other

### To Reproduce

Try to validate one of the PRs currently in the queue, eg, [this one](https://github.com/opensource-observer/oss-directory/pull/281) or [this one](https://github.com/opensource-observer/oss-directory/pull/282)

### Describe the Bug

Error message is:

```
{
  version: 5,
  name: 'zuzapp',
  display_name: 'Zuzapp',
  github: [ { url: 'https://github.com/Zuzapp' } ],
  blockchain: [
    {
      address: '0x9f99e087f531bd8bf74e414813ab73744f0a43ad',
      networks: [Array],
      tags: [Array]
    }
  ]
}
{ slug: "must have required property 'slug'" }
{"level":"error","message":"\nError: Invalid project.json"}
```

### Expected Behavior

Valid PRs should be merged against the latest schema which replaces the field `slug` with `name`

**Comment by ryscheng** [comment]
Updating oss-directory here
https://github.com/opensource-observer/oso/pull/1453

**Comment by ryscheng** [comment]
Fixed here
https://github.com/opensource-observer/oso/pull/1461

**Comment by ryscheng** [comment]
@ccerv1 just rerun the vhevks
