### ISSUE TITLE
Grab languages for GitHub repos

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1434]
We should have an array of languages that a GitHub repo uses. This can be just an array or potentially an array of tuples that show the % of each language (like it appears in the web UI) Once this is in, I can create the models.

**Comment by ravenac95** [comment]
@ccerv1 as noted in the issue, we don't have all the languages related to a repo. The api call we were already making only returns the "primary" language that github detects. So if we want more languages than that we will need to call an additional API method.
