### ISSUE TITLE
Implement log/linear and address/user variants of impact metrics

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1468]
From [Feedback Doc](https://docs.google.com/document/d/1E6aXvjVQsEW2eXlX17jn2uui4b7UQtUoJaKxWdTgtgk/edit#heading=h.odr9cr84he39)

- [x] Gas Fees [Network Growth]
- [x] Gas Fees - Log Scale [Network Growth]
- [x] Transactions [Network Growth]
- [x] Transactions - Log Scale [Network Growth]
- [x] Trusted Transactions [Network Quality]
- [x] Trusted Transactions - Log Scale [Network Quality]
- [x] Daily Active Addresses [User Growth]
- [x] Trusted MAUs [User Growth]
- [x] Monthly Active Addresses [User Growth]
- [x] Trusted Recurring Users [User Quality] - to be updated
- [x] Trusted Recurring Addresses [User Quality]

**Comment by ryscheng** [comment]
@ccerv1  IMO I think we should just let the API consumer calculate client-side (ie the frontend). Much easier 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log

**Comment by ryscheng** [comment]
Do this in the CSV rather than API
