### ISSUE TITLE
Add more eligibility checks to the RF4 dbt model

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1486]
### What is it?

- does the project have more than one contributor
- has there been a recent commit in the last 30 days
- have there been more than 10 days of activity in the last 90 days

**Comment by ryscheng** [comment]
For now at least, we need to take a final version of [this model](https://github.com/opensource-observer/oso/blob/main/warehouse/dbt/models/marts/superchain/rf4_repo_stats_by_project.sql) and adding a field [in here](https://github.com/opensource-observer/oso/blob/main/warehouse/dbt/models/marts/superchain/rf4_project_verification.sql)

**Comment by ccerv1** [comment]
Latest thoughts from Jonas are [here](https://www.notion.so/Retro-Funding-4-Application-Review-Process-e8c1e1b03f7640a680185ed4301351aa#fc15ae76b5264f27b90b421f56666b7f)

Checks to consider:
1. Enforce Eligibility criteria
2. Check that Github repo has min number of commits (e.g. 100)
3. Check that Github repo has min number of stars (e.g. 20)
4. Check that Github repo is in relevant language (Solidity or Javascript)

**Comment by ccerv1** [comment]
Current repo checks:

```
repo_snapshot.commit_count >= 10
and repo_snapshot.days_with_commits_count >= 3
and repo_snapshot.first_commit_time < '2024-05-01'
and repo_snapshot.star_count >= 10
and repo_snapshot.language in ('Solidity', 'JavaScript', 'TypeScript')
and repo_snapshot.license_type != 'Unspecified'
```
