### ISSUE TITLE
Stop using gh actions for warehouse pipeline

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1497]
### Describe the feature you'd like to request

We should trigger a dbt materialization and cloudquery plugins from dagster. 

### Describe the solution you'd like

See above

### Describe alternatives you've considered

N/A

**Comment by ryscheng** [comment]
@ravenac95 is this done? Is there any remaining cleanup in GitHub actions?

**Comment by ravenac95** [comment]
Definitely done!
