### ISSUE TITLE
Expose oss-directory social data in projects_v1 API

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1499]
We are currently missing socials and website I think

**Comment by ryscheng** [comment]
One idea is expose all twitter handles as artifacts, which you can query via artifacts_by_project.
Something like
artifact_source=TWITTER
artifact_name=@handle
Should artifact_namespace be null?

which kinda sets us up for tracking twitter events in the future, like farcaster events, which we're already starting to work on

**Comment by mseidlx** [comment]
@ryscheng I like the idea of exposing socials via artifacts! In my mind it probably makes sense to expose all 1:n relationships via artifacts_by_project
