### ISSUE TITLE
oss-directory: create a tag for `ANY_EVM` in the network enums

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1512]
### What is it?

We should have a tag that instructs the indexer to look for deployments on any EVM chain on OSO. This is preferable to enumerating them individually. It's also preferable to assuming any deployer should show up on all chains as this might not always be the case and we don't want to hardcode into the schema.

**Comment by ryscheng** [comment]
This PR adds `any_evm` to the schema in oss-directory
https://github.com/opensource-observer/oss-directory/pull/298

Tossing it over to @ravenac95 to update the semantics in the dbt pipeline

**Comment by ryscheng** [comment]
This adds ANY_EVM semantics to the dbt pipeline
https://github.com/opensource-observer/oso/pull/1540
