### ISSUE TITLE
Migrate oss-directory to remove all blockchain artifacts with a `contract` or `factory` tag

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1513]
### What is it?

Now that we index all contracts from a deployer, these artifacts are unnecessary. The fact that we currently have this redundant info in project YAMLs could be confusing to projects that are submitting PRs.

**Comment by ryscheng** [comment]
@mdalie makes a really good point that we **cannot** do this. Some contracts are deployed by community members with an EOA that cannot be thought of as owned by the project. These deployers might be deploying contracts from multiple projects.

Marking this as *no longer planned*

Thank you @mdalie, you called at exactly the right time!
