### ISSUE TITLE
Use GitHub actions to perform indexing jobs

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#152]
We should be running indexing jobs continuously through our github actions to ensure liveness of data on the app.

**Comment by ravenac95** [comment]
I realized this task is a bit bigger than I had initially thought. I have a few things that just came from the sort of hack/slash approach to getting some of this done that I'm trying to clean up. Essentially, all the "event pointer" work needs a little bit of love. So, in retrospect, this issue should likely have been a 4 as I've already spent at least a 2's (or 3 if that existed) amount of time on it.

**Comment by ravenac95** [comment]
Additionally, #173 and #170 are fairly coupled with this.

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oso/pull/284
Done!
