### ISSUE TITLE
Cloudsql/Postgres needs indices

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1533]
### Describe the feature you'd like to request

Right now we copy mart models to cloudsql but we don't build indices. That means that queries are slow, we have users mentioning that the artifacts table and metrics tables are both timing out.

Fwiw, even in a Trino world, we will need this. Trino does not have a concept of an index and just forwards queries to the underlying database. We can still have Trino serve as the frontend to postgres

### Describe the solution you'd like

Let's add some metadata to the mart models that specify which columns to index. 

Then build the index *after* the copy completes. 

Not sure what to do when we move to incremental copies, maybe drop index, incremental copy, build index?

### Describe alternatives you've considered

Setting indices early would lead to some slow copies.

**Comment by ccerv1** [comment]
Yes, been noticing this as well. How big of an issue (cost-wise) do you expect this to be?

**Comment by ryscheng** [comment]
Let's see if this works
https://github.com/opensource-observer/oso/pull/1567

**Comment by ryscheng** [comment]
Going to close this out for now. The PR above seems to successfully run and create *some* indices.
However, a seemingly random set seem to be missing and there aren't any good error logs as to why.
Filing a subsequent issue to investigage
https://github.com/opensource-observer/oso/issues/1583
