### ISSUE TITLE
Project Pages should include artifacts in a nice way

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1562]
### Describe the feature you'd like to request

The goal is to incentivize projects to discover which artifacts (e.g. treasury addresses, contracts, repos), are associated so far and what might be missing.

Then we can provide a call to action to add more data in the right way.

### Describe the solution you'd like

- Enumerate all contracts that have been 'discovered' by the deployer
- Enumerate all treasury addresses that reflect funding
- etc

### Describe alternatives you've considered

TBD

**Comment by ravenac95** [comment]
Partially completed by #1933 #1934 #1935

**Comment by ravenac95** [comment]
@ryscheng should we just close this now? We have links but I'm not sure it's "nice". Additionally we're missing links to downstream addresses.
