### ISSUE TITLE
Bug: assign zeroex contracts to 0x in OSS Directory

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1574]
### Which area(s) are affected? (leave empty if unsure)

Other

### To Reproduce

See here: https://www.opensource.observer/project/zeroex.
Should be assigned here: https://www.opensource.observer/project/0xproject

### Describe the Bug

We mixed up the project that had deployed the contracts.

### Expected Behavior

All onchain events should be attributed to 0xproject, not zeroex

**Comment by ccerv1** [comment]
Addressed here: https://github.com/opensource-observer/oss-directory/pull/321
Will close out if there's no further discussion here: https://github.com/opensource-observer/oss-directory/pull/318#pullrequestreview-2093566134

**Comment by ryscheng** [comment]
Closed done!
