### ISSUE TITLE
Import collections defined in oss-directory

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#159]
### Describe the feature you'd like to request

Collections need to be mapped to projects from the oss-directory

### Describe the solution you'd like

We already have tables defined, just need to process the oss-directory data and load into the db.

### Describe alternatives you've considered

n/a

**Comment by ravenac95** [comment]
Unless I'm wrong @ryscheng you already wrote the code to do this. I had fixed up something during the typeorm migrations but these relationships are in the DB.

**Comment by ravenac95** [comment]
I believe this is done

**Comment by ryscheng** [comment]
oh right lol. thanks for the reminder
