### ISSUE TITLE
chore: remove project Safe-related events from event table histories

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1606]
### What is it?

We now have a model for identifying Safes and excluding those transactions from the event table going forward (see #1605). However, we need to remove Safe-related data from historical events. Since these are incremental models, we can either do a full refresh (expensive) or run delete them by running queries like the following:

```
select * from `oso.int_events`
where to_artifact_id in (select artifact_id from `oso.int_safes`)
```

**Comment by ryscheng** [comment]
#1605  closed by
