### ISSUE TITLE
Investigation: Some missing optimism traces data

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1634]
### What is it?

There's seemingly ~1% of data missing in optimism traces. We are currently investigating.

**Comment by ryscheng** [comment]
@ravenac95 check the latest on the TG group, they're starting to backfill some missing data

**Comment by ravenac95** [comment]
Need to do a final check on this, I believe this was run so I'll run a check

**Comment by ravenac95** [comment]
I think this should be closed in favor of #1873 and need to send comms to goldsky
