### ISSUE TITLE
Cloudquery ingest should not write to `oso` dataset

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1666]
### What is it?

Currently the cloudquery processes write to `oso` we should move these to a different dataset. This way we can ensure that `oso` is _only_ managed by dbt and therefore make it easier to clean `oso` by only keeping the models that exist inside dbt.

**Comment by ryscheng-mobile** [comment]
@ravenac95 Is this still relevant? Since we are moving to dlt?

**Comment by ravenac95** [comment]
@ryscheng definitely no longer needed
