### ISSUE TITLE
Resolve 'resources exceeded during query execution' error for updated `int_all_artifacts` model

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1676]
### What is it?

# Context

I have made two updates to `int_contracts_by_project`:

- Previously, we only looked for contracts that were deployed by a deployer verified in OSSD. However, some projects have contracts that they still own but did not deploy. **The updated version now includes contracts enumerated in OSSD that do not have a deployer in OSSD.**

- I included a second level of contracts called `discovered_contracts`, which is an **explicit a search for contracts that have been deployed by factories owned by the project**. Here's why this appears to be needed:
    - In the `stg_{}_factories` models, the `originating_address` is the EOA that triggered the `create` request
    - In the `int_derived_contracts` model, the `originating_address` is transformed into the `deployer_address`, however, the `factory_address` is not brought through anywhere
    - Therefore, when we query `int_derived_contracts` in `int_contracts_by_project`, we only get first level deployments -- not the second level of a contract deployed by a factory. 
 - Here is an [example of Gitcoin](https://docs.google.com/spreadsheets/d/11Sr1rZoCnW0nFhxBR-Blvc_HMdrhI3wYiyiOfFPKoQs/edit?usp=sharing) showing the first implementation (165 results) and the second implementation (2280 results). The second implementation appears to be correct. 
    - For example, here is [a valid contract](https://optimistic.etherscan.io/address/0x51937713c67721e8a29da6c492d30a413e75c7e1#code) that was detected only by the second approach. 
    - It was deployed by [this factory](https://optimistic.etherscan.io/address/0xd5fb00093ebd30011d932cb69bb6313c550ab05f#internaltx), which was deployed by [this EOA](https://optimistic.etherscan.io/address/0xb8cef765721a6da910f14be93e7684e9a3714123) included in OSSD.

# Situation

Where we run this, we can get a BigQuery [resourcing error](https://github.com/opensource-observer/oso/pull/1675), eg:

```
Database Error in model int_base_contract_invocation_events`
``` 

These models are all powered by `contract_invocation_events_with_l1.sql`

# Next steps

We could look upstream for some storage optimization or we could try to refactor `contract_invocation_events_with_l1.sql`

@ravenac95 curious for your advice!

**Comment by ravenac95** [comment]
I _think_ the solution here is probably just materialize more things as tables. My bad for trying to remove that yesterday. It's a safe solution and we shouldn't be too worried about it but if it can be avoided it's much better. Just avoid using `incremental` unless we know it's important for that dataset.
