### ISSUE TITLE
Data linting tool

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#168]
### Describe the feature you'd like to request

It'd be nice to be able to scan the database and get a clear picture of what data is missing.

### Describe the solution you'd like

Some examples:
- Collections => Projects (missing projects)
- Projects => Artifacts (missing artifacts)
- Artifacts => Events (missing event types)
- Events - missing ranges

### Describe alternatives you've considered

N/A

**Comment by ryscheng** [comment]
Should be good enough to just use a SQL query for now.

@ravenac95 can you upload the SQL query you use to here
https://github.com/opensource-observer/oso/tree/main/indexer/database


And then link it in this issue (and then close?)

**Comment by ryscheng-mobile** [comment]
Let's re-scope this to actually make it more visible in the project page, for each artifact / event pointer what's missing?

**Comment by ravenac95** [comment]
I think what may be more useful here is to deploy a better workflow runner that reports errors. Then, using our airbyte/cloudquery collectors we would know when/what to rerun for any missing data. For any cases where we're _actually_ missing data that cannot be retrieved (like gh-archive going down for some time) we may want to just be transparent about it source time ranges and missing data.

**Comment by ravenac95** [comment]
This is already achieved by our dagster pipelines and should be considered on a per data type basis from now on. Most recently we have enabled this with our setup with #1633
