### ISSUE TITLE
npm downloads

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#171]
### What is it?

Are we pulling data from here?
If not, we should update the code to use @ravenac95 's idempotency and caching patterns

**Comment by ccerv1** [comment]
@ryscheng I'm moving this to P2. Currently, we don't have any npm event data. 

Once we have the data, we should decide if / how we want to surface this metric on the project page UI. It's not as important as the dependencies and could be confusing if a project has a lot of downloads but not a lot of dependencies in the ecosystem (or vice versa).

**Comment by ryscheng** [comment]
Duplicate of
https://github.com/opensource-observer/oso/issues/268
