### ISSUE TITLE
Dates should be stored in `pointer`, not `updatedAt`

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#173]
### To Reproduce

From running the Dune data fetchers

### Describe the Bug

Right now we're storing pointer data in `updatedAt`

### Expected Behavior

Instead, it should be in the `pointer`.

**Comment by ccerv1** [comment]
See also #170

**Comment by ryscheng** [comment]
Fixed with pointer ranges
https://github.com/opensource-observer/oso/pull/223/files
