### ISSUE TITLE
Ensure that linting on the pre-commit hook is consistent with PR linting

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#177]
### To Reproduce

pre-commit linting does not fail on `warning` level linting issues. So, do something that causes a warning.

### Describe the Bug

See above

### Expected Behavior

The pre-commit linting should _not_ allow warnings to pass.

**Comment by ryscheng** [comment]
I think it should be addressed here
https://github.com/opensource-observer/oso/pull/326
