### ISSUE TITLE
`artifacts_by_user_v1` dbt mart model

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1771]
### What is it?

This should be modeled similarly to `artifacts_by_project_v1` with the following columns:

- artifact_id
- artifact_source_id
- artifact_source
- artifact_namespace
- artifact_name
- user_id
- user_source_id
- user_source
- user_namespace
- user_name

This should map any artifacts owned by users (e.g. GitHub users, EOA addresses, etc)

**Comment by ccerv1** [comment]
@ryscheng working on this currently. I assume this is where we should support arbitrary groups of users, for instance "superchain trusted users", "superchain bots", "superchain power users", etc.

In this case of a bot, one implementation could be:

```
- user_source_id: 0x123...789
- user_source: BASE
- user_namespace: base_superchain_bots
- user_name: 0x123...789
```

and for a trusted farcaster user, it could be:

```
- user_source_id: 539
- user_source: FARCASTER
- user_namespace: farcaster_trusted_user
- user_name: ccerv1
 ```

@wdyt?

**Comment by ccerv1** [comment]
As discussed, we will create a new abstraction level called `usergroup`

Thus, we need the following directories for users:
- artifacts_by_user
- users_by_usergroup
- artifacts_by_usergroup
