### ISSUE TITLE
OP Labs Data wishlist

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1777]
### What is it?

@MSilb7 currently uses a mix of Dune, Defillama, L2beat, growthepie to get all the data he needs to ggenerate reports.

Could you comment on this issue:
- A list of data sources that you use
- Which metrics you want are provided by each

**Comment by ccerv1** [comment]
Notes from telegram convo:
 - Superchain: App / contract growth [Hex dashboard](https://app.hex.tech/61bffa12-d60b-484c-80b9-14265e268538/app/cd3f1525-08f0-4a49-a15a-b72f46f2a0d8/latest)
- Things he uses regularly:
  - L2Beat
  - Goldsky/Dune/etc (txns, traces, logs, etc)
  - Growthepie (if not on L2beat)
  - Defillama (TVL)
- "all i want is for all of the data to be connected"

**Comment by ryscheng** [comment]
This is a good initial list, thanks for sharing.

Tracking the l2Beat and Defillama work here
https://github.com/opensource-observer/oso/issues/619
