### ISSUE TITLE
Code Metrics Star/Fork counts are reporting incorrectly for some

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1781]
### To Reproduce

This was from a user in the discord (thanks daehyun from discord!)

This query:
```
SELECT *
FROM `oso_production.code_metrics_by_project_v1`
WHERE project_name = 'sonobe-privacy-scaling-explorations'
```

Returns the following data
* `star_count`: 644 
* `fork_count`: 152

But the numbers that we have in both the raw data from github (the cloudquery github resolver) and also the data on the UI in github shows that those star / fork counts are 162 and 38 respectively.

### Describe the Bug

See above

### Expected Behavior

The numbers should match the github data and add up correctly based on all the repos in a project.

**Comment by ravenac95** [comment]
This doesn't seem to be happening on all things. If you search for `opensource-observer`'s project (`Erx9J64anc8oSeN-wDKm0sojJf8ONrFVYbQ7GFnqSyc=`) it's just fine.

**Comment by baumstern** [comment]
[zk-eigentrust](https://github.com/privacy-scaling-explorations/zk-eigentrust) has 110 stars and 10 forks but the query to the `oso_production` in BigQuery returns 220 stars and 20 forks count. It's `project_name` is `zk-eigentrust-privacy-scaling-explorations`
