### ISSUE TITLE
Create a data import progress dashboard

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#179]
### Describe the feature you'd like to request

Github actions seem to be pretty bad at reporting their status on many of our data import tasks. I think we can create a simple UI and report the status of current jobs. This would allow for better debugging. 

### Describe the solution you'd like

Uncertain where we might store the logs (if we should) of a specific data import run. It might be best to allow for logging optionally that writes log lines into postgres (in batches) only if something like a `--debug` flag is set on the run. In all other cases, other metrics should be reported to something. Ideally, something like pushing import metrics to something that allows for viewing on a grafana like dashboard.

### Describe alternatives you've considered

Github actions logs themselves. They don't reliably report live logs.

**Comment by ryscheng** [comment]
Should be good enough to just use a SQL query for now.

@ravenac95 can you upload the SQL query you use to here
https://github.com/opensource-observer/oso/tree/main/indexer/database

And then link it in this issue (and then close?)
