### ISSUE TITLE
Blog: OSO Data Portal

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#1811]

**Comment by ryscheng-mobile** [comment]
https://docs.google.com/document/d/1zIbCMudBZfMA8IuK154T96IQjhtsGkPThMqRxG4ZBBw/edit
Draft here

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oso/pull/1820

**Comment by ryscheng** [comment]
Feedback from partners
https://github.com/opensource-observer/oso/pull/1828
