### ISSUE TITLE
Blog index should be more curated

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#1824]
### What is it?

Maybe we use a `popular` tag or something to distinguish what we want on the front page?

**Comment by ccerv1** [comment]
Bump. As we start doing more outbound, and our blog remains the best place to learn about our use cases, we should probably implement this sooner rather than later. Assuming it's a straightforward 1 pointer to add the tag and then I can curate the `popular` list.

**Comment by ccerv1** [comment]
(maybe it should be `featured` instead of `popular`)

**Comment by ryscheng** [comment]
Ah whoops, pushed to main by accident
https://github.com/opensource-observer/oso/commit/ab2cf6c094f77bb97f1775cc8c0642f70d57ef7a

This adds a custom tag list page so we can modify this list behavior

**Comment by ryscheng** [comment]
Chose some to be featured here
https://github.com/opensource-observer/oso/pull/2049

**Comment by ryscheng** [comment]
Added more space here
https://github.com/opensource-observer/oso/pull/2059
