### ISSUE TITLE
Collaborate with Token Engineering (Valueverse) on token value capture mechanisms proposal

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1877]
### What is it?

TE Value Capture Fundamentals | [Slides](https://docs.google.com/presentation/d/1_Bifl0y0fj7WUEc6SX0osotnW37aJk0U8tbH1FUF3k0/edit#slide=id.g2dc144aeb41_0_22)
GG21 Proposal | [Doc](https://docs.google.com/document/d/1a4KXmsiS7dViSsM6EZOy8PbuamWt827Yazny5HbY7b8/edit)
Protocol Longlist | [Sheet](https://docs.google.com/spreadsheets/d/1ovfFsTTeU1Cwa_fvKjLXBG4eLUcoD-RWtlp5fWrVsfU/edit?usp=sharing)

**Comment by ccerv1** [comment]
Longlist created via this query:

```sql
select
  project_name,
  array_agg(event_source) as chains,
  sum(transaction_count_6_months) as sum_transaction_count_6_months,
  sum(active_contract_count_90_days) as sum_active_contract_count,
  max(address_count_90_days) as max_address_count_90_days
from `opensource-observer.oso.onchain_metrics_by_project_v1`
group by 1
order by 3 desc
```

**Comment by ccerv1** [comment]
Shortlist:

- layer-zero
- layer3xyz
- worldcoin
- stargate-finance
- 0xproject
- velodrome
- op
- holograph
- axelar
- synapse
- synthetix
- kwenta
- thales
- fraxfinance
- hai-on-op

**Comment by ryscheng** [comment]
@ccerv1 Should we close this? Can you link to what happened here?
