### ISSUE TITLE
Segment users by interaction frequency and recent activity [JS]

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#189]
Sample query [here](https://dune.com/queries/451986/859139)

![Image](https://github.com/hypercerts-org/oso/assets/42869436/96d26b0b-61f4-4961-82c4-34a2ec682b9c)

Would need to add case for "high value user" (someone who's interacted more than 10 times over the past 30 days)

Also need some way of calculating the % of all-time users this represents

**Comment by ccerv1** [comment]
| project_name | unique_devs | active_devs | high_value_devs | unique_users | active_users | high_value_users | shared_devs | shared_users |
| ------------ | ----------- | ----------- | --------------- | ------------ | ------------ | ---------------- | ----------- | ------------ |
| 0xSplits     | 259         | 21          | 3               | 39           | 39           | 6                | 169         | 36           |
| Safe         | 3985        | 258         | 31              | 27085        | 27085        | 2952             | 3984        | 19051        |
| Uniswap      | 31492       | 747         | 31              | 61812        | 61812        | 4882             | 1765        | 45968        |

**Comment by ccerv1** [comment]
@ryscheng bumping this one, as it's blocking the remaining components in the Project Page

### Definitions

#### Onchain

- a **user** is a unique address that has interacted with a project's contract over a date range
- a **new user** is a user that had their first interaction in the past 90 days
- a **churned user** is a user that has not had an interaction in the past 90 days
- a **active user** is a user that has had an interaction in a given month
- a **high frequency user** is a active user that has more than 1000 interactions in that month
- a **high value user** is an active user that has had 10-999 interactions in that month
- a **low value user** is an active user that has had 1-9 interactions in that month

#### GitHub

- a **contributor** is a unique account that has committed code, opened or closed issues, opened or merged PRs over a date range
- a **developer** is a contributor that has committed code
- a **new contributor** is a contributor that had their first contribution in the past 90 days
- a **churned contributor** is a contributor that has not had made a contribution in the past 90 days
- a **active contributor** is a contributor that has made a contribution in a given month
- a **full-time developer** is an active developer that has contributed on 10+ days in that month
- a **part-time developer** is an active developer that has contributed on <10 days in that month
- a **other contributor** is any other contributor not included in the full-time and part-time developer sets in that month

**Comment by ccerv1** [comment]
@ryscheng update:

I have the user cards working now, we just need to get the Area Charts. I don't think we have the data to this currently ...

Summary of what we need:

#### Onchain

A stacked area chart of different types of onchain users. The total of the stack is the monthly active users. There are three types of active users.

- [ ] a **high frequency** user is a active user that has more than 1000 interactions in that month
- [ ] a **high value** user is an active user that has had 10-999 interactions in that month
- [ ] a **low value** user is an active user that has had 1-9 interactions in that month 

![Image](https://github.com/opensource-observer/oso/assets/42869436/79a50507-ce50-4af1-9e03-45910799203a)

#### GitHub

A stacked area chart of different types of contributors. The total of the stack is the monthly active contributors. There are three types of active contributors.

- [ ] a **full-time developer** is an active developer that has contributed on 10+ days in that month
- [ ] a **part-time developer** is an active developer that has contributed on <10 days in that month
- [ ] a **other contributor** is any other contributor not included in the full-time and part-time developer sets in that month



![Image](https://github.com/opensource-observer/oso/assets/42869436/c4175c8d-dc84-4e37-9ba5-b77302879178)

**Comment by ryscheng** [comment]
Just documenting some stuff I tried

1. Creating a view of artifacts that define your status as a high/low value user. Then filter out events where the 'fromId' can be joined against this view. This doesn't work because we want a sliding window -- you can be high value one month and low value another
2. For each event type, create separate "amount" columns for high vs low value. This doesn't work well because the definitions depend on the artifactType and/or eventType
3. Create a materialized view for every user definition. This explodes the space of materialized views, because we need one for every {day,week,month} and for {artifacts,projects}. So 6 views for every user definition. This also gets really messy wiring it up to the frontend, which has to switch which view we are querying.
4.  Create new event types (e.g. COMMIT_CODE_FULL_TIME vs COMMIT_CODE_PART_TIME). The events_daily_by_artifact materialized view definitions will need to add new rows for each user definition, in addition to all the rows it already has.

We are going to go with option 4 for now, out of expediency.
Pros: This works without any code changes outside of the new definition/migration.
Cons: If we ever change a user definition, we have to rebuild all of our aggregates, which will be costly and painful.

What was nice about option 3 was that we could more easily add/remove new user definitions incrementally without tearing out our existing aggregates. But not worth the mess.

Worth some additional thought on how to get the best of both worlds in the future

**Comment by ccerv1** [comment]
OK, so this query appears to work for GitHub artifacts:

```
SELECT 
    e."toId" AS artifact_id,
    e."fromId" AS contributor_id,
    TO_CHAR(e."time", 'YYYY-MM') AS month_year,
    CASE 
        WHEN COUNT(DISTINCT CASE WHEN e."typeId" = 4 THEN e."time" END) >= 10 THEN 'FULL_TIME_DEV'
        WHEN COUNT(DISTINCT CASE WHEN e."typeId" = 4 THEN e."time" END) >= 1 THEN 'PART_TIME_DEV'
        ELSE 'OTHER_CONTRIBUTOR'
    END AS status,
    1 AS amount
FROM 
    event e
WHERE
    e."typeId" IN (
        2, -- PULL_REQUEST_CREATED
        3, -- PULL_REQUEST_MERGED
        4, -- COMMIT_CODE
        6, -- ISSUE_CLOSED
        18 -- ISSUE_CREATED
    )
    -- AND e."toId" = 420126 -- uncomment for testing purposes
GROUP BY
    e."toId",
    e."fromId",
    TO_CHAR(e."time", 'YYYY-MM');
```

**Comment by ccerv1** [comment]
And this works for contract addresses and active onchain users:

```
SELECT 
    e."toId" AS artifact_id,
    e."fromId" AS contributor_id,
    TO_CHAR(e."time", 'YYYY-MM') AS month_year,
    CASE 
        WHEN SUM(e."amount") >= 1000 THEN 'HIGH_FREQUENCY_USER'
        WHEN SUM(e."amount") >= 10 THEN 'HIGH_VALUE_USER'
        ELSE 'LOW_VALUE_USER'
    END AS status,
    1 AS amount
FROM 
    event e
WHERE
    e."typeId" = 25 -- CONTRACT_INVOCATION_DAILY_COUNT
    -- AND e."toId" = 2989 -- uncomment for testing purposes
GROUP BY
    e."toId",
    e."fromId",
    TO_CHAR(e."time", 'YYYY-MM');

```

**Comment by ryscheng** [comment]
Couple things

- amount is variable, shouldn't be hard coded as 1.
- I'm not sure the status definitions are correct? Worth checking but it looks like counting distinct commit events? As opposed to marking if the fromId represents a user that made a certain number of commits in a windowed month?
- we need to use timescale aggregates to bucket by date (see Ron-entities)
- and this just marks a status, we need to create new rows in the aggregate that are different event types depending on the status

**Comment by ccerv1** [comment]
Here's a sample result (for OSO repo):

[['artifact_id', 'contributor_id', 'month_year', 'status', 'amount'],
 (420126, 38521, '2023-10', 'FULL_TIME_DEV', 1),
 (420126, 38523, '2023-10', 'FULL_TIME_DEV', 1),
 (420126, 127856, '2023-10', 'FULL_TIME_DEV', 1),
 (420126, 35760, '2023-09', 'PART_TIME_DEV', 1),
 (420126, 38521, '2023-09', 'FULL_TIME_DEV', 1),
 (420126, 38523, '2023-09', 'FULL_TIME_DEV', 1),
 (420126, 127856, '2023-09', 'FULL_TIME_DEV', 1),
 (420126, 38521, '2023-08', 'FULL_TIME_DEV', 1),
 (420126, 38523, '2023-08', 'PART_TIME_DEV', 1),
 (420126, 127856, '2023-08', 'PART_TIME_DEV', 1),
 (420126, 38521, '2023-07', 'PART_TIME_DEV', 1),
 (420126, 38523, '2023-07', 'PART_TIME_DEV', 1),
 (420126, 38521, '2023-06', 'OTHER_CONTRIBUTOR', 1),
 (420126, 38523, '2023-06', 'OTHER_CONTRIBUTOR', 1),
 (420126, 38891, '2023-06', 'OTHER_CONTRIBUTOR', 1),
 (420126, 38521, '2023-05', 'OTHER_CONTRIBUTOR', 1),
 (420126, 38523, '2023-05', 'OTHER_CONTRIBUTOR', 1),
 (420126, 38521, '2023-04', 'OTHER_CONTRIBUTOR', 1),
 (420126, 38523, '2023-04', 'OTHER_CONTRIBUTOR', 1),
 (420126, 38521, '2023-03', 'OTHER_CONTRIBUTOR', 1)]

**Comment by ccerv1** [comment]
> amount is variable, shouldn't be hard coded as 1.

This means that `contributorId` is a {event_type} to that `artifactId` in that `month_year`

> I'm not sure the status definitions are correct? Worth checking but it looks like counting distinct commit events? As opposed to marking if the fromId represents a user that made a certain number of commits in a windowed month?

The Electric Capital definition of a full-time dev is anyone who commits more than 10 days in a month. (The same would be true if we indexed on `projectId`)

> we need to use timescale aggregates to bucket by date (see Ron-entities)

The raw events are already aggregated by day; technically we only need these metrics for monthly buckets

> and this just marks a status, we need to create new rows in the aggregate that are different event types depending on the status

hmm ...  `status` is the same as`event_type`. the correct thing would be to create an `eventId` for FULL_TIME_DEV, etc. if you mean something else, then I'm confused

**Comment by ryscheng** [comment]
Okay, at the sprint meeting we realized there was a big misunderstanding.

My understanding = we wanted to be able to easily segment all events by the type of fromId. Ie. easily aggregate an event type by the user doing the actions. Like count all commits performed by full-time vs part-time devs. This led me down a rather convoluted design to try to make this work for *any* event type and *any* new user definition.

Turns out we want something simpler, which is just a monthly count of the different types of users interacting with the project.
I think we still might need to create new materialized views for this, but still easier than what I was trying to do.

**Comment by ccerv1** [comment]
@ryscheng 

Part 1:

```
WITH Devs AS (

    SELECT 
        p."id" AS "projectId",
        e."fromId" AS "fromId",
        TO_CHAR(DATE_TRUNC('MONTH', e."time"), 'YYYY-MM-01') AS "bucketMonthly",
        CASE 
            WHEN COUNT(DISTINCT CASE WHEN e."typeId" = 4 THEN e."time" END) >= 10 THEN 'FULL_TIME_DEV'
            WHEN COUNT(DISTINCT CASE WHEN e."typeId" = 4 THEN e."time" END) >= 1 THEN 'PART_TIME_DEV'
            ELSE 'OTHER_CONTRIBUTOR'
        END AS "devType",
        1 AS amount
    FROM 
        event e
    JOIN 
        project_artifacts_artifact paa ON e."toId" = paa."artifactId"
    JOIN 
        project p ON paa."projectId" = p.id
        
    WHERE
        e."typeId" IN (
            2, -- PULL_REQUEST_CREATED
            3, -- PULL_REQUEST_MERGED
            4, -- COMMIT_CODE
            6, -- ISSUE_CLOSED
            18 -- ISSUE_CREATED
        )
        AND e."toId" = 420126 -- uncomment for testing purposes
    GROUP BY
        p."id",
        e."fromId",
        TO_CHAR(DATE_TRUNC('MONTH', e."time"), 'YYYY-MM-01')
)
SELECT
    Devs."projectId",
    Devs."devType",
    Devs."bucketMonthly",
    SUM(Devs."amount") AS "amount"
FROM 
    Devs
GROUP BY
    Devs."projectId",
    Devs."devType",
    Devs."bucketMonthly";

```

**Comment by ryscheng** [comment]
Couple minor changes 
- using `time_bucket` instead of string operations on the date.
- joining on the `event_type` table so we can use names instead of typeId


```
WITH Devs AS (
      SELECT 
        p."id" AS "projectId",
        e."fromId" AS "fromId",
        time_bucket(INTERVAL '1 month', e."time") AS "bucketMonthly",
        CASE 
          WHEN COUNT(DISTINCT CASE WHEN t."name" = 'COMMIT_CODE' THEN e."time" END) >= 10 THEN 'FULL_TIME_DEV'
          WHEN COUNT(DISTINCT CASE WHEN t."name" = 'COMMIT_CODE' THEN e."time" END) >= 1 THEN 'PART_TIME_DEV'
          ELSE 'OTHER_CONTRIBUTOR'
        END AS "segmentType",
        1 AS amount
      FROM event e
      JOIN project_artifacts_artifact paa ON e."toId" = paa."artifactId"
      JOIN project p ON paa."projectId" = p.id        
      JOIN event_type t ON e."typeId" = t.id
      WHERE
        t."name" IN (
          'PULL_REQUEST_CREATED',
          'PULL_REQUEST_MERGED',
          'COMMIT_CODE',
          'ISSUE_CLOSED',
          'ISSUE_CREATED'
        )
      GROUP BY
        p."id",
        e."fromId",
        "bucketMonthly"
    ),
    Users AS (
      SELECT 
          p."id" AS "projectId",
          e."fromId" AS "fromId",
          time_bucket(INTERVAL '1 month', e."time") AS "bucketMonthly",
          CASE 
              WHEN SUM(e."amount") >= 1000 THEN 'HIGH_FREQUENCY_USER'
              WHEN SUM(e."amount") >= 10 THEN 'HIGH_VALUE_USER'
              ELSE 'LOW_VALUE_USER'
          END AS "segmentType",
          1 AS amount
      FROM event e
      JOIN project_artifacts_artifact paa ON e."toId" = paa."artifactId"
      JOIN project p ON paa."projectId" = p.id
      JOIN event_type t ON e."typeId" = t.id
      WHERE t."name" = 'CONTRACT_INVOCATION_DAILY_COUNT'
      GROUP BY
        p."id",
        e."fromId",
        "bucketMonthly"
    )
    SELECT
      "projectId",
      "segmentType",
      "bucketMonthly",
      SUM("amount") AS "amount"
    FROM 
      (
          SELECT * FROM Devs
          UNION ALL
          SELECT * FROM Users
      ) combined_data
    GROUP BY
      "projectId",
      "segmentType",
      "bucketMonthly";
```

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oso/pull/530/files

**Comment by ryscheng** [comment]
Add DataProvider here
https://github.com/opensource-observer/oso/pull/534

**Comment by ccerv1** [comment]
Wired it up! Shipped 🚀 🚀
