### ISSUE TITLE
Get a project's total current collaborators

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#190]
![Image](https://github.com/hypercerts-org/oso/assets/42869436/74be0b73-751c-4d7b-a450-c6f8b767e92e)

See Github's definition of a collaborator

# Collaborators
A user that has defined permissions in a github repo is marked as a collaborator. These permissions can vary and do not need to be the commit bit. A random org I am a member of shows the following options presently:

read
write
admin
issue triage
non-admin manager

**Comment by ccerv1** [comment]
FYI, I'm P2'ing this. It's useful but not on the critical path.

**Comment by ryscheng** [comment]
Added a `FirstContribution` materialized view here
https://github.com/opensource-observer/oso/pull/459
