### ISSUE TITLE
Try Subsquid for on-chain indexing

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#191]
### Describe the feature you'd like to request

https://docs.subsquid.io/migrate/subsquid-vs-thegraph/

Looks very similar to the Graph, but potentially faster for Optimism, and allows us to use Typescript and our existing ORM

### Describe the solution you'd like

https://docs.subsquid.io/quickstart/quickstart-ethereum/

### Describe alternatives you've considered

- The Graph

**Comment by ravenac95** [comment]
Closing this for now as we're moving towards using other resources
