### ISSUE TITLE
Bug: Clickhouse starting from idle seems to be causing timeouts and errors on the frontend

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1910]
### What is it?

I'm not sure if this is due to a change that I had with using `force-dynamic` on some pages but I definitely see that some of the requests to clickhouse timeout on the frontend server.

**Comment by ryscheng** [comment]
This is because Clickhouse is idle and needs 30 seconds to wake up. But Next.js will time out before it can respond to the user.
https://github.com/opensource-observer/oso/pull/2017

In this PR, I just redirect users to a simple notice that they should retry their request.
