### ISSUE TITLE
metrics: expose `total_developers` code metric in the website

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1916]
### What is it?

Actions:
- Show the all-time count of any Github user who has made a commit to the main branch of a project repo
- Add better copy to the website to indicate that `contributors` includes activities like opening issues, PRs, etc and not just code contributions
See also https://github.com/opensource-observer/oss-directory/issues/447

**Comment by ryscheng** [comment]
@ccerv1 curious if you could elaborate what else needs to be done here.
We have code metrics on the project page, as well as time series developer charts on the ProjectPage already
