### ISSUE TITLE
Migration: Unify contributors and artifacts into a single table

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#194]
### Describe the feature you'd like to request

Right now the `Contributor` table is effectively a stripped down artifact table. In reality, it would make sense if artifacts are able to make "contributions" to or "act" on other artifacts. These tables should simply be merged and the `Event` table should instead include something akin to a `to/from` or `target/source` for events. 

### Describe the solution you'd like

Described above

### Describe alternatives you've considered

na

**Comment by ryscheng** [comment]
We did this in our move to TypeORM
https://github.com/opensource-observer/oso/pull/256
