### ISSUE TITLE
Rewire all charts to Project/Artifact pages

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#1950]
### What is it?

As part of the latest refactor to our backend we had to remove the charts that were in the project and artifact pages. 

This is a follow on for #1628 and #1562

**Comment by ryscheng** [comment]
MetricsDataProvider registration here

https://github.com/opensource-observer/oso/pull/2026

**Comment by ryscheng** [comment]
CubeDataProvider here
https://github.com/opensource-observer/oso/pull/2027

**Comment by ryscheng** [comment]
Fixing a bug with MetricsDataProvider here
https://github.com/opensource-observer/oso/pull/2028

**Comment by ryscheng** [comment]
I'm going to close this for now and file subsequent issues on the remaining things. We have a basic chart working now, with both hasura and cube backed data components.

Now it's a question of what metrics do we want to expose and what UX refinements do we want to add?
