### ISSUE TITLE
dagster: create asset for indexing EAS data

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1954]
### Describe the feature you'd like to request

We'll probably just want to start by dumping raw attestation data into a data lake

### Describe the solution you'd like

A crawler similar to the open_collective.py example that fetches attestations from the EAS graphql endpoint and dumps that standard data plus a JSON with the decoded schema data into BigQuery.

Here's an example: https://gist.github.com/ccerv1/12a83e4a698a200a48ac17b97b049241

### Describe alternatives you've considered

Ask the EAS team if we can get a mirror of their database

**Comment by ryscheng** [comment]
Recoping this issue:
I think we prefer to do it this way
https://github.com/opensource-observer/oso/issues/2069

So once we have a generic trace decoder, we can use that to decode EAS traces.

**Comment by ccerv1** [comment]
https://github.com/opensource-observer/oso/pull/2110

@Jabolol could you take a look at the PR above? TY!

**Comment by Jabolol** [comment]
@ccerv1 Done! I made several adjustments to the PR, but the core contribution was definitely useful. I’ve tested it both locally and on BigQuery, and everything is working well.

<img width="1520" alt="image" src="https://github.com/user-attachments/assets/60629843-d97c-4e5a-974c-8183119bab31">

On the flip side, I found yet another concurrency bug with Dagster. Apparently, each `define_asset_job` call [can only have one partitioned run](https://github.com/dagster-io/dagster/issues/12580#issuecomment-1448487461), so Open Collective and the new EAS assets clash. I'll create an issue to track and fix it.

Let me know if you need anything else!
