### ISSUE TITLE
Normalize/clean all funding datasets to feed into the event table as `FUNDING` events

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1971]
### What is it?

We have a bunch of disparate funding datasets that need to be normalized into the event table

**Comment by ryscheng** [comment]
FWIW, Carl has already plumbed up some of the funding data into a metric that's shown on the website.

Worth tracing this end to end and making sure that we're joining the data properly into the same metric

**Comment by ccerv1** [comment]
Related to #2229

**Comment by ryscheng** [comment]
Yep, if all data from oss-funding is pre-normalized and validated, that'll make this a lot easier.
