### ISSUE TITLE
AlgoliaSearchList should have some better default results

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1987]
### What is it?

Before users enter a query we get a seemingly random set of projects back

this should be a list of top queries or something

**Comment by ccerv1** [comment]
FYI, tried to fix this in Algolia but couldn't find the right credentials .... what email is used to login? Wasn't in 1P

**Comment by ryscheng** [comment]
@ccerv1 your email was already added with access some time ago.

**Comment by ryscheng** [comment]
Trying a hacky fix here
https://github.com/opensource-observer/oso/pull/2414

**Comment by ryscheng** [comment]
Starting in Plasmic v74
