### ISSUE TITLE
sqlmesh: implement all existing metrics

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2004]
Code metrics:
- [x]   repository_count,
- [x]   first_commit_date,
- [x]   last_commit_date,
- [x]   star_count,
- [x]   fork_count,
- [x]   contributor_count,
- [x]   contributor_count_6_months,
- [x]   new_contributor_count_6_months,
- [x]   fulltime_developer_average_6_months,
- [x]   active_developer_count_6_months,
- [x]   commit_count_6_months,
- [x]   opened_pull_request_count_6_months,
- [x]   merged_pull_request_count_6_months,
- [x]   opened_issue_count_6_months,
- [x]   closed_issue_count_6_months

Onchain metrics:
- [ ]   days_since_first_transaction,
- [x]   active_contract_count_90_days,
- [x]   transaction_count,
- [x]   transaction_count_6_months,
- [x]   gas_fees_sum,
- [x]   gas_fees_sum_6_months,
- [x]   address_count,
- [x]   address_count_90_days,
- [x]   new_address_count_90_days,
- [x]   returning_address_count_90_days,
- [ ]   high_activity_address_count_90_days,
- [ ]   medium_activity_address_count_90_days,
- [ ]   low_activity_address_count_90_days,
- [ ]   multi_project_address_count_90_days

Superchain:
- [ ] power_user_addresses
- [ ] recuring_addresses
- [ ] trusted_transaction_count
- [ ] trusted_daily_active_users
- [ ] trusted_monthly_active_users
- [ ] trusted_recurring_users
- [ ] trusted_users_onboarded
- [ ] openrank_trusted_users
- [x] transactions
- [x] monthly_active_addresses
- [x] daily_active_addresses
- [x] gas_fees

**Comment by ryscheng** [comment]
Added a README on how to get started here
https://github.com/opensource-observer/oso/pull/2093

**Comment by ccerv1** [comment]
Going to do a first pass with this PR

**Comment by ccerv1** [comment]
https://github.com/opensource-observer/oso/pull/2517
