### ISSUE TITLE
bug: current local `duckdb` setup makes partitions error (lock already held)

### ISSUE THREAD

**Issue by Jabolol** [opensource-observer/oso#2040]
### To Reproduce

> [!NOTE]
> You need to be using duckdb for local development, see #1946 

In [`Dagster`](http://dagster.opensource.observer/), launch a backfill run that will materialise several runs, for instance, [this one](https://dagster.opensource.observer/assets/open_collective/expenses), and select more than one. Only the first one will go through, and all will fail even if the data is successfully collected.

### Describe the Bug

Since we are launching concurrent jobs, the first materialisation acquires the lock of the duckdb database, preventing all the subsequent materialisations to fail, since they cannot connect to the database.

### Expected Behavior

Materialisations should be able to run concurrently and do not have lock issues.

**Comment by ravenac95** [comment]
As discussed, for local we instead of making this fully concurrent, let's just ensure that dagster only runs jobs sequentially on a local run. However, for production this should _definitely_ work without any locking issues (unless it's writing to the exact same partition on the same table on a database)

**Comment by Jabolol** [comment]
# limit concurrency

> [!NOTE]
> [Thread](https://github.com/dagster-io/dagster/issues/15752) regarding passing tags to non-job asset runs.

- Concurrency limits for non-job assets run cannot be set (Aug 2023).
- This means that only jobs executed via the job API can have concurrency limits set.
- Would need to check if running on k8s. If not (not prod), add the max limit to `1`.

```py
assets_job = define_asset_job(
  name="assets_job",
      config={
          "execution": {
              "config": {
                  "multiprocess": {
                      "max_concurrent": 1,
                  },
              }
          }
      }
  )
```

- Another option is setting a tag to the asset run and then using settings to
  limit concurrency. This is **not** supported yet, `tags={...}` are assets
  only, and `op_tags={...}` are passed to the underlining op, not the asset run,
  so the config cannot see the tags, and the concurrency limit cannot be set.

# solutions

> [!NOTE]
> [Thread](https://github.com/dagster-io/dagster/issues/8979) regarding passing tags to runs for concurrent limits.

- Use the "Limiting overall concurrency in a job" to limit the number of runs if
  the backend is DuckDB.

  - We may need to add a new asset_group for elements that require partitioned
    runs, and make users execute these from the job API (cons: no granularity,
    must materialize ALL assets).

- Run DuckDB single-threaded, and use the `multiprocess` config to limit the
  number of concurrent runs.

  - This is a good option if we want to limit the number of concurrent runs
    without affecting the rest of the pipeline.

**Comment by Jabolol** [comment]
Since we will only run `duckdb` in local development, the solution is to add the following entry to the configuration file at `$DAGSTER_HOME/dagster.yaml`:

```yaml
run_queue:
  max_concurrent_runs: 1
```
