### ISSUE TITLE
RF6: Identify a pool of Farcaster IDs for random sampling

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2071]
Requirements from @C-Emily-Furlong:

> For Round6, I want to randomly sample the ~100 Farcaster users next week so that the marketing team can prepare for the announcement. I think I can easily run a script in Gsheets to randomly select people,  all I need is a sheet of all f.ids that meet the requirements I mentioned in my previous message above. I've attached a csv file of the f.ids of guests and citizens to exclude from the set

Farcaster accounts should satisfy the following requirements:

- [ ] Filter out business accounts
- [x] Filter out existing Badgeholders and R5 Guest Voters
- [x] Filter out accounts that have had zero activity in the last 3 months
- [x] Filter out accounts that were created after the announcement (Sept 12)

**Comment by ccerv1** [comment]
Hi @C-Emily-Furlong -

I've created a [colab notebook](https://colab.research.google.com/drive/19caz3jGetrkVI4VtJ66_Hjgg3RHh15_B?usp=sharing) that runs this query on top of the Farcaster dataset. The query itself is very simple and we could potentially incorporate other filtering attributes (eg, they need to be casting in certain channels, they need some OpenRank global trust score, etc). Right now all we do is look for users that have casted at least once during a 3 month interval.

```
select
    fid,
    max(timestamp) as last_activity,
    count(distinct date_trunc(timestamp, DAY)) as count_cast_days,
    count(*) as count_cast_events
  from `farcaster.casts`
  where
    timestamp between '2024-07-01' and '2024-09-01'
  group by fid
```

After filtering out the 129 fids on your citizen/voter list, we're still left with ... 286713 potential users. That's a lot!!

We can probably tighten the filters. For instance, here's a distribution of `count_cast_days` by user:

![Image](https://github.com/user-attachments/assets/280d9141-fb8d-4c68-bd24-772bfa3d8a79)

... and here's the number of `count_cast_events` on a log10 scale: 

![Image](https://github.com/user-attachments/assets/b46927d8-2027-4248-bb53-79677667aaa2)

I prepared a [quick dump](https://docs.google.com/spreadsheets/d/1MhKzSgU6gIuYksXzDvR8lVKxtKAV0Sv9YSyq0b95EIM/edit?usp=sharing) that applies a filter of 10+ days and 100+ casts. This narrows the pool to around ~30K users.

**Comment by ccerv1** [comment]
PS - I'm not sure if it is possible to identify business accounts. [Farcaster docs](https://github.com/opensource-observer/oso/issues/2071) don't seem to mention this type of designation, and I don't see any fields in the data that seem relevant to this. My suggestion for this would be to create the pool of 100 and have 5-10 backup options. You could screen for potential business users when you send the DMs or have an opt-in that requires the user to confirm they are not a business.

**Comment by C-Emily-Furlong** [comment]
Thanks @ccerv1 ! is it possible to filter across any action (liking, casting, following..)instead of just the casting action? We want the population we're sampling from to be as unbiased as possible, just filtering for some amount of activity so we can increase the chances that the people who are selected are actually checking Warpcast somewhat regularly.

**Comment by ccerv1** [comment]
Yes, we can filter across:
- cast events
- likes / recast events
- follow / unfollow events

**Comment by C-Emily-Furlong** [comment]
great - I think we should filter out accounts that have taken none of those actions in the last 3 months

**Comment by ccerv1** [comment]
@C-Emily-Furlong 

# Guide for exploring Farcaster Data

Link to Loom: https://www.loom.com/share/a16227ced7b247f4b72669bdf2ec1c85

## AI Summary :) 

1. **Subscribe to the Dataset**

   - Go here: https://docs.opensource.observer/docs/integrate/overview/#farcaster-data and subscribe.
   - Choose the project you want to work with (e.g., my-oso-playground).
   - Save the changes to add the dataset.

2. **Access BigQuery Studio**

   - Navigate to BigQuery Studio.
   - Select the Farcaster dataset.
   - Begin with a simple query like selecting profiles.

3. **Run Queries**

   - Execute the query and wait for the results.
   - Adjust the query as needed, ensuring it stays within the free usage limits.

4. **Refine the Query**

   - Modify the query to extract specific data fields.
   - Join relevant tables to link data properly.
   - Filter out null values if necessary.

5. **Review and Save Results**

   - Check the query results for accuracy.
   - Save the results for further exploration or analysis.
   - Consider exporting the data to a spreadsheet for easier viewing and manipulation.

##

Copy of my query:

```
with farcaster_events as (
  select
    fid,
    timestamp
  from `my-oso-playground.farcaster.casts`
  union all
  select
    fid,
    timestamp
  from `my-oso-playground.farcaster.reactions`
  union all
  select
    fid,
    timestamp
  from `my-oso-playground.farcaster.links`
)

select
  events.fid,
  json_value(profiles.data, "$.username") as username,
  max(events.timestamp) as last_activity,
  count(distinct date_trunc(events.timestamp, DAY)) as count_cast_days,
  count(*) as count_cast_events
from farcaster_events as events
left join `my-oso-playground.farcaster.profiles` as profiles
  on events.fid = profiles.fid
where
  events.timestamp between '2024-07-01' and '2024-09-01'
  and json_value(profiles.data, "$.username") is not null
group by 1,2

```

**Comment by ccerv1** [comment]
Also linking my sample results: https://docs.google.com/spreadsheets/d/1o8Vw2CMbDFlar9cJycIbNr_2nLPdULZj5tE_sm-WHFE/edit?usp=sharing
