### ISSUE TITLE
docs: network graph analysis raw data sources

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2072]
We should create a guide for doing network graph analysis on OSO. 

Here is a [Loom Video](https://www.loom.com/share/75840fe5dd1a48a49c19a3c46a2a91cf?sid=159a65ee-1d8b-4708-ba11-a76f55efca2c) explaining how to query the data.

For now, I will just do a short list of resources that exist:

## Farcaster social graph

```
select distinct
  fid,
  target_fid
from `{YOUR_PROJECT_NAME}.farcaster.links`
where deleted_at is null
limit 10
```

## Github contribution graph

```
select distinct
  user_artifacts.artifact_name as user,
  repo_artifacts.artifact_name as repo
from `{YOUR_PROJECT_NAME}.oso.timeseries_events_by_artifact_v0` as events
join `{YOUR_PROJECT_NAME}.oso.artifacts_v1` as user_artifacts
  on events.from_artifact_id = user_artifacts.artifact_id
join `{YOUR_PROJECT_NAME}.oso.artifacts_v1` as repo_artifacts
  on events.to_artifact_id = repo_artifacts.artifact_id
where
    events.event_type = 'COMMIT_CODE'
    and events.time > '2024-01-01'
```

## OpenRank data challenge with Byte Explorers

There are a collection of starter notebooks [here](https://github.com/opensource-observer/insights/tree/main/community/data_challenges/openrank).

## RPGF3 PageRank bounty

There is a playground GitHub dataset and several PageRank implementations (for repos, not developers) [here](https://github.com/opensource-observer/insights/tree/main/community/bounties/page_rank_rpgf3)

**Comment by ryscheng** [comment]
@ccerv1 can you link to where the resources are?

**Comment by ccerv1** [comment]
> @ccerv1 can you link to where the resources are?

They are already linked above @ryscheng ... did you mean something else?

**Comment by ccerv1** [comment]
Add to discussion thread

**Comment by ccerv1** [comment]
cc @astralblue

**Comment by ccerv1** [comment]
Cataloged in this discussion: https://github.com/opensource-observer/oso/discussions/2120
