### ISSUE TITLE
File issues into OSO Insta-analysis Epic

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2097]
### What is it?

https://github.com/opensource-observer/oso/milestone/46

The intention of this epic to to capture how do we turn a grant exploration into < 1 day. 
i.e. Foundation gives us a CSV dump of a grant round. We can import this into oss-directory, run pipeline, show valuable insights automatically in the web app. All in less than a day.

What aspects of an ecosystem report are something we should be able to generate for any collection?

Note: This assumes we've already shipped the [OSO terminal MVP](https://github.com/opensource-observer/oso/milestone/12) and this is follow-on work.

Note: If it's useful, feel free to pull in issue from our [OSO terminal backlog](https://github.com/opensource-observer/oso/milestone/47)

**Comment by ccerv1** [comment]
I've reviewed your issues and added one of my own. Will close out now!
