### ISSUE TITLE
Update ThankArb collection

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2140]
### What is it?

The following projects were added / updated in the [most recent PR](https://github.com/opensource-observer/oss-directory/commit/6e07eca5346ea75ae43d0183b40c097d447a7ceb) to oss-directory. They should be included in the [Thank Arb collection](https://github.com/opensource-observer/oss-directory/blob/main/data/collections/thank-arb-grantees.yaml)

```
appcalipse
arbilearn-aliveevie
arbitrumhub
astralprotocol
astrodevs-labs
basket-swap-stylus-teeeeeo9
cartographer-syndicate
circuitscan
coindlabs
collabberry
cryptosmartnow
daomasons
decentralized-library-gifted-brain-lab
duel3
ecoland-world
elefria-labs
ethdailyhub
ethereum-attestation-service
framelib
givestation
glo-foundation
grantsscope
greenpill-dev-guild
hvax
hypercerts
ikigai-labs-xyz
inferer
lexdao
merkle-root-inc
moona-lisa
nounspace
pattern-tech
peacekeepers88
peeramid-labs
rankify-it
refi-starter
rndao
seroxdesign
sherlock-protocol
solide-project
songs-tools
stogramhq
theforus
thenamespace
togethercrew
tx-city
umbra-scopelift
vyperlang
web3-gpt
zktlabs
```

**Comment by ccerv1** [comment]
cc @rohitmalekar

**Comment by rohitmalekar** [comment]
Thanks @ccerv1, [raised a PR](https://github.com/opensource-observer/oss-directory/pull/491) to update the Thank Arb collection (the checks are successful).

**Comment by ccerv1** [comment]
Marking as complete!
