### ISSUE TITLE
Funding the Commons Bangkok talk prep

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2225]
### What is it?

Evolving retrofunding with continuous experimentation

Existing retrofunding programs have distributed millions of dollars to date, usually in the form of large but infrequent distribution rounds. This poses 2 problems: (1) From the perspective of the recipient projects, it makes budgeting and planning difficult, without fine-grained feedback on their impact. (2) From the perspective of the funder organization, it reduces the iteration cycle for experimentation. If we think of retrofunding as an impact optimization experiment, we propose a new system where discrete rounds are replaced with continuous funding flows that are dynamically re-adjusted by data/AI-augmented governance processes. By drastically shortening the feedback loop, we aim to quickly iterate towards funding allocations that maximize positive changes in impact outcomes per unit dollar invested into the ecosystem.

**Comment by ryscheng-mobile** [comment]
Gonna scope in a quick refresh of the OSO talk as well for the OSS Hub

**Comment by ccerv1** [comment]
https://docs.google.com/presentation/d/1fbcZB1IK2JKhOi5JVZzavC-EyOzxTxlQ07GmjYSwu9o/edit?usp=drive_link
https://docs.google.com/presentation/d/1CbuOoQZF1Rxq7iivyhzkSx6qCUiF661z0VXTn7KbUnk/edit?usp=drive_link
