### ISSUE TITLE
Improve the OSS-Funding schema(s)

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2229]
## Context

We currently don't have a proper schema for OSS Funding events. 

- `oso_slug`: The OSO project slug (if it exists).
- `project_name`: The name of the project (according to the funder's data).
- `project_id`: The unique identifier for the project (according to the funder's data).
- `project_url`: The URL of the project's grant application or profile.
- `project_address`: The address the project used to receive the grant.
- `funder_name`: The name of the funding source.
- `funder_round_name`: The name of the funding round or grants program.
- `funder_round_type`: The type of funding this round is (eg, retrospective, builder grant, etc).
- `funder_address`: The address of the funder.
- `funding_amount`: The amount of funding.
- `funding_currency`: The currency of the funding amount.
- `funding_network`: The network the funding was provided on (eg, Mainnet, Optimism, Arbitrum, fiat, etc).
- `funding_date`: The date of the funding event.

We should create a schema for a `funder`, ie, as a YAML file similar to how we handle a project. We should then enumerate any artifacts owned by the funder that are linked to funding events. For example, it could a deployer for grants rounds (eg, Gitcoin), a multi-sig (eg, most L2 grants), or an Open Collective source. CSV uploads can then be validated against the schema.

Eventually, we should be able to detect batches of grants that can be reviewed / approved, rather than entered manually via CSV upload. However, in the near term, we just want to be stricter about validating the CSV data.

## Recommended Actions

- [ ] Review the DAOIP standard and diff against what we currently have
- [ ] Create a YAML funder profile that is compliant with the DAOIP standard
- [ ] Simplify the CSV funding data schema to the bare minimum, eg:
       - Project Identifier (oso name)
       - Funder Identifier (do we need a namespace for funders??)
       - Event Data: date, amount in USD, to/from artifacts
       - Optional but helpful metadata: Names of funding rounds, currencies, etc

**Comment by ryscheng** [comment]
Ah okay cool, thanks for proposing a simple schema. I am curious how different this is from DAO-IP5?

**Comment by ccerv1** [comment]
> Ah okay cool, thanks for proposing a simple schema. I am curious how different this is from DAO-IP5?

Yep that's probably the research we need here. Linking the standard: https://github.com/metagov/daostar/blob/main/DAOIPs/daoip-5.md

**Comment by ccerv1** [comment]
Here is an example funder schema for Octant based on DAOIP-5: https://github.com/opensource-observer/oss-funding/blob/main/data/funders/octant/octant.yaml

Here is an example funding event CSV upload for Octant: https://github.com/opensource-observer/oss-funding/blob/main/data/funders/octant/uploads/epoch_1.csv
