### ISSUE TITLE
Validate OSS Funding CSV uploads

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2230]
### Describe the feature you'd like to request

Similar to OSS Directory, we should have a validator that checks that required fields contain useable data. 

### Describe the solution you'd like

A github action that validates any pull request and shares a log of issues. The most important thing is probably to validate from_funder, to_project, amount_usd, and date. The other fields are probably optional.

### Describe alternatives you've considered

Manual review of PRs

**Comment by ryscheng** [comment]
So in oss-funding there's both the raw uploads, and the cleaned datasets. I think we should expect raw uploads to come in a variety of formats, but someone should write a python script to clean it up into a single standard.

Then yes, I agree we should create validators to check that all clean data sets satisfy the same schema.
I wonder if we can convince the DAOIP-5 folks to write the validator for us? Sounds like they're most motivated here

**Comment by ccerv1** [comment]
We have a DAOIP-5 validator here: https://github.com/opensource-observer/oss-funding/pull/7
I also implemented a manual validator of our CSV uploads for now: https://github.com/opensource-observer/oss-funding/pull/11
