### ISSUE TITLE
importOssDirectory isn't up to date

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#224]
### To Reproduce

The latest migrations on oss directory means that the existing package used by OSO isn't working. Haven't looked into why yet but if you try to run `pnpm start:indexer importOssDirectory` it will eventually hang. 

### Describe the Bug

See above

### Expected Behavior

It should completely import OSS Directory.

**Comment by ryscheng** [comment]
I think you just need to build the latest changes and publish to npm

The `oss-directory` package will need to be updated on npm after every schema change
