### ISSUE TITLE
Some projects/collections 404

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2259]
### Which area(s) are affected? (leave empty if unsure)

Frontend

### To Reproduce

Examples:
- https://www.opensource.observer/collections/filecoin-builders
- https://www.opensource.observer/projects/pinatacloud

### Describe the Bug

![image](https://github.com/user-attachments/assets/8313bfee-a77b-49fd-a114-58adcd75051f)

### Expected Behavior

A project/collection page should load

**Comment by ryscheng** [comment]
This is actually behaving as intended from the perspective of the frontend ---  if you do this SQL query in Clickhouse

```
SELECT * FROM projects_v1 WHERE project_name = 'pinatacloud';
```

Yields no results.
Are these new to oss-directory?
If so, I suspect that we've imported to BigQuery already (which populates Algolia), but we haven't copied the marts to Clickhouse.

**Comment by ryscheng** [comment]
Gonna try copying projects_v1 and collections_v1 from BQ to Clickhouse here
dagster.opensource.observer/runs/4420f2ca-0693-4361-a3fa-22380346be5a

**Comment by ryscheng** [comment]
We fixed the bq2clickhouse factory yesterday. I think this just involves running those jobs again

**Comment by ryscheng-mobile** [comment]
We manually copied a bunch of tables last week. Closing this as @ravenac95 is working on getting the end to end pipeline running again
