### ISSUE TITLE
sqlmesh timeseries rolling windows metrics seem off

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2266]
### What is it?

https://www.opensource.observer/projects/opensource-observer

commit counts look low, separately from the fact that we're missing the backfill
for reference
https://github.com/opensource-observer/oso/graphs/contributors

Current hypothesis is that the sqlmesh factory is technically correct, but Clickhouse execution has so many errors, maybe there's writes that get lost and affect correctness. 

Requires more investigation

**Comment by ravenac95** [comment]
Closed with #2426 and #2430
