### ISSUE TITLE
Impact metrics methodology paper draft 1

### ISSUE THREAD

**Issue by evanameyer1** [opensource-observer/oso#2271]
Researching and drafting a report on how impact metrics are currently used across the industry, with the hope of developing a standardized, improved approach.

**Questions to Answer:**

- How were previous funding models (Impact=Profit approach) utilized? Pros, cons?
- What are the primary challenges that members express with regards to funding models?
- Why are impact metrics relevant to the Optimism ecosystem? 
- What problems do impact metrics still have/don’t solve?
- What are the current methodologies and practices for measuring impact within the Optimism chain?
- How has the shift to the Impact=Funding model changed the approach to evaluating projects?
- What are the primary impact metrics that are currently used?
- In what ways does the overemphasis on quantitative data limit community engagement and accurate impact assessment?
- How do static definitions of "trusted users" potentially exclude valuable contributors?
- How can the analysis of impact metrics be made scalable and replicable for future funding seasons?

**Paper format:**
1. Detailed Review of Existing Methodologies and Practices
2. Proposal of Improved Methodology

**Comment by ryscheng** [comment]
@evanameyer1 awesome to see you filing issues! Would you mind adding a bit more details in the descriptions so that we can help triage? thanks

**Comment by evanameyer1** [comment]
Yep, will do now!

**Comment by evanameyer1** [comment]
https://docs.google.com/document/d/1-fPDALyYSzvLlMcTPFfdEuu9G6fAX1H5WfGEDx4tiBw/edit?usp=sharing

**Comment by ccerv1** [comment]
Thanks Evan! Good stuff.
I'm not able to add comments (requested access) but in the meantime, here are a few more articles that that this prompted:

- https://gov.gitcoin.co/t/public-goods-funding-must-be-evolutionary/18728 - metrics will quickly become targets, so we need to evolve them until we find the right balance of difficulty and meaningfulness
- https://forum.arbitrum.foundation/t/stablelab-analyzing-stip-s-efficacy-and-ltipp-comparison/24777#stip-vs-ltipp-comparison-statistics-27 - discussion of growth specific metrics, which are narrower than the typical retro funding metrics
- https://kermankohli.substack.com/p/arbitrums-85m-growth-campaign - cautionary tale!

**Comment by evanameyer1** [comment]
Sorry about that, try now - you should be able to edit and add comments.

**Comment by evanameyer1** [comment]
@ccerv1 @ryscheng Let me know your thoughts on some of the solution ideas I have at the bottom of the report - they are pretty simple ideas, and I haven't flushed them out much yet, but I wanted to see what you guys thought before I dove deeper. Any specific problems or areas I should prioritize over others?
