### ISSUE TITLE
Debug developer activity metrics

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2274]
### Which area(s) are affected? (leave empty if unsure)

Indexer

### To Reproduce

Here is a query in Clickhouse:

```
select
    m.metric_id,
    m.metric_name,
    t.sample_date,
    t.amount
from metrics.timeseries_metrics_by_project_v0 as t
join metrics.metrics_v0 as m
    on t.metric_id = m.metric_id
join default.projects_v1 as p
    on t.project_id = p.project_id
where
    p.project_name = 'opensource-observer'
    and t.sample_date = '2024-09-22'
order by m.metric_name
```

### Describe the Bug

We get back the following, which shows 1s for most fields.

![image](https://github.com/user-attachments/assets/d8e2901e-a352-448a-a7dc-23679554960f)

### Expected Behavior

The calculations are not correct (should not be 1s across the board). Moreover, it is not clear how `active_developers` and `developer_active_days` relate to each other.

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oso/pull/2270/files
