### ISSUE TITLE
OP: Aggregated GH repo metrics

### ISSUE THREAD

**Issue by JSeiferth** [opensource-observer/oso#2283]
### What would you like to see? Please provide a clear and concise description of what you want

For Retro Funding 5, could we get some  aggregate github repo metrics like:
1. How many unique contributors are we rewarding? 
2. How many years in development? 
3. How many forks/stars?

### Is there any additional context you can share? Feel free to include notes or screenshots that can help us research and track the issue.

I'm wondering if this is useful information to showcase the results of the round "Retro Funding 5 has rewarded more than 1 billion full time contributors"

**Comment by ccerv1** [comment]
Added a notebook here: https://github.com/opensource-observer/insights/blob/main/analysis/optimism/retrofunding5/RF5_ConsolidatedMetrics.ipynb

Metrics:
- Forks: 38021
- Stars: 132856
- Developer years: 194
- Developers (all time): 566
- Developers (last 2 years): 461
- Contributors (all time): 11903
- Contributors (last 2 years): 4991

**Comment by JSeiferth** [comment]
@ccerv1 could we get this for the R5 scope timeline? October 2023 - Aug 2024?

So we can make statements like "Retro Funding 5 rewarded 400 developers for their work on the OP Stack"

**Comment by ccerv1** [comment]
Updated @JSeiferth 

- Forks: 38021
- Stars: 132856
- Developer years: 194
- Developers (all time): 566
- Developers (RF period): 374
- Contributors (all time): 11903
- Contributors (RF period): 2596
