### ISSUE TITLE
OP: Dashboard for Project, Org, and Retro Funding attestations

### ISSUE THREAD

**Issue by JSeiferth** [opensource-observer/oso#2291]
### What would you like to see? Please provide a clear and concise description of what you want

I'd like to see a dashboard with live updates that shows me
1. The number of projects that have been created 
2. The number of Orgs that have been created 
3. The number of Retro Funding applications for a given round

These are very basic and a first step. Later, we'd like to see more extensive metrics that use the metadata in the attestations
1. Number of new onchain project registered
2. Number of new projects registered with Github repos above x metric 
3. Round over round overlap: How many projects have applied to multiple round
4. Time since last project update: Time since a project has been updated
5. Change in project admin permissions

### Is there any additional context you can share? Feel free to include notes or screenshots that can help us research and track the issue.

Currently I have a very humble [dune dashboard](https://dune.com/Jonasssss/retro-funding-4-applications) which isn't working super well. 
You can find all relevant attestation schema's [here](https://docs.optimism.io/chain/identity/schemas)

Please provide an ETA for when the first version of this would be live

**Comment by C-Emily-Furlong** [comment]
I would add
- Number of unique users that are admins / contributors to projects (might make sense to include this after we have made changes to how contributors are represented in attestations)
- Of the unique users (fids) associated with projects and orgs, what percentage have a verified address linked with their fid?
- Share of projects with more than one contributor
- Share of orgs with more than one member
- Share of projects that belong to an org vs. aren't associated with an org
- number of projects / orgs created per day and also cumulative total

**Comment by ccerv1** [comment]
Got it. 

The best option would probably  be for us to integrate with Agora / OP Atlas, so they can grab a generic set of metrics for any Project / Org at any time. Otherwise we'd need to recreate all of the attestation matching logic that they've already done. Then we just need to write a model to lookup the relevant stats based on the Project / Org info they send.

Would that work @JSeiferth or are you looking for something with no Agora dependency?

**Comment by ccerv1** [comment]
Prereqs:
- Determine which of these [EAS schemas](https://docs.google.com/spreadsheets/d/1ePlaR9SfF3L6XS9ReDp6n8eOAijxV82L2ZvcYHgR2GE/edit?usp=sharing) are relevant
- Get API token from Agora

**Comment by ccerv1** [comment]
V0 here:
https://app.hex.tech/00bffd76-9d33-4243-8e7e-9add359f25c7/app/f0af1836-73c7-4bc6-83a8-06d0623fe139/latest

This addresses the basic attestation info without digging into the metadata

**Comment by JSeiferth** [comment]
@ccerv1 lets only count unique applications (dedup applications that reference the same project ID) - every time a user makes an edit and resubmits their application, they're creating a new attestation. What we want to capture is the number of applications, not the number of attestations. Same applies to entities.

**Comment by ccerv1** [comment]
Hey @JSeiferth I think I have this working correctly now. Have a look here: https://app.hex.tech/00bffd76-9d33-4243-8e7e-9add359f25c7/app/f0af1836-73c7-4bc6-83a8-06d0623fe139/latest

**Comment by ccerv1** [comment]
Loom here: https://www.loom.com/share/8d2d0d0e69b74ffa8a1f24ed424f3edc?sid=25bdecf4-ad0f-4678-a72e-82370615b107

**Comment by ccerv1** [comment]
Closing the v1 out and moving additional features into here https://github.com/opensource-observer/oso/issues/2357
