### ISSUE TITLE
OSO list of talks and events

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2310]
### What is it?

We should have a page on our documentation of all talks we've given in the past, and a list of events we are hosting or going to, upcoming and past.

**Comment by karibaEA** [comment]
Ray's list of talks and events [here](https://www.raymondcheng.net/about/publications/talks/)

**Comment by karibaEA** [comment]
Got Carl's [here](https://www.youtube.com/results?search_query=%22carl+cervone%22)

Updated the list

**Comment by karibaEA** [comment]
Transferred [here ](https://github.com/opensource-observer/oso/blob/steph/apps/docs/docs/references/events.md)

**Comment by karibaEA** [comment]
Format:
For every talk, make sure it looks the same.
Title, Location, Date, Link to video,
Generally make the list look uniform
Then sort in reverse chronological order

**Comment by ryscheng** [comment]
Refactored event list here
https://github.com/opensource-observer/oso/pull/2355
