### ISSUE TITLE
Bug: CORS + Authorization tokens seem to be failing

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2312]
### What is it?

https://discord.com/channels/1151273191419953224/1291468489701330954

Tracking this Discord thread here
![image](https://github.com/user-attachments/assets/079104fe-1834-420d-8f4e-cf96db828267)

**Comment by ryscheng** [comment]
I don't have the headers, so I was trying to replicate it.....

Things I checked:
- If you use the Apollo sandbox explorer here https://studio.apollographql.com/sandbox/explorer, it works fine still. So I don't think its a CORS issue on the primary pathway
- I also previously configured liberal CORS policies here https://github.com/opensource-observer/oso/blob/main/apps/frontend/next.config.js
- I did notice a weird error when I put in an Authorization header from the Apollo sandbox, so that implies that it has to do with CORS-related auth
- Trying this fix here 
https://github.com/opensource-observer/oso/pull/2311

**Comment by MasterHW** [comment]
https://github.com/opensource-observer/oso/pull/2311 seems to have fixed. thank you!

**Comment by ryscheng** [comment]
Closing thanks for the bug report!
