### ISSUE TITLE
Add Stellar OSS projects and create collection

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2316]
### What is it?

https://airtable.com/appymB1sbp5uidiGe/shrsaWm1IyNZTCEhX/tblpytbu3t73kssiE

**Comment by rohitmalekar** [comment]
@ccerv1 Will do this in a few batches, starting with projects that have shared the link to the Github repo. Amongst the projects that have provided a website but no info on Github, I am finding that the website often includes a reference to Github. Will manually recover the Github link and process such projects in the second batch.

**Comment by rohitmalekar** [comment]
Ready for merge here - https://github.com/opensource-observer/oss-directory/pull/524

**Comment by rohitmalekar** [comment]
@ccerv1 the collection is ready to merge here: https://github.com/opensource-observer/oss-directory/pull/529
