### ISSUE TITLE
awesome-oso for tracking community work

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2326]
### What is it?

We should track an awesome-list of cool things people have built with OSO, including:
- API integrations (like Gitcoin)
- Cool dashboards (like for ThankArb)
- Cool tools/utilities (like DeveloperRank)

**Comment by ryscheng** [comment]
Started one here
https://github.com/opensource-observer/awesome-oso

**Comment by ccerv1** [comment]
Added 2/3. Will see what the Gitcoin integration looks like when the new round goes live.
