### ISSUE TITLE
Briefing on dev dependency tracking

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2338]
### What is it?

How do we get all the dependency data and link it to projects?

**Comment by ryscheng** [comment]
@ccerv1 can you clarify the scope of this issue?

I think we still need an issue for GitHub repo => package dependencies.
We only have package => package dependencies atm.

**Comment by ccerv1** [comment]
# Dependency Tracking Project Update

## Objective

The main goal of this project is to create a comprehensive graph that shows:
- Which developer tools are being used by Optimism projects (both onchain projects and other OSS tools)
- When these projects started using these tools

From the graph, we can easily analyze downstream impact associated with these tools, including:
  - Number of dependents
  - Downstream gas fees
  - Downstream active developers
  - etc.

## Requisite Data Sources

1. deps.dev dataset:
   - Maintained by Google
   - Covers various package managers (NPM, Go, Maven, Python, Rust/Cargo)
   - Available in BigQuery (full dataset ~45 terabytes)

2. GitHub data:
   - Software Bill of Materials (SBOM) for relevant projects
   - Shows which repositories import specific packages (e.g., Ethers) into their package.json or requirements

3. Onchain project data:
   - List of projects identified as being part of Optimism (e.g., in OP Atlas)
   - Potential to expand to other relevant projects that haven't signed up for Retro Funding (e.g., all of OSO projects)

4. NPM standard metrics:
   - Downloads
   - Releases

## Progress

1. Created a snapshot of the deps.dev dependency graph:
   - Focused on the last month of data
   - Limited to first-level (direct) dependencies
   - Currently only looking at NPM packages
   - Snapshot size: ~35 gigabytes

2. Developed a preliminary deps.dev query to match Optimism projects with their dependencies:
   - Caveat: this only identifies projects with packages that include another package, so this doesn't capture applications that  simply include the package in their dependencies
   - Ethers had 60 matches (out of 500+ Optimism projects on OSO)
   - Results include both web3-specific packages (e.g., Ethers, Viem, OpenZeppelin) and general-purpose packages (e.g., Axios, Lodash, React)

## Next Steps

1. Incorporate GitHub SBOM data:
   - Extract and process SBOM data for relevant projects
   - Identify which repos using specific packages (e.g., Ethers) are associated with the Optimism ecosystem

2. Improve project identification:
   - Review the matching process to identify more potential projects
   - Consider including projects with active contracts that aren't yet in OSO or OP Atlast

3. Deduplicate results:
   - Remove duplicate entries pointing to the same GitHub organization (e.g., Ethers and Ethers project)

4. Integrate NPM metrics:
   - Incorporate download statistics, release information, and other relevant metrics from NPM

5. Expand data sources:
   - Consider including Python and Rust packages in the analysis
   - Explore ways to efficiently query the full deps.dev dataset for more comprehensive results

6. Metrics implementation:
   - Create a long list of potential metrics
   - Work with badgeholders to refine list of metrics
