### ISSUE TITLE
WAR in practice blog post

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2344]
### What is it?

https://gov.optimism.io/t/advanced-metrics-for-retro-funding/8711
https://docs.opensource.observer/blog/war-for-public-goods

Possibly expand on this in preparation for CDMX?

**Comment by ccerv1** [comment]
@ryscheng did a write-up on my flight back about synthetic controls. Feel free to propose any edits. I thought about adding a final paragraph about the FTC residency but figure that may warrant a separate blog post.
