### ISSUE TITLE
Footer links drop you at the bottom of the page

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2352]
### Which area(s) are affected? (leave empty if unsure)

Frontend

### To Reproduce

Click any link on the footer:
![image](https://github.com/user-attachments/assets/5b0ff2d7-2d19-4199-bd33-5ebe1c3aeb65)

It will drop you at the bottom of the page instead of the top.

### Describe the Bug

The links don't go to the top of the page

### Expected Behavior

The links should take the user to the top of the page

**Comment by ryscheng** [comment]
Worth fiddling with this setting
https://nextjs.org/docs/app/api-reference/components/link#scroll

**Comment by ryscheng** [comment]
Forcing a `window.scrollTo(0x0)` in Plasmic v73.2.1
