### ISSUE TITLE
OSSD repositories is repeatedly failing to materialize

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2353]
### Which area(s) are affected? (leave empty if unsure)

Indexer

### To Reproduce

Hit materialize:

https://admin-dagster.opensource.observer/assets/ossd/repositories?view=events&time=1728437543117

### Describe the Bug

Something is failing in dagster and it's difficult to determine the issue from logs

### Expected Behavior

The job should run as expected or provide a more actionable log

**Comment by ravenac95** [comment]
Fixed manually!
