### ISSUE TITLE
The updated `ossd.repositories` source data doesn't exist in the playground

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2354]
### Which area(s) are affected? (leave empty if unsure)

Indexer

### To Reproduce

Grab my PR:

```
gh pr checkout 2346
```

Then run the following dbt command:

```
dbt run --select stg_ossd__current_repositories   
```

However, the same command works in the production environment, ie:

```
dbt run --select stg_ossd__current_repositories   --target production
```

### Describe the Bug

Several new fields were added to `oso_source('ossd', 'repositories')` including `created_at` and `updated_at` 

However, the playground is unable to access this (updated) source data. Thus, we get the error:

```
Unrecognized name: created_at
```

We get the same failure when we try pushing the PR: https://github.com/opensource-observer/oso/pull/2346

### Expected Behavior

The playground environment should execute the staging model (and this [PR should](https://github.com/opensource-observer/oso/pull/2346) merge)

**Comment by ravenac95** [comment]
Was a generally simple fix but, as I was debugging I realized there was a bit of manual work to get this working.
