### ISSUE TITLE
Dagster dlt asset for fetching repo dependencies from GitHub API

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2363]
### What is it?

For context, see here #2338 

This issue captures the research around finding the best option given the tradeoffs we can anticipate regarding coverage quality and execution risk

**Comment by ryscheng** [comment]
Re-assigning to @Jabolol . After speaking to @ravenac95 we agreed that the GitHub approach was the lower risk approach for now.

Let us know if you have any questions!
