### ISSUE TITLE
Determine project signup requirements

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2364]
### What is it?

After completing #2363 then:

See [Notion](https://www.notion.so/Retro-Funding-7-Dev-Tooling-round-details-1215831e345280beba3ac01919781518?pvs=4)

## Timeline:
1. Sign up: November 11th - November 25th
2. Application Review Process: November 26th - December 9th
3. Voting: January

## Eligibility:
1. Libraries must have been made **publicly available before [DATE]** via one of the following package managers: **NPM**, **PIP**, **Yarn**, or **GitHub Packages**. Libraries not distributed via these platforms will not be considered.
2. Builders must **verify library ownership** through the Retro Funding sign-up process.

## Open question:
How do we verify that a certain builder maintains a certain library?

**Comment by ccerv1** [comment]
Good people to speak to:
- TMM (Viem)
- Faina (OP Labs)

**Comment by JSeiferth** [comment]
Things to validate

### What Package managers do we need to support?
We should discover this by seeing what package managers are used by RF4 Onchain Builder projects. 

### How do we verify package ownership?
In favour of the simplest solution here

**Comment by ryscheng** [comment]
@JSeiferth IMO the simplest solution is to ask people to require people to add a GitHub repository in their own repo's `package.json` file.
See [here](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository)

It's the best industry convention for linking npm => GitHub.

Then for verification, when a project registers their npm package, we can:
1. Query the npm server to get this manifest file.
2. Get the GitHub repo from the manifest
3. Verify that the user is a owner of this GitHub repo using the same process that we used for GitHub.

Only people with publish rights to the npm package AND is a GitHub owner of the repo will be able to claim the npm package this way.

We can implement the both on the Agora frontend and oss-directory validator logic.

**Comment by ccerv1** [comment]
Summary of our discussion just now cc @JSeiferth:

- We will focus on npm (JavaScript) and crates (Rust) only
- Sign up flow:
   - Project will select their package(s) in the sign up
   - Query the npm / crates* server to get the manifest
   - Get the GitHub repo from the manifest
   - Verify that the user is an owner of the GitHub repo via the funding.json
 - Eligibility check:
   - Projects must have 3+ dependents in the ecosystem
   - Hopefully we can just have an initial list that captures >90% and then any project that isn't on it can give evidence (eg, GitHub of three projects that use them, which we can review)
- Open questions:
   - OSO need to verify that crates works the same as npm in terms of getting the manifest
   - OP need to share this flow with Agora to make sure they our comfortable implementing it
   - OSO will put together an updated list of libraries and downstream metrics before Devcon 🤞
