### ISSUE TITLE
Timescale data tiering

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#239]
### Describe the feature you'd like to request

https://docs.timescale.com/use-timescale/latest/data-tiering/

### Describe the solution you'd like

At some point, we maybe want to archive raw Event data to S3.
Timescale has built-in support for tiering data into Parquet files

### Describe alternatives you've considered

Could use a migration service to replicate data to a data warehouse too

**Comment by ryscheng-mobile** [comment]
Deprecating, we are moving off Timescale likely
