### ISSUE TITLE
Timescale compression

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#240]
### Describe the feature you'd like to request

https://docs.timescale.com/use-timescale/latest/compression/about-compression/

### Describe the solution you'd like

Seems like a key value-add for timescale, worth exploring before the end of the 30 day free trial

### Describe alternatives you've considered

Leave it

**Comment by ryscheng** [comment]
Backlogging this until our DB bill is terrible

**Comment by ryscheng-mobile** [comment]
Deprecating, we are moving off Timescale likely
