### ISSUE TITLE
SQLMesh metrics progress

### ISSUE THREAD

**Issue by Jabolol** [opensource-observer/oso#2420]
### What is it?

This issue tracks the progress implementing the metrics from #2275 with SQLMesh.

Event Source | Metric | Time-Series Type | Done
-- | -- | -- | --
GitHub | repository_count | Point-in-Time | X
GitHub | first_commit_date | Point-in-Time | X
GitHub | last_commit_date | Point-in-Time | X
GitHub | star_count | Point-in-Time |  X
GitHub | fork_count | Point-in-Time |  X
GitHub | contributor_count | Point-in-Time | X
GitHub | contributor_count_6_months | Interval | X
GitHub | new_contributor_count_6_months | Interval | 
GitHub | fulltime_developer_average_6_months | Interval | 
GitHub | active_developer_count_6_months | Interval | X
GitHub | commit_count_6_months | Interval | X
GitHub | opened_pull_request_count_6_months | Interval | X
GitHub | merged_pull_request_count_6_months | Interval | X
GitHub | opened_issue_count_6_months | Interval | X
GitHub | closed_issue_count_6_months | Interval | X

**Comment by ravenac95** [comment]
@Jabolol just double checking but do you have any additional metrics to add? I am going to start this in the morning. Wrote some scripts to make it a little more fool proof for myself.

**Comment by Jabolol** [comment]
> @Jabolol just double checking but do you have any additional metrics to add? I am going to start this in the morning. Wrote some scripts to make it a little more fool proof for myself.

I do! Finishing some right now. Will merge before standup :)

**Comment by ravenac95** [comment]
@ryscheng @ccerv1 There's a metric here `fulltime_developer_average_6_months` what does that mean?

**Comment by ryscheng** [comment]
@ravenac95 I think it means a rolling window count of fulltime developers as a time series metric. @ccerv1 can you confirm?

In which case, we should probably rename it to `fulltime_developer_count_6_months`

Reference
https://docs.google.com/spreadsheets/d/1V2EDoF_YvFjOX1HlhROOXQxcKdScSw5pAEBqLzB8gto/edit?gid=0#gid=0
