### ISSUE TITLE
Devcon presentation

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2456]
📥 Use this Slides Link for Your Session: "Optimism Retro Funding: So Far, So Good, So What!?":

https://devcon.org/en/sea/presentation/QCMZS8

If this email is not a Gmail account or you encounter access issues, please provide an alternate email so we can grant access.

You must use this link to submit your slides. Feel free to use our template or your own slides, but you must upload your slides at this URL.

📘 Speaker Guide
Please review the [Speaker Guide](https://ef-events.notion.site/Speakers-Devcon-Wiki-127638cdc41580619bb4f8dd7f735e52?pvs=4) for all you need to know about Devcon. We will continuously update it with useful information.

✅ Double Check Your Session Details
Session Details
- Date: 2024-11-12
- Time: 17:30
- Room: Stage 2
- Format: Talk (20"Talk+5"Q&A)

If you have any question or feedback, don’t hesitate to reach out.

Best regards,
The Devcon Team

https://docs.google.com/presentation/d/13Pt_GSxCedQkGTiptcOxzfpSOiZRApdYLaDdfjTzw8A/edit#slide=id.p

**Comment by ryscheng-mobile** [comment]
@ccerv1 can you move this to the shared drive presentation folder? I'm curious if there's any material I can borrow for the FDS thing in a couple days

**Comment by ccerv1** [comment]
I'm not able to move it or create a shortcut for some reason. But I gave you edit access
