### ISSUE TITLE
Extract relevant grant and project data from the GovGrants tracker

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2491]
### What is it?

The first step is getting a handle on which projects have received growth grants and for what intended objectives. This [spreadsheet](https://docs.google.com/spreadsheets/d/1Ul8iMTsOFUKUmqz6MK0zpgt8Ki8tFtoWKGlwXj-Op34/edit?gid=769451685#gid=769451685) has all relevant information about the projects (including links to their grant applications). 

I've taken a first step in parsing the sheet [here](https://github.com/opensource-observer/insights/tree/main/analysis/optimism/govfund_grants). 

We should try to obtain the following for all growth grants:

- Project info (see JSON)
- Markdown or plaintext version of project application
- Relevant dates of disbursement
- L2 addresses (the application may include other addresses)
- The chain(s) where activity is expected. See [here](https://docs.google.com/spreadsheets/d/1fF6BMvX7hgsEEMSOU2_RLumQaMjpH8ucaqfAiO_vspY/edit?usp=sharing) for a list of OP chains. Once that are not on OSO but on OP Labs will be coming soon.
- List of metrics that are referenced in the growth grant application

**Comment by evanameyer1** [comment]
PR created: https://github.com/opensource-observer/insights/pull/78

**Comment by evanameyer1** [comment]
https://github.com/opensource-observer/insights/pull/81
