### ISSUE TITLE
Create / update entries in OSSD for growth grant recipients

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2492]
### What is it?

This work will likely consist of two parts. First, for projects that have activity on chains that are already on OSO, we should update their project entries to include any wallets or contract addresses that are relevant to their growth grant. Second, for projects that have activity on chains that aren't yet on OSO, we should create a backlog of updates that will need to be made once we get those chains indexed from OP Labs (hopefully soon). 

FYI, here is the guide on adding/updating projects to OSS Directory: https://docs.opensource.observer/docs/contribute/project-data/#add-or-update-project-data-quick-steps

⚠️ 
Pay special to any contract addresses included in applications. In some cases, we will want to add the deployers and/or factories associated with projects. (Carl can help with this when the time comes.)

**Comment by evanameyer1** [comment]
PR from the Forked OSO directory with updated contracts and wallet addresses: [link](https://github.com/opensource-observer/oss-directory/pull/582)

Backlog: [link](https://docs.google.com/document/d/1EBY6Mxl1Aga1UrOlY3KDTTn1t27Fyos_8G4WFAmXomQ/edit?usp=sharing)

**Comment by ccerv1** [comment]
Completed here: https://github.com/opensource-observer/oss-directory/pull/583
