### ISSUE TITLE
Propose a new docs outline v2

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2510]
### What is it?

Our current docs are a big step forward from what we had previously, but still fall short of a seamless portal for new contributors. 

Some ideas of what can be improved:
- We should have better tutorials centered around intents (I want to be able to XYZ)
- We should make better threads for certain contributor personas that are easy to follow. Right now Getting Started conflates a lot of things
- The model space is really complex, and we don't have nearly enough documentation to help folks understand which model they should use for what

Some docs to take inspiration from include Stripe and Deno

**Comment by ccerv1** [comment]
Copying over my notes:

- Intro
- Get Started
    - API
    - BigQuery
    - Python SDK [soon]
- Add Your Project
    - Search For Artifacts Linked to Your Project
    - Update Artifacts 
    - Get Metrics
    - Troubleshoot Data Issues
- Get Data
    - Public Datasets
    - API
    - BigQuery
    - Static Datasets
- Contribute Data
    - Connect Your Database
    - Crawl an API
    - Upload Static Data
- Use Case Examples
    - Funder View
    - Developer Retention    
    - Cohort Analysis
    - Synthetic Controls
    - Trusted Users
    - Network Graphs
    - OpenRank
    - ROI Analysis
- Guides
    - oss-directory
        - Adding Projects
        - Adding Collections
        - Migrations
    - oss-funding
        - Adding Funders
        - Adding Rounds
        - Mapping Projects to Rounds
        - Integrating with DAOIP-5
    - dagster
    - dbt
    - SQL Mesh
    - Operations
    - Connecting OSO to Dashboarding Tools
        - Hex
        - Looker
        - Streamlit
        - Metabase
        - Tableau
    - Connecting OSO to Data Science Tools
        - Jupyter Notebook
        - Google Colab
- Reference
    - Technical Architecture
    - Event Sources
    - Event Types
    - Impact Metrics
    - Models
    - Code Style Conventions
    - FAQs
- Work With Us
    - Careers
    - Bounties
- Talks
- Subscribe for Updates

**Comment by ccerv1** [comment]
https://docs.google.com/document/d/10Az321DXZpZJ4FZy7T9GlbMhU231ye-5Tfib13RGQBM/edit?usp=sharing

**Comment by ryscheng** [comment]
Did an edit pass in the doc. Generally I like the move towards more intent-based organization
