### ISSUE TITLE
chore: update oss-directory on NPM

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2552]
### What is it?

Someone with NPM access (eg, @ryscheng) needs to do an OSSD release in order to accommodate the new chains included in [this PR](https://github.com/opensource-observer/oss-directory/pull/584)

**Comment by ryscheng** [comment]
Published oss-directory@0.0.16

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oss-directory/pull/594

**Comment by ryscheng** [comment]
Updating external-prs here
https://github.com/opensource-observer/oso/pull/2622
