### ISSUE TITLE
SM/ Announcement Graphic Templates

### ISSUE THREAD

**Issue by ciciaran** [opensource-observer/oso#2570]

**Comment by ciciaran** [comment]
[OSO Social Media Template 1 - light background w/circles](https://www.canva.com/design/DAGZqXVOG4Q/IeGVkGfLm2N7_6JfNF7Iuw/view?utm_content=DAGZqXVOG4Q&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)

[OSO Social Media Template 2 - dark background w/fold lines](https://www.canva.com/design/DAGZqadmL5w/GjQ4pppdDWXCyZ3CeDDQMA/view?utm_content=DAGZqadmL5w&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)

[OSO Partnership / Integration announcement Template](https://www.canva.com/design/DAGZrC6t160/4a3YinE3QbJj2XryQt_ADA/view?utm_content=DAGZrC6t160&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)

[Kariba Social Media Template 1 - layer image background ](https://www.canva.com/design/DAGZqe426xE/wsonTJQyooUw1LZxnt6xGw/view?utm_content=DAGZqe426xE&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)

[Kariba Social Media Template 2 - dark backround + movable gradient squares](https://www.canva.com/design/DAGZqkaNCck/u2LeytoO0RWNNezjmwOn3g/view?utm_content=DAGZqkaNCck&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)

[Kariba Partnershop / Integration announcement Template](https://www.canva.com/design/DAGZrG-nJwg/eHXpcMZH5Feie61DOj6N8w/view?utm_content=DAGZrG-nJwg&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)

[Loom video explainer](https://www.loom.com/share/6501300435b142a6bc65b3132ada2b8e?sid=8097e9d1-8fac-4aa0-adf0-8362d6b3eb09)

**Comment by ciciaran** [comment]
[A doc with links](https://docs.google.com/document/d/1_EjUsphWqvRmsLtL2WvxP7kiU9CaMK_2qU8xtoblcv0/edit?usp=sharing) is in the assets folder of the google drive. I'll keep this updated with figma links too

**Comment by ryscheng** [comment]
tyty!
