### ISSUE TITLE
Kariba graphic illustrations

### ISSUE THREAD

**Issue by ciciaran** [opensource-observer/oso#2595]

**Comment by ryscheng** [comment]
@ciciaran do you mind linking to the work product here so I can take a look? In general would be helpful for closing out any issues. Thanks!

**Comment by ciciaran** [comment]
Google [drive folder here ](https://drive.google.com/drive/folders/1hB7DC2V0JUWddF-qPusMADCSmZKR-N5Y?usp=sharing) @ryscheng
