### ISSUE TITLE
If cache's overlap duplicate events cause recorder to error

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#267]
### To Reproduce

Create two overlapping caches for the same sets of data and this will happen. In normal function this generally shouldn't happen as long as jobs are being scheduled correctly. 

### Describe the Bug

See above

### Expected Behavior

The recorder should simply ignore duplicates within pending writes (probably should warn).

**Comment by ryscheng** [comment]
@ravenac95 is this obsolete? If so , feel free to close as "unplanned"

**Comment by ravenac95** [comment]
Ya obsolete. Thank god.
