### ISSUE TITLE
Garbage collect dead artifacts

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#294]
### To Reproduce

At some point the pull-requests job was creating new "repo" artifacts. It's very possible it created replicas `GIT_REPOSITORY` artifact types of what was already in the database because string comparisons weren't normalizing to lower case when we found those names in the responses from github. It's possible this wasn't the case but we should write a script to do clean up and fix any given relations that may need to be fixed. 

The correct artifacts would be ones that are related a project. Also, there are cases were pull-requests return an unexpected artifact of a different repository for a given pull request. Those shouldn't pose a problem in this scenario. 

### Describe the Bug

See above.

### Expected Behavior

Names for repos should match regardless of case. Same goes for things like addresses.

**Comment by ravenac95** [comment]
Currently running this to check

**Comment by ryscheng** [comment]
In the future, we're going to index everything from GitHub/npm etc. And we should clean up invalid artifacts at that time.

In the medium term, since everything is seeded an oss-directory project, we can remove any artifacts without a project associated.

**Comment by ryscheng** [comment]
@ravenac95 is this still relevant?

**Comment by ravenac95** [comment]
OBE
