### ISSUE TITLE
Impact metrics dashboard for a "collection"

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#3]
### Describe the feature you'd like to request

See here for initial designs
https://github.com/hypercerts-org/os-observer/issues/54

### Describe the solution you'd like

Implement enough of a exploration UI for users to make their own queries and charts

### Describe alternatives you've considered

See here for design comparison
https://www.notion.so/network-goods/OS-Observer-UI-UX-Research-7617f3af235340baaf2b03bd8197f8e5?pvs=4

**Comment by ccerv1** [comment]
@ryscheng If this is still relevant, I assume it means rebuild what Reuven created?

**Comment by ccerv1** [comment]
Here is the [current Figma](https://www.figma.com/file/V2QgvVMsxJX6xCg7jT7v4d/OS-Observer?type=design&node-id=101%3A166&mode=design&t=iWmq2HYSqds71OyJ-1) link.

**Comment by ryscheng** [comment]
Getting started here
https://github.com/opensource-observer/oso/pull/464

**Comment by ryscheng** [comment]
Adding an API endpoint for getting data here
https://github.com/opensource-observer/oso/pull/466

**Comment by ryscheng** [comment]
Gonna mark this as a duplicate of 
https://github.com/opensource-observer/oso/issues/102
