### ISSUE TITLE
Fetch time-series data for software dependencies

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#31]
### What is it?

https://deps.dev/

They've done a really good job of exposing package versioned dependencies via API
Maintained by Google

**Comment by ryscheng** [comment]
@ravenac95 's notes on the topic
https://docs.google.com/document/d/1sUC2Q6HiEB5c4RU3IO1sNKAPEyHMimitZsG6O4eLUIs/edit

In the future, feel free to link here, or just dump thoughts directly in the issue

Noting for others that we have a call with Nesbitt on Aug 7 to discuss his thoughts on time-series

**Comment by ryscheng** [comment]
Braindumping some more notes with our call with Andrew Nesbitt

- All of the tools above are really meant for just getting current data on dependencies / dependents.
- He's open to dumping a copy of ecosystems data into a data warehouse for us to play with. 
- For time series data, might be best to use something like [repo_miner](https://github.com/andrew/repo_miner). For example, if you want to get the number of dependents over time, start with all of the current dependents. Then use repo_miner to crawl commit history and see exactly when the dependency was added and what version. This is pretty good for an approximation for how dependencies are added over time.
- Limitations: it'll miss packages that added and later removed the dependency. It is strictly accumulative, so we won't be able to see if the number of dependents ever decreases. This is probably good enough anyway

**Comment by ryscheng** [comment]
Andrew just started an export for us. He maintains all his data dumps here:
https://packages.ecosyste.ms/open-data

**Comment by ryscheng** [comment]
Current plan is

- Wire up deps.dev as a dbt source
- Write the dbt models for `ADD_DEPENDENCY`, `REMOVE_DEPENDENCY` events from deps.dev to int_events
- *Pause* - here's let's evaluate how much coverage this has over the protocol-labs collection and if we need the stuff below
- Extend our dlt integration with GitHub to fetch "last-mile" dependencies from package => repo

**Comment by ccerv1** [comment]
From Jonas:

> What would be the lift to put together a v2 of the "downstream impact" model for packages that you put together a while back? Link [here](https://ccerv1.github.io/downstream_impact/?mode=fees). Just having up to date data with all the new Superchain projects that are in OSO would be great. This could give a good basis to reason about parts of the RF Dev tooling round
