### ISSUE TITLE
on importOssDirectory, enumerate all created contracts by `factory` or `creator`

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#310]
### Describe the feature you'd like to request

These should be treated as additional implicit contract artifacts that we index for events on import

Then also index those contracts as well for all the event types we care about

A good example is SAFE

### Describe the solution you'd like

See above

### Describe alternatives you've considered

Enumerating all contract addresses in oss-directory
(removing this)

**Comment by ravenac95** [comment]
We are technically working on this with #1048
