### ISSUE TITLE
A user should be able to generate a List ✨ that meets the EAS schema

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#312]
### What is it?

The current (testnet) version of the EAS list schema is available [here](https://optimism-goerli.easscan.org/schema/view/0xc09de76e8bd3baedb951ce0f9313e66267555ab8dd901878235c5946408772f0)

Latest version [here](https://optimism.easscan.org/schema/view/0x3e3e2172aebb902cf7aa6e1820809c5b469af139e7a4265442b1c22b97c6b2a5)

**Comment by ccerv1** [comment]
I've generated a test list [here](https://optimism-agora-dev.agora-dev.workers.dev/retropgf/3/list/0x3ce7146c4cead5392c2ae106b501609bdf72ef38e66a6f2ec464ad35ce495614) using a simple query and analysis script [here](https://github.com/opensource-observer/insights/blob/main/notebooks/2023-10-29_ListStar69.ipynb). I'm going to close this out for now, as this satisfies the current requirements. 

Caveats: the user needs database access and to upload the metadata to IPFS on their own.
