### ISSUE TITLE
Diff PLN metrics in OSO and ecosyste.ms

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#313]
### What is it?

https://ipfs.ecosystem-dashboard.com/
https://libp2p.ecosystem-dashboard.com/
https://filecoin.ecosystem-dashboard.com/
https://github.com/ipfs-shipyard/ecosystem-dashboard

**Comment by davidgasquez** [comment]
Heads up! Last I checked the PLN metrics weren't very accurate. :see_no_evil:

**Comment by ccerv1** [comment]
Here is a screenshot of the metrics from the IPFS dashboard:

![Image](https://github.com/user-attachments/assets/c2f614c2-6c6a-48a8-a4c4-1d96b1dab1ca)

OSO currently tracks 9/12 metrics. The missing three metrics are: 
- Avg Resp Time
- Slow Responses
- Releases

Releases are straightforward to include in the OSO event model as they simply represent a new event type. 

However, the two metrics related to response time require some changes to the underlying OSO event model. Critically, we need to introduce some concept of an `event_id` and `event_source_id`. Trivially, we also need to create a new event type for `COMMENTED`.

Once this has been done, the implementation of the `avg_resp_time` metric might look like:

```
SELECT
  i.sample_date,
  i.event_source,
  i.to_group_id, -- project, collection, or artifact id
  'AVERAGE_RESPONSE_TIME' AS metric
  AVG(TIMESTAMPDIFF(SECOND, i.time, c.time)) / 60 AS amount
FROM events AS i
LEFT JOIN events AS c
  ON i.event_id = c.event_id
  AND c.time = (
    SELECT MIN(c1.time)
    FROM events AS c1
    WHERE
      c1.event_id = i.event_id
      AND event_type = 'COMMENTED'
  )
WHERE
  i.event_type IN ('ISSUE_OPENED', 'PR_OPENED')
  AND c.event_type = 'COMMENTED'
GROUP BY
  i.sample_date,
  i.event_source,
  i.to_group_id;
```

**Comment by ccerv1** [comment]
Created the following new issues:

- [ ] https://github.com/opensource-observer/oso/issues/1991
- [ ] https://github.com/opensource-observer/oso/issues/1992
- [ ] https://github.com/opensource-observer/oso/issues/1993
