### ISSUE TITLE
Fetch data from OpenCollective

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#32]
### What is it?

Getting

- [ ] Contributions
- [ ] Expenses

**Comment by ryscheng-mobile** [comment]
If we figure out a general purpose data replication approach into the data warehouse like this
https://github.com/opensource-observer/oso/issues/836

then that'll be a much better lift to goto OpenCollective with 
CC @ravenac95

**Comment by ryscheng** [comment]
Current plan is to write an Airbyte connector against their API

**Comment by ryscheng** [comment]
Some notes from our chat today:

- We can start with building an Airbyte connector to pull *all* Open Collective data into the data warehouse. 
- @andrew has active work to build dashboards for OC based on funding data. Let's figure out what data would be necessary for the visualizations they want.
- If these things work well, then there's a possiblity we could host the data + pipelines, and just build a frontend on top of OSO for this. There's a reasonable chance these pipelines will be useful for other ecosystems as well

**Comment by ryscheng** [comment]
First draft done
https://github.com/opensource-observer/oso/pull/1952
https://github.com/opensource-observer/oso/pull/1941
