### ISSUE TITLE
If a project forks a repo, it should not inherit that repo's commit history

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#335]
### Which area(s) are affected? (leave empty if unsure)

Indexer

### To Reproduce

Here's an [example of a forked repo](https://github.com/GoodDollar/react-native-side-menu) and a query that displays inherited commits.

```
    SELECT
        p."slug" AS project_slug,
        p."name" AS project_name,
        a."id" AS artifact_id,
        e."fromId" AS contributor,
        e."time" AS event_time,
        e."type" AS event_type
    FROM
        project p
    JOIN
        project_artifacts_artifact paa ON p."id" = paa."projectId"
    JOIN
        artifact a ON paa."artifactId" = a."id"
    JOIN
        event e ON a."id" = e."toId"
    WHERE 
        p."slug" = 'gooddollar'
        AND e."type" = 'COMMIT_CODE'
```

### Describe the Bug

The commits (and the contributor) appear to belong to the project that forked the repo. This gives the impression that a project is older / has more contributors / more code than it otherwise would.

### Expected Behavior

A project that forks a repo should only count commits that happen in its namespace subsequent to the fork and are not synced back to the origin repo

**Comment by ccerv1** [comment]
@ravenac95 I wrote a quick script to identify forked repos. You can see the output here. Would be great to remove the project:artifact link for any repo with a value of `true` in [here](https://github.com/opensource-observer/insights/blob/main/notebooks/data/2023-10-15_forks.json)

**Comment by ravenac95** [comment]
Ah I missed half of this now, I realize. `importOssDirectory` still tracks the repo but the `github-commits` collector does not pull any fork's commits.
