### ISSUE TITLE
Create Docs and Video instructions for Indexer Jobs Triggering

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#345]
### Describe the feature you'd like to request

We need to have it so any of the team can trigger indexer/oss-directory db updates.

### Describe the solution you'd like

Docs plz.

### Describe alternatives you've considered

Just docs. plz

**Comment by ccerv1** [comment]
Docs (WIP) [branch](https://github.com/opensource-observer/oso/tree/ravenac95/docs-for-collectors)

**Comment by ccerv1** [comment]
Backfilling video: https://drive.google.com/drive/folders/1LIHVQetNYce-06bOwdV6z6k8B0POtPTh

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oso/pull/499
