### ISSUE TITLE
Steer users on what to do if data is missing

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#346]
We probably want them to create a PR on oss-directory and flag it to us

**Comment by ryscheng** [comment]
Gonna send this to you @ccerv1  as you're wiring up the project/artifact pages.

I was imagining a really simple notice on the bottom that's like, think this is incorrect? send feedback using the button or link them to the respective oss-directory project file and ask them to verify it's correct. File an issue if not.

**Comment by ccerv1** [comment]
Added a dynamic link to OSS directory next to the artifact chips.



![Image](https://github.com/opensource-observer/oso/assets/42869436/804c671b-b4b1-4973-ac17-c18a5ffcff25)
