### ISSUE TITLE
Cheaper schema migrations

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#366]
In a world where we're storing our data on BigQuery, we need some mechanism for migrations.
We currently use TypeORM for this, but Idk if that is the right fit.

I'm not sure if this is the right thing, but linking anyway
https://cloud.google.com/bigquery/docs/migration-intro

**Comment by ryscheng** [comment]
Would be cool if we could write the data warehouse integrations in a way that was agnostic to whether we use BigQuery, Redshift, Snowflake etc.

**Comment by davidgasquez** [comment]
This is a great issue! Wanted to share some thoughts from the Data Engineering side. 

When using BigQuery or other warehouses, you don't usually need to run classic "migrations". Nowadays, the approach is to dump all the raw data into an append only table and then use sometething like [dbt](https://docs.getdbt.com/docs/introduction)¹ to model the data and run the migrations for you. With this approach, you don't need to run migrations for intermediary tables.

For "raw" or ingestion tables, the standard is to rely on tools like Fivetran/Airbyte/Stitch... that will manage the ingestion for you (batching, migrations, dedup, ...).

Does this makes sense? Perhaps I've interpreted the "migration" part in the wrong way!

¹ Additionally, tools like `dbt` (the tool that Dune and Flipside use) have [integrated data linting/tests](https://docs.getdbt.com/docs/build/tests) that help with https://github.com/opensource-observer/oso/issues/168.

**Comment by ryscheng** [comment]
You're totally right, the term "migrations" is probably the wrong terminology, just expressing a desire to encode changes in code so that we can keep continuously testing/deploying

**Comment by ryscheng** [comment]
@davidgasquez dbt makes total sense, especially when you pair it with Dagster to re-compute stages of the pipeline that have changed.

Do you see how people typically would make cheaper schema migrations in-place without re-computing (e.g. re-naming column)?

**Comment by davidgasquez** [comment]
> Do you see how people typically would make cheaper schema migrations in-place without re-computing (e.g. re-naming column)?

Not sure if I understood entirely the question but let me share a few things:

- For simple migrations like renaming columns, I'd rely on BigQuery DML and perhaps create a `migrations` folder on `dbt`. 
- That said, the goal with dbt is to not have migrations and never edit the source tables. If something needs to change, follow backward compatible schema evolution (new columns, new tables) and do the aggregation downstream.
- For some migrations, it might be worth to first start them as downstream views on top of partitioned/clustered datasets so it's cheap-ish to run many migrations until the final schema is settled on.

Does that make sense? Is it helpful or where you looking for something else?

**Comment by ryscheng** [comment]
This is quite old. Deprecating
