### ISSUE TITLE
Research: Gather blockchain traces and transactions in an affordable way

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#367]
BigQuery has some public datasets already for blockchain data.
For example:
https://console.cloud.google.com/marketplace/browse?filter=solution-type:dataset
https://console.cloud.google.com/marketplace/product/ethereum/crypto-ethereum-blockchain
https://console.cloud.google.com/marketplace/product/bigquery-public-data/blockchain-analytics-ethereum-mainnet-us
https://console.cloud.google.com/marketplace/product/bigquery-public-data/blockchain-analytics-optimism-mainnet-us

If BigQuery doesn't have the dataset we want, we can try using cryo.
https://github.com/paradigmxyz/cryo

**Comment by ryscheng** [comment]
Subsquid seems like an interesting approach too
https://medium.com/@dariaag/creating-parquet-datasets-with-squid-sdk-54a0262f3471

It should be able to write both to Parquet files as well as our TypeORM

**Comment by davidgasquez** [comment]
> Subsquid seems like an interesting approach too

Quickly explored how it worked and they seem to rely on a "decentralized" archive (a specialized data lake for on-chain data, optimized for batch data access). 

Basically, they pre-index the chains and plan to distribute the compressed data in chunks among the set of workers in the network (which will be rewarded by the network at some point).

Right now, they're providing a [Cockroach DB](https://docs.subsquid.io/archives/substrate/self-hosted/#database-choice) centralized instance until the Mainnet goes live.

I wouldn't worry much about where the data comes from as I'm sure some of the related projects collected in https://github.com/opensource-observer/oso/discussions/111#discussioncomment-7242418 has it (e.g: [Allium](https://docs.allium.so/) gives you BigQuery/Snowflake ready datasets for a bunch of chains)!

**Comment by ravenac95** [comment]
Repurposing this as a research task to derisk the various methods and to gather cost data for ourselves.

**Comment by ravenac95** [comment]
One thought is that we could actually run our own L2 node and pay for the basic usage of an RPC provider to be able to get L1 data (and hopefully continued L2 traces/transactions for recent blocks). 

So a machine would be something like a one time cost of ~$1500-2000 + electricity costs (if I were to run it in my place). The other option is we colocate it which is cheaper than getting a host at a cloud provider but isn't that cheap. 

Then there's also the RPC provider which, if we used alchemy (I believe they're more expensive that most) is $200/month.

**Comment by ccerv1** [comment]
Others include Flair and Indexed (Goldsky

**Comment by ravenac95** [comment]
It seems that this past week was productive at least determining that we might be able to get this through some other means. We need to follow up on these threads.

**Comment by ravenac95** [comment]
Closing this issue finally!

The plan:
* We will prototype and integration with Goldsky.
* Data would flow into GCS (unless this integration doesn't work... waiting on some confirmation)
* Daily we'll dump data into BigQuery
* We will only use this to fill gaps of data that doesn't _already_ exist as a dataset in BigQuery.
