### ISSUE TITLE
Hasura => CloudSQL

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#369]
Hasura can connect directly to BigQuery

https://hasura.io/docs/latest/databases/bigquery/index/

Let's add that connection when it's time.

Need devops solution for configuring Hasura including
- Synchronize the GraphQL and postgres schemas
- Setup ACL and rate limiting for new tables

**Comment by davidgasquez** [comment]
If you end up connecting Harusa to BigQuery you might end up with a veeeery large bill (even with caching). :money_mouth_face: 

Not entirely sure if this pattern will apply but if;

1. the dataset changes slowly (once a day, ...) 
2. end users don't require real time data
3. is less than 1TB

You could export it to files and put something like [RoAPI](https://github.com/roapi/roapi) or [Dozer](https://github.com/getdozer/dozer) on top of it.

Another approach if the data is super small and don't need a GraphQL API would be to generate static JSON files ([ala Allo](https://github.com/gitcoinco/allo-indexer)) and make that the API.

**Comment by davidgasquez** [comment]
Chiming in to share a cool product, [Tinybird](https://www.tinybird.co/). It might be a simple way to have both a fast database (Clickhouse) on top of the BigQuery data and an exposed API.

**Comment by ryscheng** [comment]
Using the Hasura CLI as of https://github.com/opensource-observer/oso/pull/851

which sets this up
