### ISSUE TITLE
Data warehouse queries to transform raw data to Collection/Project/Artifact/Event entities

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#371]
Let's start with BigQuery public data sets, like the GitHub or Ethereum public data sets.

Let's create transforms that create the aggregations/materialized views that we expect in the frontend (e.g. events_daily_by_artifact)

**Comment by davidgasquez** [comment]
I feel this is what `dbt` does perfectly! I'm happy to jump into a call and share an example or quick demo.

**Comment by ryscheng** [comment]
Oh I totally forgot about `dbt`! I vaguely recall playing with it a while ago, but it seems to have really matured
https://www.getdbt.com/product/what-is-dbt

Great suggestion, thank you

**Comment by davidgasquez** [comment]
Indeed! Is one of the core components of the data stack nowadays. Let me know if you want a quick run or demo! :blush:

**Comment by ryscheng** [comment]
Duplicate
https://github.com/opensource-observer/oso/issues/751
