### ISSUE TITLE
GraphQL anonymous rate limits

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#373]
We should consider rate limits per client.
We should also find a way to tie the requests to the client application, at least until we have a mechanism to support more general API support.

**Comment by ryscheng** [comment]
We should provide rate-limits per user and more aggressive rate limits on the anonymous role.

**Comment by ryscheng-mobile** [comment]
Rate limit config
https://hasura.io/docs/latest/security/api-limits/
https://hasura.io/docs/latest/api-reference/metadata-api/api-limits/

**Comment by ryscheng** [comment]
Starting one here
https://github.com/opensource-observer/oso/pull/865

**Comment by ryscheng** [comment]
The rate limits are added here. This is independent of authentication
https://github.com/opensource-observer/oso/pull/868
