### ISSUE TITLE
Flesh out Project and Artifact pages with widgets

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#396]
We need to create widgets (Plasmic components) for each ArtifactType.
We already have VizNPM and VizGiHub, which probably need to be updated.

We should similarly create ones for

- [ ] VizNPM
- [ ] VizGitHub
- [ ] VizTreasuryAddress
- [ ] VizContractAddress
etc

Then plop these into the Project and Artifact pages as appropriate and plumb up the EventDataProvider

**Comment by ccerv1** [comment]
@ryscheng I've gone through these and now feel comfortable wiring these up. I've tagged you on a few bugs and EventDataProvider feature requests, mostly related to GitHub stats and basic ContractAddress analysis. I'll jump back in over the weekend and make additional widgets / styling.

**Comment by ryscheng** [comment]
Project page is partially done last night. See Plasmic v23.0.0

**Comment by ccerv1** [comment]
I have wired up all of the widgets shown [here](https://www.figma.com/file/kfJBy2qsw7OsAiOPUo1fSZ/OSO-Project-Page?type=design&node-id=0%3A1&mode=design&t=lSiI0iADMgM6QnZd-1). I'm closing this issue and will open separate issues for bugs and other features.
