### ISSUE TITLE
Create weekly aggregations of event data 

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#404]
### Describe the feature you'd like to request

Event data should go from daily to weekly 

![image](https://github.com/opensource-observer/oso/assets/42869436/cebe2d7d-fd4b-4b38-aa24-07f02cd80750)

### Describe the solution you'd like

More like this

![image](https://github.com/opensource-observer/oso/assets/42869436/4a169372-1ec7-40ee-ad30-c8507cf4781f)

### Describe alternatives you've considered

na

**Comment by ryscheng** [comment]
This just creates the views
https://github.com/opensource-observer/oso/pull/457

Still need to wire to frontend

**Comment by ryscheng** [comment]
Fixing up the frontend here
https://github.com/opensource-observer/oso/pull/462

**Comment by ryscheng** [comment]
Wired up EventDataProvider here
https://github.com/opensource-observer/oso/pull/463
