### ISSUE TITLE
Add a data provider containing aggregate stats about all artifacts in a namespace

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#405]
### Describe the feature you'd like to request

Fetch data to power aggregations such as "Number of repos (on Github)", "Total contracts deployed (on Optimism)", "Number of packages (on NPM)"

### Describe the solution you'd like

Data for cards like

![image](https://github.com/opensource-observer/oso/assets/42869436/98390476-ff3e-4ce6-bc45-ad7496b5653f)

### Describe alternatives you've considered

na

**Comment by ryscheng** [comment]
I'm pretty sure this is done already. We are just using graphql queries directly to make this happen.
