### ISSUE TITLE
Add a data provider that contains developer KPIs

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#407]
### Describe the feature you'd like to request

It should contain the same timeseries aggregations as other KPIs, and apply definitions that are aligned with Electric Capital's:

![image](https://github.com/opensource-observer/oso/assets/42869436/40429f2a-94ab-403b-8d35-f5b6b46e7656)

![image](https://github.com/opensource-observer/oso/assets/42869436/19fe465d-5fcb-4765-82ca-23096ca58435)

![image](https://github.com/opensource-observer/oso/assets/42869436/eea1b45d-19ac-4908-8837-2b062f2c50a8)

![image](https://github.com/opensource-observer/oso/assets/42869436/08c714ff-7fcc-4ef6-89d5-17a0fb91dd74)

### Describe the solution you'd like

Materialized views for developers, similar to how we plan to handle users #189 

### Describe alternatives you've considered

na

**Comment by ccerv1** [comment]
@ryscheng we can close this now, ya?

**Comment by ryscheng** [comment]
Yep! I think you wired this up with the ProjectUserDataProvider already. Thanks!
