### ISSUE TITLE
Web-flow (bot) commits should be attributed to the user who merged the PR

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#410]
### Which area(s) are affected? (leave empty if unsure)

Indexer

### To Reproduce

Try the following query for hypercerts:

```
SELECT
    p."slug" AS project_slug,
    p."name" AS project_name,
    a1."name" AS artifact_name,
    a2."name" AS contributor_name,
    e."time" AS event_time,
    e."type" AS event_type
FROM
    project p
JOIN
    project_artifacts_artifact paa ON p."id" = paa."projectId"
JOIN
    artifact a1 ON paa."artifactId" = a1."id"
JOIN
    event e ON a1."id" = e."toId"
JOIN
    artifact a2 ON e."fromId" = a2."id"
WHERE 
    p."slug" = 'hypercerts'
ORDER BY
    e."time" DESC
```

And here's a pivot on the results:

![image](https://github.com/opensource-observer/oso/assets/42869436/643be6e0-69a1-44ac-b194-b9d1c8ba1ae2)

### Describe the Bug

The bug makes it so that commits made via the web-flow bot will not be properly attributed, reducing the active developer estimates and potentially other metrics related to developer activity of a project.

FWIW, [Crypto Ecosystems](https://www.developerreport.com/) also ignores bot commits.

### Expected Behavior

For repos that have automation around PR merges, we should be able to capture commits from the appropriate non-bot users.

**Comment by ravenac95** [comment]
#397 this should address this!
