### ISSUE TITLE
Gaps in coverage for some newly added projects

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#411]
### Which area(s) are affected? (leave empty if unsure)

Indexer

### To Reproduce

Run the following query for Protocol Guild projects (which were added a few days ago):
```
WITH EventData AS (
    SELECT
        p."slug" AS project_slug,
        p."name" AS project_name,
        a."name" AS artifact_name,
        e."fromId" AS contributor_id,
        e."id" AS event_id,   
        e."type" AS event_type,     
        e."time" as event_time
    FROM
        project p
    JOIN
        project_artifacts_artifact paa ON p."id" = paa."projectId"
    JOIN
        artifact a ON paa."artifactId" = a."id"
    JOIN
        event e ON a."id" = e."toId"
    JOIN
        collection_projects_project cpp ON p."id" = cpp."projectId"
    JOIN
        collection c ON cpp."collectionId" = c."id"
    WHERE
        a."namespace" = 'GITHUB'
        AND c."slug" = 'protocol-guild'
)

SELECT
    project_slug,    
    project_name,
    artifact_name,
    COUNT(DISTINCT CASE WHEN event_type = 'STARRED' THEN contributor_id END) AS stars_count,
    COUNT(DISTINCT CASE WHEN event_type = 'FORKED' THEN contributor_id END) AS forks_count,
    COUNT(DISTINCT CASE WHEN event_type IN ('COMMIT_CODE', 'PULL_REQUEST_MERGED') THEN contributor_id END) AS num_developers,
    MIN(event_time) AS first_date,
    MAX(event_time) AS last_date
FROM
    EventData
GROUP BY
    project_slug,
    project_name,
    artifact_name
ORDER BY
    project_slug;

```

Here are some of the results, including projects like [Trin](https://github.com/ethereum/trin) and [UTP](https://github.com/ethereum/utp) which have much more activity than shown here.

![image](https://github.com/opensource-observer/oso/assets/42869436/c4a8e04f-4c42-47f9-a434-8b2b55056d0b)

### Describe the Bug

There are significant gaps in event data, although recent events (last few days) appear to be indexing properly. This suggests one of the historical big indexing runs failed and we haven't gone back to get the data again.

### Expected Behavior

Complete historical data with no gaps

**Comment by ryscheng** [comment]
I'm gonna close this for now, because I see GitHub actions flows passing for the most part and we fixed a couple related bugs.

@ccerv1 is still noticing gaps in the data, which he will file subsequent issues for.
