### ISSUE TITLE
Frontend builds need to be fixed post EventType table migration

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#425]
### To Reproduce

There are builds on the frontend are failing due to schema changes. 

### Describe the Bug

See: https://github.com/opensource-observer/oso/actions/runs/6544326563/job/17770568661

### Expected Behavior

Builds should pass

**Comment by ryscheng** [comment]
Doesn't look flakey. Looks like there are legit linting errors and the graphql queries are out of date now that the schema has been migrated.

**Comment by ravenac95** [comment]
AH! cool. Ya I didn't look into it. Will update this title. I needed it as a TODO to fix the frontend builds

**Comment by ravenac95** [comment]
Addressed
