### ISSUE TITLE
Per-user GraphQL rate limits

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#447]
Hasura has the ability to link permissions to a user table.
Once we allow users to log in, we should create query limits per user.

**Comment by ryscheng-mobile** [comment]
Rate limit config
https://hasura.io/docs/latest/security/api-limits/
https://hasura.io/docs/latest/api-reference/metadata-api/api-limits/

**Comment by ryscheng** [comment]
The rate limits are added here. This is independent of authentication
https://github.com/opensource-observer/oso/pull/868
