### ISSUE TITLE
Setup GCP Free Trial

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#452]
Not entirely blocked on this yet, but will be soon. We need to have a CC configured for our GCP account or we cannot use the free trial.

**Comment by ryscheng** [comment]
@ravenac95 I setup billing and used an IAM template on the organization.
Can you confirm you have everything you need? If so feel free to close on my behalf. Thanks!

**Comment by ravenac95** [comment]
Seems to be good!
