### ISSUE TITLE
X axis on area chart should begin on start date

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#476]
Hopefully this isn't hard, but ideally we should see the X axis start at the start date selected by the date picker (and the chart will be flat until the first event happens). This is important to give a sense of when projects actually started. You can see the discrepency in this example below.

![Image](https://github.com/opensource-observer/oso/assets/42869436/cf9d6eb7-56b9-412b-b21d-363ec5ba2f41)

**Comment by ccerv1** [comment]
Example of [Ethereum Attestation Service](https://www.opensource.observer/project/ethereum-attestation-service) at 1 year date picker

**Comment by ryscheng** [comment]
Basically just remove the trimming function in the EventDataProvider

**Comment by ryscheng** [comment]
https://github.com/opensource-observer/oso/pull/528

done here
