### ISSUE TITLE
A user should be able to click a project's collections chip and see a list of collections

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#480]
### Describe the feature you'd like to request

If a user clicks the collection chip, it expands into a component with list items enumerating the collections that project is linked to. Through this interface, the user is able trigger certain collection-related filters and click a link to go to the collections themselves.

![Image](https://github.com/opensource-observer/oso/assets/42869436/9077059e-e34c-4320-8cb8-a89cd2727780)

### Describe the solution you'd like

- P1: A user should be able to click a collection list item to go to its collection page via a link.
- P2: A user should be able to click the chip and apply filters on collection-related metrics displayed on the project page via checkboxes. (This is relevant once we have dependencies and/or want to gauge a project's "ecosystem" impact.)

### Describe alternatives you've considered

An alternative could be a multiselect, similar to what we have on the explore page. However, this could take up too much real estate.

**Comment by ryscheng** [comment]
Modal is created in Plasmic v35.0.0

Should be trivial to turn the items into links once we have 
https://github.com/opensource-observer/oso/issues/342
