### ISSUE TITLE
A modal for each artifact type that includes links to the source URLs

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#481]
### Describe the feature you'd like to request

An artifact chip represent a namespace for artifacts and the number of linked artifacts owned by that project. For instance, the number of GitHub repos it owns.

If a user clicks on an artifact chip, there should be modal with list items enumerating the artifacts that project is linked to within that namespace. Through this interface, the user is able to click a link to go to the source URL (eg, [opensource-observer/oso](https://github.com/opensource-observer/oso)).

![Image](https://github.com/opensource-observer/oso/assets/42869436/0cfab363-73d4-4c45-8dd7-154fb37840e5)

### Describe the solution you'd like

A modal with a repeating list item that links to the source URL (new tab), eg, github, npm, etherscan

### Describe alternatives you've considered

Maintain status quo and users to the project page on OSS Directory

**Comment by ccerv1** [comment]
@ryscheng if you can show me how to make one of these, I can probably do the rest. I just need help configuring the repeating element on the modal.

**Comment by ryscheng** [comment]
Done
