### ISSUE TITLE
Backfill fork and star events don't seem to be indexing for newer projects

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#500]
To replicate, run this query on IPFS:

```
SELECT
    p.id,
    p.slug,
    et.name,
    SUM(e.amount),
    MIN(e.time),
    MAX(e.time)
FROM event e
JOIN event_type et ON e."typeId" = et.id
JOIN artifact a ON e."toId" = a.id
JOIN project_artifacts_artifact paa ON a.id = paa."artifactId"
JOIN project p ON paa."projectId" = p.id
WHERE
    p."slug" = 'ipfs'
GROUP BY
    p.id,
    p.slug,
    et.name
```

It only returns stars and forks as of October 12.

**Comment by ravenac95** [comment]
This is likely because the star collector is particularly slow. We likely
need to run a couple more collectors simultaneously. It’s having trouble
keeping up

-Reuven

**Comment by ccerv1** [comment]
Implemented workaround. FYI @ryscheng your version only took the last artifact : last date combo, when we need the summation of all artifacts forks / stars on the most recent date. 

I implemented a workaround using using MAX on the project aggregates.

Will leave this open until we get to the root of the issue, but moving down to a P1.
