### ISSUE TITLE
Project fork counts don't match actuals [JS]

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#511]
There appears to be a bug in the fork indexer. It appears to affect all projects. 

This query runs on three projects:

- [rotki](https://github.com/rotki/rotki): should be around 500, currently returns 36
- [Blockscout](https://github.com/blockscout/blockscout): should be over 2000, currently returns 58
- [ipfs](https://github.com/ipfs/ipfs): should be over 1500, currently returns 165 (note this project is one of the ones also affected by #500)

```
SELECT
    p.id,
    p.slug,
    et.name,
    SUM(e.amount) AS total_events,
    MIN(e.time) AS first_event_time,
    MAX(e.time) AS last_event_time
FROM event e
JOIN event_type et ON e."typeId" = et.id
JOIN artifact a ON e."toId" = a.id
JOIN project_artifacts_artifact paa ON a.id = paa."artifactId"
JOIN project p ON paa."projectId" = p.id
WHERE
    p."slug" IN ('rotki', 'blockscout', 'ipfs')
    AND et.name = 'FORKED'
GROUP BY
    p.id,
    p.slug,
    et.name;
```

Here is the result:

![Image](https://github.com/opensource-observer/oso/assets/42869436/1278b961-76ae-44c3-8d3b-ce86b694829b)

**Comment by ravenac95** [comment]
@ccerv1 I forgot to document parts of this, but definitely some of this is just a bug/collector issue. So counting the `FORKED` won't ever work entirely because private forks don't show up in the collector's data that it retrieves (perhaps it's in the public github data on BigQuery). That being said, I do record an event `FORK_AGGREGATE_STATS` that is _supposed_ to get the aggregate stats for the forks every day. I'm realizing that if things are slow this may not get run as consistently as I'd hope.

**Comment by ccerv1** [comment]
Ahh... good to know! 

So the workaround would be to just grab the most recent value and subtract it from the value at the start of the date range. Let me try that out and see how it looks!

**Comment by ccerv1** [comment]
@ryscheng I started this .. it needs to grab the last node (most recent date)

```
query Project ($projectId: Int!, $typeIds: [Int!]) {
  events_daily_to_project_aggregate(where: {projectId: {_eq: $projectId}, typeId: {_in: $typeIds}}) {
    nodes {
      amount,
      bucketDaily
    }
  }
}


```

**Comment by ryscheng** [comment]
```
query MyQuery($artifactIds: [Int!], $typeId: Int!) {
  events_daily_to_artifact(
    where: {typeId: {_eq: $typeId}, artifactId: {_in: $artifactIds}}
    limit: 1
    order_by: {bucketDaily: desc}
  ) {
    typeId
    bucketDaily
    artifactId
    amount
  }
}
```

with typeId=22 for FORK_AGGREGATE_STATS

**Comment by ccerv1** [comment]
@ryscheng this didn't quite work (it only grabbed the last artifact : date tuple).

This seems to work for now:

```
query MyQuery($projectId: Int!, $typeId: Int!) {
  events_daily_to_project_aggregate(
    where: {typeId: {_eq: $typeId}, projectId: {_eq: $projectId}}
  ) {
    aggregate {
      max {
        amount
      }
    }
  }
}


```

**Comment by ccerv1** [comment]
This appears to resolve the issue, so closing while Reuven works on #500
