### ISSUE TITLE
Different colors for different metrics types [JS]

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#512]
E.g. onchain red, github green, NPM yellow or smth. Just so I easily understand that these are different

Options are [here](https://github.com/opensource-observer/oso/blob/main/frontend/tailwind.config.js)

**Comment by ccerv1** [comment]
@ryscheng can we pass a `fontColor` variable to the BarList component? The default color doesn't work well with lighter palettes. 

Related: can we apply [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#using_tolocalestring) to the BarList values ?



![Image](https://github.com/opensource-observer/oso/assets/42869436/85aaeec5-53b2-4c4e-bd67-70f3b4c257cf)

**Comment by ryscheng** [comment]
Done here
https://github.com/opensource-observer/oso/pull/526

This will hard-code us to both:
* always use light mode so text colors show up right (there's no way to set a custom font color via prop atm)
* use toLocaleString for formatting numbers

**Comment by ryscheng** [comment]
Oh, actually I'll leave it to you @ccerv1 to change the colors in Plasmic once this deploys. watch it on vercel

**Comment by ccerv1** [comment]
Yep, done! Thank you!
