### ISSUE TITLE
Hide dependency-based collections from multi-select UI

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#518]
These types of collections should be hidden. Basically anything other than a `Type 1` collection per Reuven's current taxonomy.

![Image](https://github.com/opensource-observer/oso/assets/42869436/4b0eeb88-66fb-49ee-b7ef-12e7b0d77da4)

**Comment by ryscheng** [comment]
Done. steps completed:

1. Update the Hasura schemas from the database (which now include a CollectionType)
2. Update Plasmic explore page to only fetch Collections where the CollectionType == "OSS_DIRECTORY"
