### ISSUE TITLE
Wrap barlists for transactions, downloads, etc in collapsable components

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#522]
A barlist like this should be wrapped in a collapsable since the info won't be useful to "90% of users"

![Image](https://github.com/opensource-observer/oso/assets/42869436/0295cfdb-18ae-4787-adea-bbd42dc8e7c9)

**Comment by ryscheng** [comment]
I'm going to re-assign this back to you @ccerv1 
This should be achievable with the built-in antd `Collapse` component.
Just put it under the `Card`, but above the `BarList` to achieve what you want.

**Comment by ccerv1** [comment]
Just made these changes for contract transactions and NPM downloads on Plasmic
