### ISSUE TITLE
Where possible, let's try to use eventType names, rather than IDs

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#529]
### What is it?

CC @ccerv1 

As of right now, we use hard-coded typeIds in a lot of places, assuming that the IDs in our database are always mapped to what we expect. But we don't really have a mechanism to ensure this.
i.e. if we have a staging database, or a developer database, it's likely that we'll have different mappings from event type id => name. That's because the id is a monotonically increasing number, which will depend on insert order.

It's a pretty easy fix to just use the event type name and join on the event_type table. We should be doing that where appropriate.

**Comment by ccerv1** [comment]
ack

**Comment by ryscheng** [comment]
I'm starting to go thru the project page and do this.
You'll find override variables like this:

```
({
  artifactIds: $queries.artifacts.data.response.data.artifact.map(a => a.id),
  typeIds: [
    "PULL_REQUEST_CREATED",
    "PULL_REQUEST_MERGED",
    "COMMIT_CODE",
    "ISSUE_CLOSED",
    "ISSUE_CREATED"
  ].map(x => $queries.eventTypes.data?.response?.data?.event_type?.find(t => t.name === x).id),
  startDate: $state.dateOptions.startDate
})
```

**Comment by ryscheng** [comment]
Added it to all the GraphQL fetchers in Plasmic
