### ISSUE TITLE
Perform QA on materialized views

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#540]
Re-run coverage tests and diff MV query results vs direct event table query results

**Comment by ryscheng** [comment]
@ccerv1 can you share some queries to reproduce what's happening and what you expect instead?

**Comment by ccerv1** [comment]
@ryscheng yes I started this issue and then reran some of the MVs that had been behaving funny yesterday ... they appear OK right now. I have changed this to a todo for me and will file any MV issues that arise separately.

**Comment by ccerv1** [comment]
Closing after doing QA directly with Reuven now
