### ISSUE TITLE
Backfill commits not showing up for certain projects

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#541]
I believe there are a few cases of this, but it's definitely affecting [geth](https://www.opensource.observer/project/go-ethereum):

```
query MyQuery {
  events_daily_to_project(where: {projectId: {_eq: 452}, typeId: {_eq: 4}}, order_by: {bucketDaily: asc}, limit: 11) {
    bucketDaily
    amount
  }
}
```

returns

```
{
  "data": {
    "events_daily_to_project": [
      {
        "bucketDaily": "2023-05-25T00:00:00+00:00",
        "amount": 5
      }
    ]
  }
}
```

However, the go-ethereum repo should have [commits dating back to 2014](https://github.com/ethereum/go-ethereum/graphs/code-frequency).

One reason could be that this repo (github.com/ethereum/go-ethereum) is also contained within Protocol Guild (which owns github.com/ethereum), and this mapping was updated after the first batch of indexing was performed.

If this is the case, then it might be necessary to redefine the repos that belong to Protocol Build so there is no overlap.

That said, if we run queries for the same project with different filters (eg, `typeId: {_eq: 3}`), then we get dates all the way back to 2014 as expected.

**Comment by ccerv1** [comment]
@ravenac95 just checked and this still seems to be an issue, at least for my test on go-ethereum (above)

**Comment by ravenac95** [comment]
Ah this works!
