### ISSUE TITLE
Results should not be displayed from deprecated collections

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#542]
The following query returns a number of deprecated collections:

```
query MyQuery {
  collection(where: {typeId: {_eq: 1}}) {    
    id
    slug
    createdAt
    updatedAt
    deletedAt
  }
}
```

For example:

```
{
      "id": 11,
      "slug": "op-govgrants-phoenix",
      "createdAt": "2023-09-30T16:39:04.552222+00:00",
      "updatedAt": "2023-09-30T16:39:04.552222+00:00",
      "deletedAt": null
},

```

A number of temporary collections were deleted in [this recent PR](https://github.com/opensource-observer/oss-directory/commit/b42c527d2582ac9c44b882a09bc3bc0b650e735f).

The issue might be related to (not) running the `importOssDirectory` action and could therefore be a very quick fix. If not, and it's more complicated, then this is P2 / grabbag category.

**Comment by ryscheng** [comment]
At the end of importOssDirectory, just mark the `deletedAt` column of any `verified` collections that weren't imported.
Then in the front-end we should only search for Collections with a null `deletedAt`.
