### ISSUE TITLE
Investigate date related errors

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#551]
This is a breaking bug. I'm not sure whether we just missed it previously, if it's related to something I did, or if the 0s trimming we rolled back caused it to appear.

I spent over an hour digging around trying to fix it to no avail, and am hoping there's something that will be obvious to you and it's a quick fix. If not, we can consider other options like disable some of the date options for now or rolling back the 0s trimming.

Anyway ...

There appear to be several issues related to how the `startDate` variable is being passed to different queries and cards.

First, note that I updated the value formula for the "max" option to 5 years (see below). Previously this was undefined and seemed to be a source of error.

![Image](https://github.com/opensource-observer/oso/assets/42869436/77b25958-e33c-4ed5-be11-845014519213)

Second, I configured the `endDate` variable in all the charts to: 

```new Date(new Date().getFullYear(), new Date().getMonth(), 0).toISOString().split('T')[0];```

![Image](https://github.com/opensource-observer/oso/assets/42869436/5582c2a1-38e3-477f-aa73-0348b10b9a2e)

Now, here are the places where I'm observing bugs.

---

### 90 Day Setting

When the setting is 90 Days, the step area charts for monthly active users & contributors only display two months of data. See below:

![Image](https://github.com/opensource-observer/oso/assets/42869436/3aa176e3-f131-491b-bf9b-ebcef1f1d3ba)

(The last month is absent for all settings, but it's most visible with the 90 day setting obviously)

### Max Setting

The total and inactive users & contributors cards return errors. See below:

![Image](https://github.com/opensource-observer/oso/assets/42869436/b8178ded-7be5-4e46-9e6e-166fec893b67)

**Comment by ccerv1** [comment]
Update: I've applied a temp fix for now that should hold for the time being. If the start date is null, I assign a hardcoded min date. 

eg, `startDate: $state.dateOptions.startDate || '2020-01-01'` for Total Users and Inactive Users

I apply '2009-01-01' for the contributor cards

Will deprioritize for now, but we should make a more durable fix.

**Comment by ccerv1** [comment]
@ryscheng there are still three issues I'm hoping you can investigate and then we can close this out:

1. The default `datePicker` setting is at 180 days, however it appears the state variable is still stuck at 1 year. So when a page loads you see something like this typically:


![Image](https://github.com/opensource-observer/oso/assets/42869436/ac6f495d-cd92-4719-9064-c327659f4d9b)

2. If I set a custom date range (try 11-01-2023) I can reliably get the app to crash (client-side exception)

3. The 90 day setting (see above) is still a problem. Related, for some reason, the chart appears to be rendering a date like 2023-10-01 from the fetcher as 2023-09-30.

**Comment by ryscheng** [comment]
In Plasmic 30.0.0 I removed the hacky DatePicker we made to the antd Date Range Picker. Much nicer
