### ISSUE TITLE
Run NPM backfill indexer

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#597]
Data from recently added projects, eg, [Hats Protocol](https://www.opensource.observer/project/hats-protocol) is missing despite packages being included in OSS Directory

**Comment by ravenac95** [comment]
Oh this is currently running! The queue is getting worked through.

**Comment by ccerv1** [comment]
@ravenac95 here's the hole in the NPM data I'm checking, FYI

```
SELECT p.id, p.slug, e.time, SUM(e.amount)
FROM event e
JOIN artifact a ON e."toId" = a.id
JOIN project_artifacts_artifact paa ON a.id = paa."artifactId"
JOIN project p ON paa."projectId" = p.id
WHERE e."typeId" = 9 AND p.slug = 'safe-global' AND e.time >= '2023-10-01'
GROUP BY p.id, p.slug, e.time
ORDER BY e.time DESC
```


![Image](https://github.com/opensource-observer/oso/assets/42869436/416900bd-993f-49c7-9135-002ef2c49b50)

**Comment by ccerv1** [comment]
Fixed and shipped!
