### ISSUE TITLE
Blog: Retrospective on RetroPGF 1 and 2

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#618]
### What is the improvement or update you wish to see?

We should run OSO analyses against RetroPGF 1 and 2 projects. 
And see how different the allocations are from what we would have recommended.

### Is there any context that might help us understand?

Not sure what conclusions to draw, I suppose it depends on what we find.
we might find that 
- The allocations are actually pretty correlated with particular metrics (e.g. stars). Is this a good or bad thing?
- Are there metrics that are completely unrepresented that are actually quite important (e.g. usage)

Perhaps the goal is to spark Twitter discussion, not steer people in particular directions.

**Comment by ryscheng** [comment]
This was largely done here
https://docs.opensource.observer/blog/impact-of-retro-funding
