### ISSUE TITLE
Connect DefiLlama TVL datasets

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#619]
### Describe the feature you'd like to request

We are all doing very similar things in terms of indexing and surfacing data.

Can we collaborate on the OSO data collective to build open infrastructure?

### Describe the solution you'd like

Maybe we need to run a fork just to get experience on how it all works.

Write up a simple design doc on what their needs are and how it fits

### Describe alternatives you've considered

TBD

**Comment by ryscheng** [comment]
https://l2beat.notion.site/Delegate-your-votes-to-L2BEAT-8ffc452bed9a431cb158d1e4e19839e3

**Comment by ryscheng** [comment]
@mdalie made a good point that we should at least figure out how to get the contracts => project mappings from Terminal, DeFiLlama, and DappRadar and populate oss-directory with it

**Comment by ccerv1** [comment]
@msilb7 has experience with the DefiLlama api

**Comment by ryscheng** [comment]
https://defillama.com/docs/api

They charge $300/mo for premium. But at the end of the day, we'd prefer to just replicate their database if they're open to it.
The goal is to power our impact metrics for RF, which hopefully will also benefit them as well. Let's try to setup a call.

So basic notes:
- I think DefiLlama is built on AWS Lambda in eu region
- They also query other APIs to get their data, you can get a sense of that in their code base, for example:
- https://github.com/DefiLlama/defillama-server/blob/master/coins/src/fetchCoingeckoData.ts
- They're writing straight to AWS databases (e.g. Dynamo)
- https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/utils/database.ts

Thinking through ways to bring the data to BigQuery, maybe the easiest is to periodically dump to S3, and then do a BQ DTS job. We could also see if there's a dlt adapter, that might be easier.

**Comment by ryscheng** [comment]
Downscoping to DefiLlama TVL data

**Comment by ryscheng** [comment]
OP Labs team is just scraping the API, I suppose we should just do the same.
