### ISSUE TITLE
Typo in README file in indexer folder

### ISSUE THREAD

**Issue by tjayrush** [opensource-observer/oso#646]
### To Reproduce

Read the README in the `indexer` subfolder

### Describe the Bug

The README in the indexer folder says to run `$ python src/zerion_scraper.py`, but that file doesn't exist. It's in `src/events/zerion_scraper.py`.

### Expected Behavior

It should point to the correct file.

**Comment by ravenac95** [comment]
This readme no longer exists. Closing this now! Thanks for the issue :)
