### ISSUE TITLE
Talk proposal for Open Source Summit NA

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#676]
https://events.linuxfoundation.org/open-source-summit-north-america/program/cfp/

Current proposal is to do something around collecting data and impact metrics with Sean/Matt from CHAOSS

**Comment by ryscheng** [comment]
Jan 14th deadline

**Comment by ryscheng** [comment]
@ravenac95 just a reminder this talk proposal is due on Jan 14th. So if we want feedback and to collaborate on with the CHAOSS folks, we need to get them something ASAP

**Comment by ravenac95** [comment]
Currently this is not a public google doc but I jotted down some ideas here: https://docs.google.com/document/d/1ASjOGiGjo-N9WKHQNgH5XD71wnXiH2FQ8DnJiqe-yc4/edit

**Comment by ravenac95** [comment]
Submitted! I'll keep post here any response we get.
