### ISSUE TITLE
Record first batch of Greenpill x Impact episodes

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#684]
### What is it?

https://docs.google.com/document/d/10mYLa0Fflpk6gPdTe9-14MVyhSuKaAiQBLvD-N85UAE/edit#heading=h.e1neftdxze0r

**Comment by ccerv1** [comment]
Done! Recorded first six episodes:
 - Intro
 - EAS
 - Juan
 - Greenpill Network
 - MetaGov
 - Hypercerts use cases
