### ISSUE TITLE
Data collective signup form

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#690]
- Apply to join the OSO Data Collective!
	- Github
	- ENS or wallet address
	- Telegram
	- Discord
	- Skills

**Comment by ccerv1** [comment]
Created [here](https://docs.google.com/forms/d/e/1FAIpQLSdfUwuzE5_n9ddfjIGel8LCyx84lU30vpmchooIGdPkTw9NuA/viewform)

**Comment by ryscheng-mobile** [comment]
@ccerv1 I deprecated all Google Forms earlier
See here for all of our short-cut links
https://github.com/opensource-observer/oso/blob/main/frontend/next.config.js

For example:
https://www.opensource.observer/forms/data-collective-interest

Can you use the Tally forms instead? Feel free to update them to include the fields you want

**Comment by ccerv1** [comment]
OK, updated and improved design of the Tally form. Original available [here](/forms/data-collective-interest). Also updated on Plasmic.
