### ISSUE TITLE
ETH Denver speaker application

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#702]
### What is it?

@ryscheng you should apply for a speaking slot! The form is [here](https://www.ethdenver.com/apps/speak). I've been asked to join a panel on grant platforms with Gitcoin and Plurality Labs, so hopefully we both get an opportunity to be on stage!

Note the deadline: **January 14 11:59 pm MST**

**Comment by ryscheng** [comment]
Here's my submission

https://docs.google.com/document/d/1aHhpzK32kQZfngVqp7dinCjlWH7kp5_PoJcNgHTw-jc/edit?usp=sharing

**Comment by ryscheng** [comment]
FWIW, I submitted to both the main ETHDenver event as a speaker, as well as the DeSci-focused application here

https://airtable.com/apptAi2tFe7I5lDvn/shrzCFRCa3n8Fk7fL
