### ISSUE TITLE
Add search functionality to docs

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#703]
We currently have an indexer configured for OSO projects pages. We should have a separate indexer for our docs. This should require two steps:

- [x] Configure the indexer in Algolia
- [x] Update the configs in our docs

**Comment by ccerv1** [comment]
@ryscheng I've updated the configs and tagged you on the PR. When you have a chance, could you configure the indexer in Algolia? I assumed it would make sense to have this be a separate indexer than the OSO projects / artifacts one.

**Comment by ryscheng** [comment]
Config here
https://github.com/opensource-observer/oso/pull/730

I've applied to their OSS docs indexing program, awaiting results.

**Comment by ryscheng** [comment]
You can manage the crawler here
https://crawler.algolia.com/admin/crawlers/14fbd8fc-16e6-47ed-a7a2-d7626d6becd5/overview
Gave everyone access to both the search index and the crawler

Updating the AppID here to use the new index
https://github.com/opensource-observer/oso/pull/731
https://github.com/opensource-observer/oso/pull/737
