### ISSUE TITLE
Secure ETHDenver community event

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#720]
If anything, this might be a good way to start fleshing out a playbook on how we want to run these types of events, start practicing that muscle.

**Comment by ryscheng** [comment]
Can post it here
https://side-events.ethdenver.com/

**Comment by ccerv1** [comment]
I'm working on getting us an afternoon for Schelling Point Sessions (small event) on Saturday March 2. Will provide more details in the next 48 hours!

**Comment by ccerv1** [comment]
Working doc [here](https://docs.google.com/document/d/1wF4Ee1N2I3JM6Xhvz7kBC-DwFpl0mda8Sh2dmL3cnL8/edit?usp=sharing)

**Comment by ccerv1** [comment]
Event went live today and we are getting lots of sign ups!
