### ISSUE TITLE
Setup Terraform for Data Pipeline Infra

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#722]
At the moment, data pipeline infrastructure has been setup manually. We should establish a basic terraform setup for the infrastructure.

**Comment by ravenac95** [comment]
Part of this was completed with #924 we now just need to add the terraform invocation into the repository. Originally I wanted to keep that out of the public repo but upon discussion we think it _should_ be there.

**Comment by ryscheng** [comment]
Put the terraform module instantiations into OSO

**Comment by ravenac95** [comment]
For now we opened up a private repo. Closing this for now. In the future we will setup the infrastructure to maintain much of the sensitive things in the public repo.
