### ISSUE TITLE
Write a guide on downloading CSV from BigQuery

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#723]
This should be clearly spelled out in the docs

**Comment by ravenac95** [comment]
@ryscheng @ccerv1 If we dump data in GCS we actually incur costs as people download. Might be better to actually put this into bigquery then we only pay storage costs but the egress costs are actually on the user. This would spread the costs a bit

**Comment by ryscheng** [comment]
Rescoping this to be a guide on how to download from BigQuery to a CSV file
