### ISSUE TITLE
Update search UI to return artifacts and collections

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#726]
The search results should also specify whether the response is a project, artifact, or collection, either via an icon or some separation in how the results are presented in the tooltip

**Comment by ryscheng** [comment]
Going to need to switch Algolia to directly fetch from BigQuery

**Comment by ryscheng** [comment]
Most recent Plasmic publish takes care of this for Projects and Collections.

Artifacts are currently not being indexed on Algolia because it blows past our free tier atm. Very to easy to turn this on when we decide we want it.
