### ISSUE TITLE
OSO Project Page lets you toggle between multiple blockchain networks

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#729]
Goto www.opensource.observer
Goto a project page (e.g. Superfluid)
Be able to see metrics toggled by different networks

**Comment by ccerv1** [comment]
@ryscheng as you are working through the onchain metrics on the frontend, can I pass this over to you?

**Comment by ryscheng** [comment]
sgtm I'll re-assign

**Comment by ryscheng** [comment]
Added a select button to the Project page in v67.0.1

**Comment by ccerv1** [comment]
Nice!!
