### ISSUE TITLE
Configure data pipelines with dagster

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#760]
### Describe the feature you'd like to request

Depends on #759 (and likely #758)

We need to configure our data pipelines (cloudquery, dbt, etc.) in dagster so that the data pipeline can be better managed that just github actions. This will give visibility into any errors in the data pipeline and hopefully a more transparent look into the health of the system.

### Describe the solution you'd like

dagster is configured to manage our data pipelines. 

### Describe alternatives you've considered

Considered using other tools like kestra, but dagster is all python and we are trying to limit the explosion of languages in use. The most important thing is that pipelines are managed as code.

**Comment by davidgasquez** [comment]
Happy to help with the `dbt` integration!
