### ISSUE TITLE
Filecoin source data

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#764]
### What is it?

Looks like they maintain public Google datasets here, so it might be easier to integrate than expected

https://lilium.sh/data/dumps/
https://filecoin-data-portal.on-fleek.app/index.html

**Comment by ryscheng** [comment]
@ravenac95 @ccerv1 can we see if Arbitrum and Optimism does something similar for transactions and traces data?

**Comment by davidgasquez** [comment]
> can we see if Arbitrum and Optimism does something similar for transactions and traces data?

Transactions for these chains should be available on BigQuery preview datasets!

- `bigquery-public-data.goog_blockchain_arbitrum_one_us`
- `bigquery-public-data.goog_blockchain_optimism_mainnet_us`

Traces are a different beast! :sweat_smile:

**Comment by ryscheng** [comment]
`select   *  from `lily-data.lily.block_headers` order by height desc`

They're still working on documentation, we can ask David for more details.

We should publish this on our Data Exchange

**Comment by davidgasquez** [comment]
I think there might be some tables with duplicates and missing data so perhaps the best thing would be to create a small dataset with simple views deduplicating and exposing only the useful / complete tables.

**Comment by ryscheng** [comment]
Debugging the Filecoin data transfer job here
https://github.com/opensource-observer/oso/pull/2073

**Comment by ryscheng** [comment]
Attempting another auth fix here
https://github.com/opensource-observer/oso/pull/2081

**Comment by ryscheng** [comment]
Getting closer...
https://github.com/opensource-observer/oso/pull/2082

**Comment by ryscheng** [comment]
Adding more auth scopes
https://github.com/opensource-observer/oso/pull/2083

**Comment by ryscheng** [comment]
It worked!
https://dagster.opensource.observer/runs/dbae570a-c146-4532-87a0-f4408323c6f3

**Comment by davidgasquez** [comment]
:rocket:
