### ISSUE TITLE
Hasura configurations continuously deployed

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#778]
### Describe the feature you'd like to request

Right now, anytime the schema changes, we need to manually configure Hasura to resync the schema, and setup access control.

### Describe the solution you'd like

It'd be nice if this was continuously deployed anytime we make changes.
I think there is a Hasura terraform provider, but not sure if that suits this purpose

### Describe alternatives you've considered

Keep manually configuring

**Comment by ryscheng-mobile** [comment]
@ravenac95 

Notes from today. We should try to use the Hasura CLI metadata migrations
https://hasura.io/docs/latest/migrations-metadata-seeds/manage-metadata/

**Comment by ryscheng** [comment]
From @ravenac95 
`find dbt/models/marts/ -name "*.sql" -type f -exec sh -c 'basename $0 .sql' {} \; | xargs -n1 xargs -0 printf "bq_%s\n"`

**Comment by ryscheng-mobile** [comment]
https://hasura.io/docs/latest/migrations-metadata-seeds/migrations-metadata-setup/
https://hasura.io/docs/latest/cloud-ci-cd/github-integration/#initial-setup
https://hasura.io/docs/latest/migrations-metadata-seeds/metadata-format/#tablesyaml

**Comment by ryscheng** [comment]
Here's a start to the metadata config
https://github.com/opensource-observer/oso/pull/851

Remaining things:
- Auto-generated tables based on the dbt models
- GitHub action to deploy on merge to main
- Auth hooks for checking API keys
- API rate limits based on your role

**Comment by ryscheng** [comment]
Auto-generated tables here via a script
https://github.com/opensource-observer/oso/pull/861

**Comment by ryscheng** [comment]
GitHub workflow here
https://github.com/opensource-observer/oso/pull/869
