### ISSUE TITLE
BigQuery OAuth

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#779]
### Describe the feature you'd like to request

With our identity provider, it'd be nice to allow users to connect to the BigQuery API and submit jobs using the user's token, so that the user is billed directly, rather than us.

### Describe the solution you'd like

Client-side OAuth

### Describe alternatives you've considered

Running things through our server using our Cloud keys

**Comment by ryscheng** [comment]
So technically we are getting the oAuth scope now. it's considered a sensitive scope, so we get really scary warnings until we can verify our service with Google, which can't happen until we build the thing. 

I'll move this to the custom SQL epic

**Comment by ryscheng** [comment]
Now that we have a Clickhouse cluster, we probably don't want to be doing this anymore. Will close this out in favor of Clickhouse-based queries.
