### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#781]

**Comment by ryscheng** [comment]
Restructuring docs here
https://github.com/opensource-observer/oso/pull/785

**Comment by ryscheng** [comment]
Outline getting started here
https://github.com/opensource-observer/oso/pull/788

**Comment by ryscheng** [comment]
Revert canonical URL back to docs.opensource.observer
https://github.com/opensource-observer/oso/pull/794

**Comment by ryscheng** [comment]
starting a devops guide here
https://github.com/opensource-observer/oso/pull/863

**Comment by ryscheng** [comment]
Added more details here
https://github.com/opensource-observer/oso/pull/921

**Comment by ryscheng** [comment]
Contribute restructure here
https://github.com/opensource-observer/oso/pull/920
