### ISSUE TITLE
A user can trigger an indexing update via API

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#8]
### What is it?

In addition to having cron jobs that update all organizations in the database regularly, a user should be able to trigger re-indexing or an update for a specific organization. A common example would be if a new organization adds itself, then it would want to have it's results indexed and available ASAP.

**Comment by ryscheng** [comment]
This is already do-able via GitHub actions, but it'll be a privileged process for the foreseeable future because of cost-management
