### ISSUE TITLE
Expose BigQuery public data sets and docs on how to use

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#838]
We should terraform expose BigQuery data sets as public. Anything exposed in Hasura via our API should also be queryable from BigQuery directly.

We should also add documentation on how to get setup from scratch using the BigQuery retail UX.

**Comment by ryscheng** [comment]
@ravenac95 Let's use this to track the docs around how to use our public data sets? i.e. anyone should be able to come to our docs and follow some steps to get started on BigQuery quickly

**Comment by davidgasquez** [comment]
Hey! Wanted to raise that there are I think two ways of exposing datasets in BigQuery to the public. Sharing and Analytics Hub. 

I think the recommended approach is via the [Analytics Hub](https://cloud.google.com/bigquery/docs/analytics-hub-introduction).

Also, if you reach to BQ, they might give some credits for publishing an open dataset. Usually, they take care of the storage costs, which is not a lot but still helpful!

**Comment by ravenac95** [comment]
@davidgasquez oh I wasn't aware of the analytics hub. For now it's exposed as a public dataset like the githubarchive is but I'll take a look at that later! I'll add things to the docs later today.

**Comment by ravenac95** [comment]
This was actually closed with #956
