### ISSUE TITLE
Explore indexed.xyz / Goldsky for blockchain data

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#839]
https://docs.indexed.xyz/examples/benthos_local_hasura

looks like you can stream the data from an S3 bucket

**Comment by ryscheng** [comment]
Related
https://docs.goldsky.com/mirror/sources/direct-indexing

**Comment by ryscheng** [comment]
Update on status: we made a team on Goldsky and are starting to plumb up a data pipeline!
We got a Jeff checking if it's easy for them to stream to GCS, which we can import into BigQuery

**Comment by ryscheng** [comment]
It would be nice to have this pipeline up with a dbt model to go from raw => what we currently export from Dune

**Comment by ryscheng** [comment]
Current status: shared access to Goldsky's service account, awaiting writes from them

**Comment by ccerv1** [comment]
Closing this out. Next action will be to complete the de-duping and get GS as a complete substitute.
