### ISSUE TITLE
Artifact/Project/Collection KPI dbt model

### ISSUE THREAD

**Issue by ryscheng-mobile** [opensource-observer/oso#841]
Let's just create a pre-compute stage that takes every KPI card in the project page and pre-compute it in dbt.

That way we have a project_kpi table with 1 row per project, 1 column per metric. Makes it trivially easy to build a fast project page or our collections table.

We should also refactor the Project Page to do 1 top-level query, and plumb it into each KPI card.

**Comment by ryscheng** [comment]
@ravenac95 as per discussion today
If easy to do it per artifact, project, and collection, let's do that too

**Comment by ryscheng** [comment]
@ccerv1 this is the issue for the KPIs
