### ISSUE TITLE
Docs: How to contribute to the data pipeline (e.g. dbt models)

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#848]
### What is the improvement or update you wish to see?

We should expand the docs on how to contribute to the pipeline, e.g. with new dbt models

### Is there any context that might help us understand?

It's okay to point to other docs (e.g. dbt) for more details, but we should probably have guides that tell you everything you need to do in 1 place in the context of OSO (i.e. ending in a PR to the OSO GitHub repo)

### Does the docs page already exist? Please link to it.

https://docs.opensource.observer/docs/contribute/data-engineering/creating-pipeline

**Comment by ravenac95** [comment]
Closed with #911
