### ISSUE TITLE
Remaining dbt models

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#857]
### What is it?

- [x] Add `artifact_id`, `project_id`, and `collection_id`, which will need to be added to basically every table.
- [x] `user_namespace` in the `projects` and `collections`. (should our namespace be `oso`?)
- [x] `artifact_current_name` - need to be able to search by the current name, type, namespace
- [x] collection event tables (daily, weekly, monthly), (to, from)

And this issue afterwards
https://github.com/opensource-observer/oso/issues/841

**Comment by ryscheng** [comment]
- [ ] artifacts_by_project_slugs. Let's include artifact_latest_name, artifact_id, and project_id, project_user_namespace
- [ ] projects_by_collection_slugs. We should similarly include project_id, collection_id, collection_user_namespace, project_user_namespace
- [ ] I think we're still missing events_daily/weekly/monthly_to/from_collection
- [ ] More minor, for first/last contribution, is artifact_id => from_artifact_id, and project_id => to_project_id? Just trying to be clear which is the from and to

**Comment by ravenac95** [comment]
@ryscheng use `artifacts_by_project` and `projects_by_collection`. The from/to collection _should_ be there.

**Comment by ravenac95** [comment]
@ryscheng closing for now. as I believe this was all completed.
