### ISSUE TITLE
Reorganize the data warehouse code

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#886]
### Describe the feature you'd like to request

This is a proposal to collect the warehouse code into a single top-level directory.

### Describe the solution you'd like

The proposal is as follows:

```
warehouse/
    dbt/ # Move the current DBT directory
    cloudquery/ # Move the current cloudquery directory here
    common/ # Common python (or even js) libraries go here
    ops/ # warehouse related ops code goes here (like bq2cloudsql) and the scripts to package cloudquery plugins to docker
```

### Describe alternatives you've considered

The current existing organization is less than ideal

**Comment by ryscheng** [comment]
Couple requests:

- Can we minimize the amount of nesting? Like I'm cool with some nesting to organize, but ideally not deeply nested. Something like 1 top-level category, but everything on the second level should have a package.json?
```
warehouse/dbt
warehouse/cloudquery-oss-directory
warehouse/cloudquery-github-resolve-repos
warehouse/bq2cloudsql
apps/docs
apps/frontend
apps/hasura
packages/indexer
```
- Can we use turbo monorepo for everything? Including python? All you need to do is have a package.json with `name` and `scripts`, but it'd be nice for the CI to build and test everything in our monorep, not just JavaScript
https://github.com/vercel/turbo/discussions/1077
