### ISSUE TITLE
Create a data collector for NPM downloads

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#899]
We need to pull NPM download data and load it into bigquery.

**Comment by ryscheng** [comment]
You can see the old version we used to have here
https://github.com/opensource-observer/oso/blob/0b131a7b2fc4829c64f5f6034237d1c43b9b9364/indexer/src/events/npm.ts#L152

https://github.com/opensource-observer/oso/tree/0b131a7b2fc4829c64f5f6034237d1c43b9b9364
