### ISSUE TITLE
Change the csv export gcs bucket's location to match cloudsql deployment

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#910]
Currently `oso-csv-exports` is being used as the transitory GCS bucket for `bq2cloudsql`. However, we seem to be incurring transfer charges (not large) between it's multi-region `us` and `us-central1` (CloudSQL's location). In theory we should be able to save money by having that bucket match the cloudsql location.

**Comment by ryscheng** [comment]
From what I can tell in our June bill
BigQuery network costs were $0.70. 
GCS netwwork costs were $107

**Comment by ravenac95** [comment]
Ah ya. This is probably not all the important then. That almost seems more like it’s just normal usage as opposed to cost of transfer for all that data
