### ISSUE TITLE
PRs from forks will fail CI tests

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#946]
### Which area(s) are affected? (leave empty if unsure)

Other

### To Reproduce

Fork `oso`. Submit a PR. It should fail CI tests

### Describe the Bug

https://stackoverflow.com/questions/58737785/github-actions-empty-env-secrets
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow

We make use of GitHub secrets right now, which are excluded from the GitHub actions runner for anyone who does not have `write` permissions for the repo
This will cause builds to fail

### Expected Behavior

Outside PRs should succeed, even if you don't have write permissions.

We should refactor our CI tests to not need secrets, which I think is possible.

**Comment by ravenac95** [comment]
#1113 - was the final issue
