### ISSUE TITLE
Explore automatically generating time-series daily/monthly/weekly models

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#975]
### Describe the feature you'd like to request

We currently manually create the daily/monthly/weekly models for events. It would be nicer from a code maintenance perspective to have something automatically generate those models from a single abstract definition.

### Describe the solution you'd like

We would have some abstract definition that we can use as a template to generate the daily/weekly/monthly models for a time-series model. 

### Describe alternatives you've considered

Currently we're doing this manually (copy and paste ftw)

**Comment by ryscheng** [comment]
Going to de-prioritze this for now. The intention was to have MetricFlow do this for us automatically
https://github.com/opensource-observer/oso/issues/1179

But MetricFlow turned into a paid cloud product just now, so we can either:
- Pay for dbt Team tier and try again
- Write our own scripts to automate this.

Going to punt this decision till later

**Comment by ryscheng** [comment]
This is technically done with Cube now! Closing in favor of follow-on work to hook it up to the UI
