### ISSUE TITLE
Design first Kariba Data Challenge

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#989]
We should start working out our playbook as we do it.
Should be announced in all the channels, including starting our first newsletter

**Comment by ccerv1** [comment]
https://docs.google.com/document/d/11e6450FHaJVnzSkdCsClFFF_F7iznnUT6XYDoR_ADPs/edit?usp=sharing

**Comment by ryscheng** [comment]
We'll probably split this into multiple (~2) challenges across April / May based on available datasets
